[package]
name = "ruvm-linux-user"
description = "Linux user mode emulation."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 4

[dependencies]
libc.workspace = true
ruvm-jit.workspace = true
ruvm-jit-core.workspace = true
ruvm-mem.workspace = true
ruvm-target-arm.workspace = true
ruvm-target-riscv.workspace = true
ruvm-target-x86.workspace = true
ruvm-user-common.workspace = true

[lints]
workspace = true
