[package]
name = "ruvm-machine-s390x"
description = "The s390-ccw-virtio machine."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]

[lints]
workspace = true
