[package]
name = "ruvm-machine-x86"
description = "x86 machines: pc, q35, microvm, isapc, nitro and Xen."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]
ruvm-base.workspace = true
ruvm-firmware.workspace = true
ruvm-hw-acpi.workspace = true
ruvm-hw-char.workspace = true
ruvm-hw-core.workspace = true
ruvm-hw-intc.workspace = true
ruvm-hw-pci.workspace = true
ruvm-hw-timer.workspace = true
ruvm-hw-virtio.workspace = true
ruvm-mem.workspace = true
ruvm-virtio-queue.workspace = true

[lints]
workspace = true
