[package]
name = "ruvm-machine-x86"
description = "x86 machines: pc, q35, microvm, isapc, nitro and Xen."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 1

[dependencies]
ruvm-accel.workspace = true
ruvm-base.workspace = true
ruvm-firmware.workspace = true
ruvm-hw-acpi.workspace = true
ruvm-hw-char.workspace = true
ruvm-hw-core.workspace = true
ruvm-hw-i2c.workspace = true
ruvm-hw-input.workspace = true
ruvm-hw-intc.workspace = true
ruvm-hw-pci.workspace = true
ruvm-hw-storage.workspace = true
ruvm-hw-timer.workspace = true
ruvm-hw-virtio.workspace = true
ruvm-jit.workspace = true
ruvm-jit-core.workspace = true
ruvm-mem.workspace = true
ruvm-migration.workspace = true
ruvm-target-x86.workspace = true
ruvm-virtio-queue.workspace = true
ruvm-vmstate.workspace = true

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
kvm-bindings.workspace = true
kvm-ioctls.workspace = true
ruvm-accel-kvm.workspace = true
vmm-sys-util.workspace = true

[dev-dependencies]
flate2.workspace = true
ruvm-hw-misc.workspace = true

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dev-dependencies]
ruvm-accel-kvm.workspace = true

[lints]
workspace = true
