[package]
name = "ruvm-machine-x86"
description = "x86 machines: pc, q35, microvm, isapc, nitro and Xen."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]

[lints]
workspace = true
