[package]
name = "ruvm-jit-x86_64"
description = "The x86-64 host backend for the ruvm JIT."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 14

[dependencies]
libc.workspace = true
ruvm-jit-core.workspace = true
ruvm-jit-interp.workspace = true

[lints]
workspace = true
