[package]
name = "ruvm-vfio-user"
description = "The vfio-user protocol, client and server, without libvfio-user."
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]

[lints]
workspace = true
