[package]
name = "ruvm-audio"
description = "The audio core, mixing engine and audio backends."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]
alsa = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
libpulse-binding = { workspace = true, optional = true }
pipewire = { workspace = true, optional = true }
ruvm-base.workspace = true
ruvm-hw-core.workspace = true
ruvm-qapi.workspace = true

[features]
# The dbus audiodev type, which comes with -display dbus.
ui-dbus = ["ruvm-qapi/ui-dbus"]
# The alsa audiodev type, over the system's ALSA library.
audio-alsa = ["dep:alsa", "dep:libc", "ruvm-qapi/audio-alsa"]
# The pa audiodev type, over the system's PulseAudio client library.
audio-pa = ["dep:libpulse-binding", "ruvm-qapi/audio-pa"]
# The pipewire audiodev type, over the system's PipeWire library.
audio-pipewire = ["dep:pipewire", "dep:libc", "ruvm-qapi/audio-pipewire"]

[lints]
workspace = true
