// SPDX-License-Identifier: GPL-2.0-or-later

//! The F, D and Zfa instructions, the Zfhmin and Zfbfmin instructions and the compressed
//! floating point loads and stores, a port of QEMU's `trans_rvf.c.inc`, `trans_rvd.c.inc`,
//! `trans_rvzfa.c.inc`, the Zfhmin parts of `trans_rvzfh.c.inc` and the scalar parts of
//! `trans_rvbf16.c.inc`, with the floating point parts of `translate.c` (`gen_set_rm()`,
//! `gen_nanbox_s()`, `gen_check_nanbox_s()`, `gen_nanbox_h()`).
//!
//! The model is RV64 with F, D, C and Zfa and without Zfinx, Zdinx, Zhinx, Zhinxmin, Zcf or
//! Zama16b, so the register of an operand is always the `cpu_fpr` global, single and half
//! precision values are NaN boxed, and the Zfh arithmetic, `fmvh.x.d` and `fmvp.d.x` (RV32
//! only) keep the default `trans_*` that returns false. `flh`, `fsh`, `fmv.x.h`, `fmv.h.x`
//! and the conversions check `cfg.ext_zfhmin` and `cfg.ext_zfbfmin`. `c.flw` and
//! `c.fsw` share their encodings with `c.ld` and `c.sd`, which come first in their decode
//! groups on RV64, so they are never reached and keep the default as well.
//!
//! The `trans_*` methods are generated by [`fp_trans32`] and [`fp_trans16`] inside the
//! decoder trait impls of `translate.rs`; each one is a single call into this file.

use ruvm_jit_core::ir::TempI64;
use ruvm_jit_core::types::Cond;
use ruvm_jit_core::{MemOp, Temp};

use super::fpu;
use super::helpers::Def;
use super::translate::S;
use crate::cpu::{EXT_STATUS_DISABLED, RISCV_FRM_DYN, RISCV_FRM_RTZ};
use crate::decode::insn32::{arg_i, arg_s};

/// The upper half of a NaN boxed single precision value.
const NANBOX_S: u64 = 0xffff_ffff_0000_0000;
/// The canonical single precision NaN, NaN boxed.
const NANBOXED_NAN_S: u64 = 0xffff_ffff_7fc0_0000;
/// The upper bits of a NaN boxed half precision or bf16 value, `gen_nanbox_h()`.
const NANBOX_H: u64 = 0xffff_ffff_ffff_0000;
/// The sign bit of a single precision value.
const SIGN_S: i64 = 1 << 31;

/// The `fli.s` values, NaN boxed, indexed by the `rs1` field.
pub(super) const FLI_S: [u64; 32] = [
    0xffffffffbf800000, // -1.0
    0xffffffff00800000, // minimum positive normal
    0xffffffff37800000, // 1.0 * 2^-16
    0xffffffff38000000, // 1.0 * 2^-15
    0xffffffff3b800000, // 1.0 * 2^-8
    0xffffffff3c000000, // 1.0 * 2^-7
    0xffffffff3d800000, // 1.0 * 2^-4
    0xffffffff3e000000, // 1.0 * 2^-3
    0xffffffff3e800000, // 0.25
    0xffffffff3ea00000, // 0.3125
    0xffffffff3ec00000, // 0.375
    0xffffffff3ee00000, // 0.4375
    0xffffffff3f000000, // 0.5
    0xffffffff3f200000, // 0.625
    0xffffffff3f400000, // 0.75
    0xffffffff3f600000, // 0.875
    0xffffffff3f800000, // 1.0
    0xffffffff3fa00000, // 1.25
    0xffffffff3fc00000, // 1.5
    0xffffffff3fe00000, // 1.75
    0xffffffff40000000, // 2.0
    0xffffffff40200000, // 2.5
    0xffffffff40400000, // 3
    0xffffffff40800000, // 4
    0xffffffff41000000, // 8
    0xffffffff41800000, // 16
    0xffffffff43000000, // 2^7
    0xffffffff43800000, // 2^8
    0xffffffff47000000, // 2^15
    0xffffffff47800000, // 2^16
    0xffffffff7f800000, // +inf
    0xffffffff7fc00000, // canonical NaN
];

/// The `fli.d` values, indexed by the `rs1` field.
pub(super) const FLI_D: [u64; 32] = [
    0xbff0000000000000, // -1.0
    0x0010000000000000, // minimum positive normal
    0x3ef0000000000000, // 1.0 * 2^-16
    0x3f00000000000000, // 1.0 * 2^-15
    0x3f70000000000000, // 1.0 * 2^-8
    0x3f80000000000000, // 1.0 * 2^-7
    0x3fb0000000000000, // 1.0 * 2^-4
    0x3fc0000000000000, // 1.0 * 2^-3
    0x3fd0000000000000, // 0.25
    0x3fd4000000000000, // 0.3125
    0x3fd8000000000000, // 0.375
    0x3fdc000000000000, // 0.4375
    0x3fe0000000000000, // 0.5
    0x3fe4000000000000, // 0.625
    0x3fe8000000000000, // 0.75
    0x3fec000000000000, // 0.875
    0x3ff0000000000000, // 1.0
    0x3ff4000000000000, // 1.25
    0x3ff8000000000000, // 1.5
    0x3ffc000000000000, // 1.75
    0x4000000000000000, // 2.0
    0x4004000000000000, // 2.5
    0x4008000000000000, // 3
    0x4010000000000000, // 4
    0x4020000000000000, // 8
    0x4030000000000000, // 16
    0x4060000000000000, // 2^7
    0x4070000000000000, // 2^8
    0x40e0000000000000, // 2^15
    0x40f0000000000000, // 2^16
    0x7ff0000000000000, // +inf
    0x7ff8000000000000, // canonical NaN
];

/// The `fsgnj` variants.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Sgnj {
    /// `fsgnj`: the sign of rs2.
    Copy,
    /// `fsgnjn`: the inverted sign of rs2.
    Neg,
    /// `fsgnjx`: the sign of rs1 xor the sign of rs2.
    Xor,
}

impl S<'_, '_> {
    /// `REQUIRE_FPU`: whether `mstatus.FS` is off, which makes every floating point
    /// instruction illegal.
    pub(super) fn fpu_off(&self) -> bool {
        self.d.mstatus_fs == EXT_STATUS_DISABLED
    }

    /// `gen_set_rm()`: make `rm` the rounding mode of the helpers that follow, unless the
    /// block already did.
    pub(super) fn gen_set_rm(&mut self, rm: i32) {
        if self.d.frm == rm {
            return;
        }
        self.d.frm = rm;
        if rm == RISCV_FRM_DYN as i32 {
            // The helper returns only if frm is valid.
            self.d.frm_valid = true;
        }
        // The helper may raise an illegal instruction exception.
        self.decode_save_opc(0);
        let env = self.env();
        let c = self.c32(rm);
        self.call(&fpu::SET_ROUNDING_MODE, None, &[env.into(), c.into()]);
    }

    /// `gen_set_rm_chkfrm()`: [`S::gen_set_rm`] for a static rounding mode that also
    /// checks `frm`.
    pub(super) fn gen_set_rm_chkfrm(&mut self, rm: i32) {
        if self.d.frm == rm && self.d.frm_valid {
            return;
        }
        self.d.frm = rm;
        self.d.frm_valid = true;
        // The helper may raise an illegal instruction exception.
        self.decode_save_opc(0);
        let env = self.env();
        let c = self.c32(rm);
        self.call(&fpu::SET_ROUNDING_MODE_CHKFRM, None, &[env.into(), c.into()]);
    }

    /// `gen_set_fpr_hs()` and `gen_set_fpr_d()` without Zfinx: `rd = v`.
    fn set_fpr(&mut self, rd: i32, v: TempI64) {
        let f = self.fpr(rd);
        self.f().gen_mov_i64(f, v);
    }

    /// `gen_nanbox_s()`.
    fn gen_nanbox_s(&mut self, out: TempI64, v: TempI64) {
        self.f().gen_ori_i64(out, v, NANBOX_S as i64);
    }

    /// `gen_check_nanbox_s()`: a value that is not NaN boxed reads as the canonical NaN.
    fn gen_check_nanbox_s(&mut self, out: TempI64, v: TempI64) {
        let t_max = self.c64(NANBOX_S as i64);
        let t_nan = self.c64(NANBOXED_NAN_S as i64);
        self.f().gen_movcond_i64(Cond::Geu, out, v, t_max, v, t_nan);
    }

    /// Call helper `h` with `env` and `srcs`, the result in a fresh temp.
    fn fp_call(&mut self, h: &Def, srcs: &[TempI64]) -> TempI64 {
        let env = self.env();
        let mut args = [Temp::from(env); 4];
        for (a, &s) in args[1..].iter_mut().zip(srcs) {
            *a = s.into();
        }
        let d = self.new64();
        self.call(h, Some(d.into()), &args[..=srcs.len()]);
        d
    }

    /// The floating point registers `rs`.
    fn fprs<const N: usize>(&self, rs: [i32; N]) -> [TempI64; N] {
        rs.map(|r| self.fpr(r))
    }

    /// `rd = h(env, rs...)` with rounding mode `rm` (none for the operations that do not
    /// round) for a floating point `rd`.
    pub(super) fn fp_ff<const N: usize>(
        &mut self,
        rd: i32,
        rs: [i32; N],
        rm: Option<i32>,
        h: &Def,
    ) -> bool {
        if self.fpu_off() {
            return false;
        }
        let srcs = self.fprs(rs);
        if let Some(rm) = rm {
            self.gen_set_rm(rm);
        }
        let d = self.fp_call(h, &srcs);
        self.set_fpr(rd, d);
        self.mark_fs_dirty();
        true
    }

    /// `rd = h(env, rs...)` with rounding mode `rm` for an integer `rd`: compares,
    /// conversions to integers and `fclass`. The helpers mark `mstatus.FS` themselves.
    pub(super) fn fp_xf<const N: usize>(
        &mut self,
        rd: i32,
        rs: [i32; N],
        rm: Option<i32>,
        h: &Def,
    ) -> bool {
        if self.fpu_off() {
            return false;
        }
        let srcs = self.fprs(rs);
        if let Some(rm) = rm {
            self.gen_set_rm(rm);
        }
        let d = self.fp_call(h, &srcs);
        self.set_gpr(rd, d);
        true
    }

    /// `rd = h(env, x[rs1])` with rounding mode `rm`: conversions from integers.
    pub(super) fn fp_fx(&mut self, rd: i32, rs1: i32, rm: i32, h: &Def) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.gpr(rs1);
        self.gen_set_rm(rm);
        let d = self.fp_call(h, &[src]);
        self.set_fpr(rd, d);
        self.mark_fs_dirty();
        true
    }

    /// `fclass.d`, whose helper takes no `env`.
    pub(super) fn fp_fclass_d(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.fpr(rs1);
        let d = self.new64();
        self.call(&fpu::FCLASS_D, Some(d.into()), &[src.into()]);
        self.set_gpr(rd, d);
        true
    }

    /// `fcvtmod.w.d`: always truncates.
    pub(super) fn fp_fcvtmod_w_d(&mut self, rd: i32, rs1: i32) -> bool {
        self.fp_xf(rd, [rs1], Some(RISCV_FRM_RTZ as i32), &fpu::FCVTMOD_W_D)
    }

    /// `flw` and `fld`: `fld` loads 8 bytes, `flw` loads 4 and NaN boxes them. QEMU's
    /// `MO_ATOM_IFALIGN` is the default atomicity of `MemOp`, so it needs no flag.
    pub(super) fn fp_load(&mut self, a: &arg_i, double: bool) -> bool {
        if self.fpu_off() {
            return false;
        }
        let memop = if double { MemOp::LEUQ } else { MemOp::LEUL };
        self.decode_save_opc(0);
        let addr = self.address(a.rs1, i64::from(a.imm));
        let dest = self.fpr(a.rd);
        let idx = self.d.mem_idx;
        self.f().gen_qemu_ld_i64(dest, addr, idx, memop);
        if !double {
            self.gen_nanbox_s(dest, dest);
        }
        self.mark_fs_dirty();
        true
    }

    /// `fsw` and `fsd`.
    pub(super) fn fp_store(&mut self, a: &arg_s, double: bool) -> bool {
        if self.fpu_off() {
            return false;
        }
        let memop = if double { MemOp::LEUQ } else { MemOp::LEUL };
        self.decode_save_opc(0);
        let addr = self.address(a.rs1, i64::from(a.imm));
        let src = self.fpr(a.rs2);
        let idx = self.d.mem_idx;
        self.f().gen_qemu_st_i64(src, addr, idx, memop);
        true
    }

    /// `fsgnj.s`, `fsgnjn.s` and `fsgnjx.s`, the operands checked to be NaN boxed. The
    /// result keeps the NaN boxing of an operand.
    pub(super) fn fp_sgnj_s(&mut self, rd: i32, rs1: i32, rs2: i32, op: Sgnj) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src1 = self.fpr(rs1);
        let dest = self.new64();
        if op == Sgnj::Copy && rs1 == rs2 {
            // fmv.s
            self.gen_check_nanbox_s(dest, src1);
        } else {
            let r1 = self.new64();
            self.gen_check_nanbox_s(r1, src1);
            if rs1 == rs2 {
                if op == Sgnj::Neg {
                    // fneg.s
                    self.f().gen_xori_i64(dest, r1, SIGN_S);
                } else {
                    // fabs.s
                    self.f().gen_andi_i64(dest, r1, !SIGN_S);
                }
            } else {
                let src2 = self.fpr(rs2);
                let r2 = self.new64();
                self.gen_check_nanbox_s(r2, src2);
                match op {
                    // Keeps the NaN boxing of rs2.
                    Sgnj::Copy => self.f().gen_deposit_i64(dest, r2, r1, 0, 31),
                    Sgnj::Neg => {
                        // Replace bit 31 of rs1 with the inverse of that of rs2.
                        let mask = self.c64(!SIGN_S);
                        let f = self.f();
                        f.gen_nor_i64(r2, r2, mask);
                        f.gen_and_i64(dest, mask, r1);
                        f.gen_or_i64(dest, dest, r2);
                    }
                    Sgnj::Xor => {
                        let f = self.f();
                        f.gen_andi_i64(dest, r2, SIGN_S);
                        f.gen_xor_i64(dest, r1, dest);
                    }
                }
            }
        }
        self.set_fpr(rd, dest);
        self.mark_fs_dirty();
        true
    }

    /// `fsgnj.d`, `fsgnjn.d` and `fsgnjx.d`.
    pub(super) fn fp_sgnj_d(&mut self, rd: i32, rs1: i32, rs2: i32, op: Sgnj) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src1 = self.fpr(rs1);
        let dest = self.new64();
        if rs1 == rs2 {
            let f = self.f();
            match op {
                // fmv.d
                Sgnj::Copy => f.gen_mov_i64(dest, src1),
                // fneg.d
                Sgnj::Neg => f.gen_xori_i64(dest, src1, i64::MIN),
                // fabs.d
                Sgnj::Xor => f.gen_andi_i64(dest, src1, !i64::MIN),
            }
        } else {
            let src2 = self.fpr(rs2);
            let t0 = self.new64();
            let f = self.f();
            match op {
                Sgnj::Copy => f.gen_deposit_i64(dest, src2, src1, 0, 63),
                Sgnj::Neg => {
                    f.gen_not_i64(t0, src2);
                    f.gen_deposit_i64(dest, t0, src1, 0, 63);
                }
                Sgnj::Xor => {
                    f.gen_andi_i64(t0, src2, i64::MIN);
                    f.gen_xor_i64(dest, src1, t0);
                }
            }
        }
        self.set_fpr(rd, dest);
        self.mark_fs_dirty();
        true
    }

    /// `fmv.x.w`: the low 32 bits, sign extended.
    pub(super) fn fp_fmv_x_w(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.fpr(rs1);
        let dest = self.new64();
        self.f().gen_ext32s_i64(dest, src);
        self.set_gpr(rd, dest);
        true
    }

    /// `fmv.w.x`: the low 32 bits, NaN boxed.
    pub(super) fn fp_fmv_w_x(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.gpr(rs1);
        let dest = self.new64();
        self.gen_nanbox_s(dest, src);
        self.set_fpr(rd, dest);
        self.mark_fs_dirty();
        true
    }

    /// `fmv.x.d`.
    pub(super) fn fp_fmv_x_d(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.fpr(rs1);
        self.set_gpr(rd, src);
        true
    }

    /// `fmv.d.x`.
    pub(super) fn fp_fmv_d_x(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() {
            return false;
        }
        let src = self.gpr(rs1);
        self.set_fpr(rd, src);
        self.mark_fs_dirty();
        true
    }

    /// `fli.s` and `fli.d`: the constant `rs1` of the table.
    pub(super) fn fp_fli(&mut self, rd: i32, rs1: i32, double: bool) -> bool {
        if self.fpu_off() {
            return false;
        }
        let table = if double { &FLI_D } else { &FLI_S };
        let dest = self.fpr(rd);
        self.f().gen_movi_i64(dest, table[rs1 as usize] as i64);
        self.mark_fs_dirty();
        true
    }
}

// Zfhmin and Zfbfmin.
impl S<'_, '_> {
    /// `REQUIRE_ZFHMIN_OR_ZFBFMIN`.
    fn zfhmin_or_zfbfmin(&self) -> bool {
        self.d.cfg.ext_zfhmin || self.d.cfg.ext_zfbfmin
    }

    /// `flh`: load 2 bytes and NaN box them.
    pub(super) fn fp_load_h(&mut self, a: &arg_i) -> bool {
        if self.fpu_off() || !self.zfhmin_or_zfbfmin() {
            return false;
        }
        self.decode_save_opc(0);
        let addr = self.address(a.rs1, i64::from(a.imm));
        let dest = self.fpr(a.rd);
        let idx = self.d.mem_idx;
        self.f().gen_qemu_ld_i64(dest, addr, idx, MemOp::LEUW);
        self.f().gen_ori_i64(dest, dest, NANBOX_H as i64);
        self.mark_fs_dirty();
        true
    }

    /// `fsh`.
    pub(super) fn fp_store_h(&mut self, a: &arg_s) -> bool {
        if self.fpu_off() || !self.zfhmin_or_zfbfmin() {
            return false;
        }
        self.decode_save_opc(0);
        let addr = self.address(a.rs1, i64::from(a.imm));
        let src = self.fpr(a.rs2);
        let idx = self.d.mem_idx;
        self.f().gen_qemu_st_i64(src, addr, idx, MemOp::LEUW);
        true
    }

    /// `fmv.x.h`: the low 16 bits, sign extended.
    pub(super) fn fp_fmv_x_h(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() || !self.zfhmin_or_zfbfmin() {
            return false;
        }
        let src = self.fpr(rs1);
        let dest = self.new64();
        self.f().gen_ext16s_i64(dest, src);
        self.set_gpr(rd, dest);
        true
    }

    /// `fmv.h.x`: the low 16 bits, NaN boxed.
    pub(super) fn fp_fmv_h_x(&mut self, rd: i32, rs1: i32) -> bool {
        if self.fpu_off() || !self.zfhmin_or_zfbfmin() {
            return false;
        }
        let src = self.gpr(rs1);
        let dest = self.new64();
        self.f().gen_ori_i64(dest, src, NANBOX_H as i64);
        self.set_fpr(rd, dest);
        self.mark_fs_dirty();
        true
    }

    /// The conversions of Zfhmin (`bf16` false) and Zfbfmin (`bf16` true) with helper `h`.
    pub(super) fn fp_fcvt_h(&mut self, rd: i32, rs1: i32, rm: i32, bf16: bool, h: &Def) -> bool {
        let ext = if bf16 { self.d.cfg.ext_zfbfmin } else { self.d.cfg.ext_zfhmin };
        if self.fpu_off() || !ext {
            return false;
        }
        self.fp_ff(rd, [rs1], Some(rm), h)
    }
}

/// The floating point `trans_*` methods of `DecodeInsn32`.
macro_rules! fp_trans32 {
    () => {
        // F.

        fn trans_flw(&mut self, a: &mut arg_flw) -> bool {
            self.fp_load(a, false)
        }

        fn trans_fsw(&mut self, a: &mut arg_fsw) -> bool {
            self.fp_store(a, false)
        }

        fn trans_fmadd_s(&mut self, a: &mut arg_fmadd_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FMADD_S)
        }

        fn trans_fmsub_s(&mut self, a: &mut arg_fmsub_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FMSUB_S)
        }

        fn trans_fnmsub_s(&mut self, a: &mut arg_fnmsub_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FNMSUB_S)
        }

        fn trans_fnmadd_s(&mut self, a: &mut arg_fnmadd_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FNMADD_S)
        }

        fn trans_fadd_s(&mut self, a: &mut arg_fadd_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FADD_S)
        }

        fn trans_fsub_s(&mut self, a: &mut arg_fsub_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FSUB_S)
        }

        fn trans_fmul_s(&mut self, a: &mut arg_fmul_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FMUL_S)
        }

        fn trans_fdiv_s(&mut self, a: &mut arg_fdiv_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FDIV_S)
        }

        fn trans_fsqrt_s(&mut self, a: &mut arg_fsqrt_s) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FSQRT_S)
        }

        fn trans_fsgnj_s(&mut self, a: &mut arg_fsgnj_s) -> bool {
            self.fp_sgnj_s(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Copy)
        }

        fn trans_fsgnjn_s(&mut self, a: &mut arg_fsgnjn_s) -> bool {
            self.fp_sgnj_s(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Neg)
        }

        fn trans_fsgnjx_s(&mut self, a: &mut arg_fsgnjx_s) -> bool {
            self.fp_sgnj_s(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Xor)
        }

        fn trans_fmin_s(&mut self, a: &mut arg_fmin_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMIN_S)
        }

        fn trans_fmax_s(&mut self, a: &mut arg_fmax_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMAX_S)
        }

        fn trans_fcvt_w_s(&mut self, a: &mut arg_fcvt_w_s) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_W_S)
        }

        fn trans_fcvt_wu_s(&mut self, a: &mut arg_fcvt_wu_s) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_WU_S)
        }

        fn trans_fmv_x_w(&mut self, a: &mut arg_fmv_x_w) -> bool {
            self.fp_fmv_x_w(a.rd, a.rs1)
        }

        fn trans_feq_s(&mut self, a: &mut arg_feq_s) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FEQ_S)
        }

        fn trans_flt_s(&mut self, a: &mut arg_flt_s) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLT_S)
        }

        fn trans_fle_s(&mut self, a: &mut arg_fle_s) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLE_S)
        }

        fn trans_fclass_s(&mut self, a: &mut arg_fclass_s) -> bool {
            self.fp_xf(a.rd, [a.rs1], None, &$crate::tcg::fpu::FCLASS_S)
        }

        fn trans_fcvt_s_w(&mut self, a: &mut arg_fcvt_s_w) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_S_W)
        }

        fn trans_fcvt_s_wu(&mut self, a: &mut arg_fcvt_s_wu) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_S_WU)
        }

        fn trans_fmv_w_x(&mut self, a: &mut arg_fmv_w_x) -> bool {
            self.fp_fmv_w_x(a.rd, a.rs1)
        }

        fn trans_fcvt_l_s(&mut self, a: &mut arg_fcvt_l_s) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_L_S)
        }

        fn trans_fcvt_lu_s(&mut self, a: &mut arg_fcvt_lu_s) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_LU_S)
        }

        fn trans_fcvt_s_l(&mut self, a: &mut arg_fcvt_s_l) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_S_L)
        }

        fn trans_fcvt_s_lu(&mut self, a: &mut arg_fcvt_s_lu) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_S_LU)
        }

        // D.

        fn trans_fld(&mut self, a: &mut arg_fld) -> bool {
            self.fp_load(a, true)
        }

        fn trans_fsd(&mut self, a: &mut arg_fsd) -> bool {
            self.fp_store(a, true)
        }

        fn trans_fmadd_d(&mut self, a: &mut arg_fmadd_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FMADD_D)
        }

        fn trans_fmsub_d(&mut self, a: &mut arg_fmsub_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FMSUB_D)
        }

        fn trans_fnmsub_d(&mut self, a: &mut arg_fnmsub_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FNMSUB_D)
        }

        fn trans_fnmadd_d(&mut self, a: &mut arg_fnmadd_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2, a.rs3], Some(a.rm), &$crate::tcg::fpu::FNMADD_D)
        }

        fn trans_fadd_d(&mut self, a: &mut arg_fadd_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FADD_D)
        }

        fn trans_fsub_d(&mut self, a: &mut arg_fsub_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FSUB_D)
        }

        fn trans_fmul_d(&mut self, a: &mut arg_fmul_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FMUL_D)
        }

        fn trans_fdiv_d(&mut self, a: &mut arg_fdiv_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], Some(a.rm), &$crate::tcg::fpu::FDIV_D)
        }

        fn trans_fsqrt_d(&mut self, a: &mut arg_fsqrt_d) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FSQRT_D)
        }

        fn trans_fsgnj_d(&mut self, a: &mut arg_fsgnj_d) -> bool {
            self.fp_sgnj_d(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Copy)
        }

        fn trans_fsgnjn_d(&mut self, a: &mut arg_fsgnjn_d) -> bool {
            self.fp_sgnj_d(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Neg)
        }

        fn trans_fsgnjx_d(&mut self, a: &mut arg_fsgnjx_d) -> bool {
            self.fp_sgnj_d(a.rd, a.rs1, a.rs2, $crate::tcg::translate_fp::Sgnj::Xor)
        }

        fn trans_fmin_d(&mut self, a: &mut arg_fmin_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMIN_D)
        }

        fn trans_fmax_d(&mut self, a: &mut arg_fmax_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMAX_D)
        }

        fn trans_fcvt_s_d(&mut self, a: &mut arg_fcvt_s_d) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_S_D)
        }

        fn trans_fcvt_d_s(&mut self, a: &mut arg_fcvt_d_s) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_D_S)
        }

        fn trans_feq_d(&mut self, a: &mut arg_feq_d) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FEQ_D)
        }

        fn trans_flt_d(&mut self, a: &mut arg_flt_d) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLT_D)
        }

        fn trans_fle_d(&mut self, a: &mut arg_fle_d) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLE_D)
        }

        fn trans_fclass_d(&mut self, a: &mut arg_fclass_d) -> bool {
            self.fp_fclass_d(a.rd, a.rs1)
        }

        fn trans_fcvt_w_d(&mut self, a: &mut arg_fcvt_w_d) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_W_D)
        }

        fn trans_fcvt_wu_d(&mut self, a: &mut arg_fcvt_wu_d) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_WU_D)
        }

        fn trans_fcvt_d_w(&mut self, a: &mut arg_fcvt_d_w) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_D_W)
        }

        fn trans_fcvt_d_wu(&mut self, a: &mut arg_fcvt_d_wu) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_D_WU)
        }

        fn trans_fcvt_l_d(&mut self, a: &mut arg_fcvt_l_d) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_L_D)
        }

        fn trans_fcvt_lu_d(&mut self, a: &mut arg_fcvt_lu_d) -> bool {
            self.fp_xf(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FCVT_LU_D)
        }

        fn trans_fmv_x_d(&mut self, a: &mut arg_fmv_x_d) -> bool {
            self.fp_fmv_x_d(a.rd, a.rs1)
        }

        fn trans_fcvt_d_l(&mut self, a: &mut arg_fcvt_d_l) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_D_L)
        }

        fn trans_fcvt_d_lu(&mut self, a: &mut arg_fcvt_d_lu) -> bool {
            self.fp_fx(a.rd, a.rs1, a.rm, &$crate::tcg::fpu::FCVT_D_LU)
        }

        fn trans_fmv_d_x(&mut self, a: &mut arg_fmv_d_x) -> bool {
            self.fp_fmv_d_x(a.rd, a.rs1)
        }

        // Zfa.

        fn trans_fli_s(&mut self, a: &mut arg_fli_s) -> bool {
            self.fp_fli(a.rd, a.rs1, false)
        }

        fn trans_fli_d(&mut self, a: &mut arg_fli_d) -> bool {
            self.fp_fli(a.rd, a.rs1, true)
        }

        fn trans_fminm_s(&mut self, a: &mut arg_fminm_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMINM_S)
        }

        fn trans_fmaxm_s(&mut self, a: &mut arg_fmaxm_s) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMAXM_S)
        }

        fn trans_fminm_d(&mut self, a: &mut arg_fminm_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMINM_D)
        }

        fn trans_fmaxm_d(&mut self, a: &mut arg_fmaxm_d) -> bool {
            self.fp_ff(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FMAXM_D)
        }

        fn trans_fround_s(&mut self, a: &mut arg_fround_s) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FROUND_S)
        }

        fn trans_froundnx_s(&mut self, a: &mut arg_froundnx_s) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FROUNDNX_S)
        }

        fn trans_fround_d(&mut self, a: &mut arg_fround_d) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FROUND_D)
        }

        fn trans_froundnx_d(&mut self, a: &mut arg_froundnx_d) -> bool {
            self.fp_ff(a.rd, [a.rs1], Some(a.rm), &$crate::tcg::fpu::FROUNDNX_D)
        }

        fn trans_fcvtmod_w_d(&mut self, a: &mut arg_fcvtmod_w_d) -> bool {
            self.fp_fcvtmod_w_d(a.rd, a.rs1)
        }

        fn trans_fleq_s(&mut self, a: &mut arg_fleq_s) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLEQ_S)
        }

        fn trans_fltq_s(&mut self, a: &mut arg_fltq_s) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLTQ_S)
        }

        fn trans_fleq_d(&mut self, a: &mut arg_fleq_d) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLEQ_D)
        }

        fn trans_fltq_d(&mut self, a: &mut arg_fltq_d) -> bool {
            self.fp_xf(a.rd, [a.rs1, a.rs2], None, &$crate::tcg::fpu::FLTQ_D)
        }

        // Zfhmin and Zfbfmin.

        fn trans_flh(&mut self, a: &mut arg_flh) -> bool {
            self.fp_load_h(a)
        }

        fn trans_fsh(&mut self, a: &mut arg_fsh) -> bool {
            self.fp_store_h(a)
        }

        fn trans_fmv_x_h(&mut self, a: &mut arg_fmv_x_h) -> bool {
            self.fp_fmv_x_h(a.rd, a.rs1)
        }

        fn trans_fmv_h_x(&mut self, a: &mut arg_fmv_h_x) -> bool {
            self.fp_fmv_h_x(a.rd, a.rs1)
        }

        fn trans_fcvt_s_h(&mut self, a: &mut arg_fcvt_s_h) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, false, &$crate::tcg::fpu::FCVT_S_H)
        }

        fn trans_fcvt_h_s(&mut self, a: &mut arg_fcvt_h_s) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, false, &$crate::tcg::fpu::FCVT_H_S)
        }

        fn trans_fcvt_d_h(&mut self, a: &mut arg_fcvt_d_h) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, false, &$crate::tcg::fpu::FCVT_D_H)
        }

        fn trans_fcvt_h_d(&mut self, a: &mut arg_fcvt_h_d) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, false, &$crate::tcg::fpu::FCVT_H_D)
        }

        fn trans_fcvt_bf16_s(&mut self, a: &mut arg_fcvt_bf16_s) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, true, &$crate::tcg::fpu::FCVT_BF16_S)
        }

        fn trans_fcvt_s_bf16(&mut self, a: &mut arg_fcvt_s_bf16) -> bool {
            self.fp_fcvt_h(a.rd, a.rs1, a.rm, true, &$crate::tcg::fpu::FCVT_S_BF16)
        }
    };
}
pub(super) use fp_trans32;

/// The floating point `trans_*` methods of `DecodeInsn16`.
macro_rules! fp_trans16 {
    () => {
        fn trans_c_fld(&mut self, a: &mut $crate::decode::insn16::arg_c_fld) -> bool {
            self.fp_load(a, true)
        }

        fn trans_c_fsd(&mut self, a: &mut $crate::decode::insn16::arg_c_fsd) -> bool {
            self.fp_store(a, true)
        }
    };
}
pub(super) use fp_trans16;

#[cfg(test)]
mod tests {
    use super::*;
    use ruvm_softfloat::{Float32, Float64, FloatStatus};

    #[test]
    fn fli_tables() {
        let mut st = FloatStatus::default();
        for i in 0..32 {
            let s = FLI_S[i];
            let d = FLI_D[i];
            assert_eq!(s >> 32, 0xffff_ffff, "fli.s {i} is NaN boxed");
            let s = Float32(s as u32);
            let d = Float64(d);
            if i == 31 {
                assert!(s.is_any_nan() && d.is_any_nan());
                assert_eq!(s.0, 0x7fc0_0000);
                assert_eq!(d.0, 0x7ff8_0000_0000_0000);
                continue;
            }
            if i == 1 {
                // The minimum positive normal of each format, checked below.
                continue;
            }
            // Every other entry is exact in single precision and the same value in both
            // tables.
            assert_eq!(s.to_float64(&mut st), d, "entry {i}");
        }
        assert_eq!(st.flags(), 0);
        assert_eq!(FLI_D[0], (-1.0f64).to_bits());
        assert_eq!(FLI_D[1], f64::MIN_POSITIVE.to_bits());
        assert_eq!(FLI_S[1] as u32, f32::MIN_POSITIVE.to_bits());
        assert_eq!(FLI_D[2], 2f64.powi(-16).to_bits());
        assert_eq!(FLI_D[9], 0.3125f64.to_bits());
        assert_eq!(FLI_D[21], 2.5f64.to_bits());
        assert_eq!(FLI_D[29], 65536f64.to_bits());
        assert_eq!(FLI_D[30], f64::INFINITY.to_bits());
        assert_eq!(FLI_S[30] as u32, f32::INFINITY.to_bits());
        // Strictly increasing from entry 2 to +inf.
        for i in 2..30 {
            assert!(f64::from_bits(FLI_D[i]) < f64::from_bits(FLI_D[i + 1]), "entry {i}");
        }
    }

    #[test]
    fn nanbox_constants() {
        assert_eq!(NANBOXED_NAN_S, NANBOX_S | 0x7fc0_0000);
        assert_eq!(FLI_S[31], NANBOXED_NAN_S);
        assert_eq!(SIGN_S, 0x8000_0000);
    }
}
