// SPDX-License-Identifier: GPL-2.0-or-later

//! The hypervisor instructions, a port of QEMU's `trans_rvh.c.inc`: the HLV, HLVX and HSV
//! loads and stores and `hfence.vvma` and `hfence.gvma`. Every one of them calls a helper
//! in `helpers`, which checks the privilege level (`check_access_hlsv()`) and picks the
//! two stage MMU index. The signed HLV loads are the zero extending helper followed by a
//! sign extension, as in QEMU.
//!
//! The `trans_*` methods are generated by [`rvh_trans32`] inside the decoder trait impl
//! of `translate.rs`; each one is a single call into this file.

use ruvm_jit_core::Func;
use ruvm_jit_core::ir::TempI64;

use super::helpers::{self, Def};
use super::translate::S;

impl S<'_, '_> {
    /// `do_hlv()`: `rd = helper(rs1)`, then `ext` on the result.
    pub(super) fn hlv(
        &mut self,
        rd: i32,
        rs1: i32,
        d: &Def,
        ext: Option<fn(&mut Func, TempI64, TempI64)>,
    ) -> bool {
        if !self.d.cfg.ext_h() {
            return false;
        }
        let addr = self.gpr(rs1);
        let dest = self.new64();
        self.decode_save_opc(0);
        let env = self.env();
        self.call(d, Some(dest.into()), &[env.into(), addr.into()]);
        if let Some(ext) = ext {
            ext(self.f(), dest, dest);
        }
        self.set_gpr(rd, dest);
        true
    }

    /// `do_hsv()`: `helper(rs1, rs2)`.
    pub(super) fn hsv(&mut self, rs1: i32, rs2: i32, d: &Def) -> bool {
        if !self.d.cfg.ext_h() {
            return false;
        }
        let addr = self.gpr(rs1);
        let data = self.gpr(rs2);
        self.decode_save_opc(0);
        let env = self.env();
        self.call(d, None, &[env.into(), addr.into(), data.into()]);
        true
    }

    /// `trans_hfence_gvma()` and `trans_hfence_vvma()`.
    pub(super) fn hfence(&mut self, gvma: bool) -> bool {
        if !self.d.cfg.ext_h() {
            return false;
        }
        self.decode_save_opc(0);
        let env = self.env();
        let d = if gvma { &helpers::HYP_GVMA_TLB_FLUSH } else { &helpers::HYP_TLB_FLUSH };
        self.call(d, None, &[env.into()]);
        true
    }
}

/// The hypervisor `trans_*` methods of `DecodeInsn32`.
macro_rules! rvh_trans32 {
    () => {
        fn trans_hlv_b(&mut self, a: &mut arg_hlv_b) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_BU, Some(Func::gen_ext8s_i64))
        }

        fn trans_hlv_bu(&mut self, a: &mut arg_hlv_bu) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_BU, None)
        }

        fn trans_hlv_h(&mut self, a: &mut arg_hlv_h) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_HU, Some(Func::gen_ext16s_i64))
        }

        fn trans_hlv_hu(&mut self, a: &mut arg_hlv_hu) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_HU, None)
        }

        fn trans_hlv_w(&mut self, a: &mut arg_hlv_w) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_WU, Some(Func::gen_ext32s_i64))
        }

        fn trans_hlv_wu(&mut self, a: &mut arg_hlv_wu) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_WU, None)
        }

        fn trans_hlv_d(&mut self, a: &mut arg_hlv_d) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLV_D, None)
        }

        fn trans_hlvx_hu(&mut self, a: &mut arg_hlvx_hu) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLVX_HU, None)
        }

        fn trans_hlvx_wu(&mut self, a: &mut arg_hlvx_wu) -> bool {
            self.hlv(a.rd, a.rs1, &helpers::HYP_HLVX_WU, None)
        }

        fn trans_hsv_b(&mut self, a: &mut arg_hsv_b) -> bool {
            self.hsv(a.rs1, a.rs2, &helpers::HYP_HSV_B)
        }

        fn trans_hsv_h(&mut self, a: &mut arg_hsv_h) -> bool {
            self.hsv(a.rs1, a.rs2, &helpers::HYP_HSV_H)
        }

        fn trans_hsv_w(&mut self, a: &mut arg_hsv_w) -> bool {
            self.hsv(a.rs1, a.rs2, &helpers::HYP_HSV_W)
        }

        fn trans_hsv_d(&mut self, a: &mut arg_hsv_d) -> bool {
            self.hsv(a.rs1, a.rs2, &helpers::HYP_HSV_D)
        }

        fn trans_hfence_gvma(&mut self, _a: &mut arg_hfence_gvma) -> bool {
            self.hfence(true)
        }

        fn trans_hfence_vvma(&mut self, _a: &mut arg_hfence_vvma) -> bool {
            self.hfence(false)
        }
    };
}
pub(super) use rvh_trans32;
