// SPDX-License-Identifier: GPL-2.0-or-later

//! The vector configuration, load and store instructions and the checks every vector
//! instruction uses, a port of the first part of QEMU's `trans_rvv.c.inc`.
//!
//! The `trans_*` methods are generated by [`rvv_trans32`] inside the decoder trait impl of
//! `translate.rs`; each one is a single call into this file or into the files of the other
//! vector instructions.
//!
//! Deliberate differences from QEMU:
//!
//! - QEMU calls a helper per element size, `vle8_v` to `vle64_v`. Here a helper serves
//!   every element size, which is in the descriptor ([`Desc`]).
//! - The `-cpu` model has no Ztso, so there are no barriers around the vector loads and
//!   stores (QEMU only emits them with Ztso).
//! - The vector registers are little endian in `env` on every host, so the inline whole
//!   register loads and stores swap the bytes of each 64-bit chunk on a big endian host.

use ruvm_jit_core::ir::TempI64;
use ruvm_jit_core::types::mo;
use ruvm_jit_core::{MemOp, Temp};

use super::helpers::Def;
use super::translate::S;
use super::vector::{self, Desc, RV_VLEN_MAX, voff};
use crate::cpu::{EXT_STATUS_DISABLED, VL, VSTART};

/// `is_overlapped()`.
pub(super) fn is_overlapped(astart: i32, asize: i32, bstart: i32, bsize: i32) -> bool {
    let aend = astart + asize;
    let bend = bstart + bsize;
    aend.max(bend) - astart.min(bstart) < asize + bsize
}

/// `require_vm()`.
pub(super) fn require_vm(vm: i32, v: i32) -> bool {
    vm != 0 || v != 0
}

/// `require_nf()`.
pub(super) fn require_nf(vd: i32, nf: i32, lmul: i32) -> bool {
    let size = nf << lmul.max(0);
    size <= 8 && vd + size <= 32
}

/// `require_align()`: register `val` is a multiple of the group size `1 << lmul`.
pub(super) fn require_align(val: i32, lmul: i32) -> bool {
    lmul <= 0 || val & ((1 << lmul) - 1) == 0
}

/// `require_noover()`: the destination group does not overlap the source group, or
/// overlaps it as rule 3 of section 5.2 allows.
pub(super) fn require_noover(dst: i32, dst_lmul: i32, src: i32, src_lmul: i32) -> bool {
    let dst_size = if dst_lmul <= 0 { 1 } else { 1 << dst_lmul };
    let src_size = if src_lmul <= 0 { 1 } else { 1 << src_lmul };
    // Destination EEW is greater than the source EEW, check rule 3.
    if dst_size > src_size
        && dst < src
        && src_lmul >= 0
        && is_overlapped(dst, dst_size, src, src_size)
        && !is_overlapped(dst, dst_size, src + src_size, src_size)
    {
        return true;
    }
    !is_overlapped(dst, dst_size, src, src_size)
}

// The checks of the instruction context.
impl S<'_, '_> {
    /// `require_rvv()`.
    pub(super) fn require_rvv(&self) -> bool {
        self.d.mstatus_vs != EXT_STATUS_DISABLED
    }

    /// `require_rvf()`. Without Zvfbfa `altfmt` is never set.
    pub(super) fn require_rvf(&self) -> bool {
        if self.d.mstatus_fs == EXT_STATUS_DISABLED {
            return false;
        }
        match self.d.sew {
            1 => self.d.cfg.ext_zvfh,
            2 => self.d.cfg.ext_zve32f,
            3 => self.d.cfg.ext_zve64d,
            _ => false,
        }
    }

    /// `require_rvfmin()`.
    pub(super) fn require_rvfmin(&self) -> bool {
        if self.d.mstatus_fs == EXT_STATUS_DISABLED {
            return false;
        }
        match self.d.sew {
            1 => self.d.cfg.ext_zvfhmin,
            2 => self.d.cfg.ext_zve32f,
            _ => false,
        }
    }

    /// `require_scale_rvf()`.
    pub(super) fn require_scale_rvf(&self) -> bool {
        if self.d.mstatus_fs == EXT_STATUS_DISABLED {
            return false;
        }
        match self.d.sew {
            0 => self.d.cfg.ext_zvfh,
            1 => self.d.cfg.ext_zve32f,
            2 => self.d.cfg.ext_zve64d,
            _ => false,
        }
    }

    /// `require_scale_rvfmin()`.
    pub(super) fn require_scale_rvfmin(&self) -> bool {
        if self.d.mstatus_fs == EXT_STATUS_DISABLED {
            return false;
        }
        match self.d.sew {
            1 => self.d.cfg.ext_zve32f,
            2 => self.d.cfg.ext_zve64d,
            _ => false,
        }
    }

    /// `vext_check_isa_ill()`.
    pub(super) fn vext_check_isa_ill(&self) -> bool {
        !self.d.vill
    }

    /// `vext_check_store()`.
    pub(super) fn vext_check_store(&self, vd: i32, nf: i32, eew: i32) -> bool {
        let emul = eew - self.d.sew + self.d.lmul;
        (-3..=3).contains(&emul) && require_align(vd, emul) && require_nf(vd, nf, emul)
    }

    /// `vext_check_load()`.
    pub(super) fn vext_check_load(&self, vd: i32, nf: i32, vm: i32, eew: i32) -> bool {
        self.vext_check_store(vd, nf, eew) && require_vm(vm, vd)
    }

    /// `vext_check_st_index()` on RV64.
    pub(super) fn vext_check_st_index(&self, vd: i32, vs2: i32, nf: i32, eew: i32) -> bool {
        let emul = eew - self.d.sew + self.d.lmul;
        (-3..=3).contains(&emul)
            && require_align(vs2, emul)
            && require_align(vd, self.d.lmul)
            && require_nf(vd, nf, self.d.lmul)
    }

    /// `vext_check_ld_index()`.
    pub(super) fn vext_check_ld_index(
        &self,
        vd: i32,
        vs2: i32,
        nf: i32,
        vm: i32,
        eew: i32,
    ) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        let emul = eew - sew + lmul;
        let mut ret = self.vext_check_st_index(vd, vs2, nf, eew) && require_vm(vm, vd);
        // Each segment register group has to follow the overlap rules.
        for i in 0..nf {
            let seg_vd = vd + (1 << lmul.max(0)) * i;
            if eew > sew {
                if seg_vd != vs2 {
                    ret &= require_noover(seg_vd, lmul, vs2, emul);
                }
            } else if eew < sew {
                ret &= require_noover(seg_vd, lmul, vs2, emul);
            }
            // The destination groups of an indexed segment load cannot overlap the
            // index group.
            if nf > 1 {
                ret &= !is_overlapped(seg_vd, 1 << lmul.max(0), vs2, 1 << emul.max(0));
            }
        }
        ret
    }

    /// `vext_check_input_eew()`: `-1` for a register stands for none.
    pub(super) fn vext_check_input_eew(
        &self,
        vs1: i32,
        eew_vs1: i32,
        vs2: i32,
        eew_vs2: i32,
        vm: i32,
    ) -> bool {
        let emul_vs1 = eew_vs1 - self.d.sew + self.d.lmul;
        let emul_vs2 = eew_vs2 - self.d.sew + self.d.lmul;
        let mut valid = true;
        // When vm is 0, the vs1 and vs2 groups (EEW != 1) cannot overlap v0 (EEW 1).
        if (vs1 != -1 && !require_vm(vm, vs1)) || (vs2 != -1 && !require_vm(vm, vs2)) {
            valid = false;
        }
        // When the EEWs differ, vs1 and vs2 cannot overlap.
        if vs1 != -1
            && vs2 != -1
            && eew_vs1 != eew_vs2
            && is_overlapped(vs1, 1 << emul_vs1.max(0), vs2, 1 << emul_vs2.max(0))
        {
            valid = false;
        }
        valid
    }

    /// `vext_check_ss()`.
    pub(super) fn vext_check_ss(&self, vd: i32, vs: i32, vm: i32) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        require_vm(vm, vd)
            && require_align(vd, lmul)
            && require_align(vs, lmul)
            && self.vext_check_input_eew(vs, sew, -1, sew, vm)
    }

    /// `vext_check_sss()`.
    pub(super) fn vext_check_sss(&self, vd: i32, vs1: i32, vs2: i32, vm: i32) -> bool {
        let sew = self.d.sew;
        self.vext_check_ss(vd, vs2, vm)
            && self.vext_check_input_eew(vs1, sew, vs2, sew, vm)
            && require_align(vs1, self.d.lmul)
    }

    /// `vext_check_ms()`.
    pub(super) fn vext_check_ms(&self, vd: i32, vs: i32) -> bool {
        let mut ret = require_align(vs, self.d.lmul);
        if vd != vs {
            ret &= require_noover(vd, 0, vs, self.d.lmul);
        }
        ret
    }

    /// `vext_check_mss()`.
    pub(super) fn vext_check_mss(&self, vd: i32, vs1: i32, vs2: i32) -> bool {
        let mut ret = self.vext_check_ms(vd, vs2) && require_align(vs1, self.d.lmul);
        if vd != vs1 {
            ret &= require_noover(vd, 0, vs1, self.d.lmul);
        }
        ret
    }

    /// `vext_wide_check_common()`.
    pub(super) fn vext_wide_check_common(&self, vd: i32, vm: i32) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        lmul <= 2
            && sew < 3
            && sew < (self.d.cfg.elen >> 4) as i32
            && require_align(vd, lmul + 1)
            && require_vm(vm, vd)
    }

    /// `vext_narrow_check_common()`.
    pub(super) fn vext_narrow_check_common(&self, vd: i32, vs2: i32, vm: i32) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        lmul <= 2
            && sew < 3
            && sew < (self.d.cfg.elen >> 4) as i32
            && require_align(vs2, lmul + 1)
            && require_align(vd, lmul)
            && require_vm(vm, vd)
    }

    /// `vext_check_ds()`.
    pub(super) fn vext_check_ds(&self, vd: i32, vs: i32, vm: i32) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        self.vext_wide_check_common(vd, vm)
            && self.vext_check_input_eew(vs, sew, -1, 0, vm)
            && require_align(vs, lmul)
            && require_noover(vd, lmul + 1, vs, lmul)
    }

    /// `vext_check_dd()`.
    pub(super) fn vext_check_dd(&self, vd: i32, vs: i32, vm: i32) -> bool {
        self.vext_wide_check_common(vd, vm)
            && self.vext_check_input_eew(vs, self.d.sew + 1, -1, 0, vm)
            && require_align(vs, self.d.lmul + 1)
    }

    /// `vext_check_dss()`.
    pub(super) fn vext_check_dss(&self, vd: i32, vs1: i32, vs2: i32, vm: i32) -> bool {
        let (sew, lmul) = (self.d.sew, self.d.lmul);
        self.vext_check_ds(vd, vs2, vm)
            && self.vext_check_input_eew(vs1, sew, vs2, sew, vm)
            && require_align(vs1, lmul)
            && require_noover(vd, lmul + 1, vs1, lmul)
    }

    /// `vext_check_dds()`.
    pub(super) fn vext_check_dds(&self, vd: i32, vs1: i32, vs2: i32, vm: i32) -> bool {
        let sew = self.d.sew;
        self.vext_check_ds(vd, vs1, vm)
            && self.vext_check_input_eew(vs1, sew, vs2, sew + 1, vm)
            && require_align(vs2, self.d.lmul + 1)
    }

    /// `vext_check_sd()`.
    pub(super) fn vext_check_sd(&self, vd: i32, vs: i32, vm: i32) -> bool {
        let mut ret = self.vext_narrow_check_common(vd, vs, vm)
            && self.vext_check_input_eew(vs, self.d.sew + 1, -1, 0, vm);
        if vd != vs {
            ret &= require_noover(vd, self.d.lmul, vs, self.d.lmul + 1);
        }
        ret
    }

    /// `vext_check_sds()`.
    pub(super) fn vext_check_sds(&self, vd: i32, vs1: i32, vs2: i32, vm: i32) -> bool {
        let sew = self.d.sew;
        self.vext_check_sd(vd, vs2, vm)
            && self.vext_check_input_eew(vs1, sew, vs2, sew + 1, vm)
            && require_align(vs1, self.d.lmul)
    }

    /// `vext_check_reduction()`.
    pub(super) fn vext_check_reduction(&self, vs2: i32) -> bool {
        require_align(vs2, self.d.lmul) && self.d.vstart_eq_zero
    }

    /// `vext_check_slide()`.
    pub(super) fn vext_check_slide(&self, vd: i32, vs2: i32, vm: i32, is_over: bool) -> bool {
        let lmul = self.d.lmul;
        let mut ret = require_align(vs2, lmul)
            && require_align(vd, lmul)
            && require_vm(vm, vd)
            && self.vext_check_input_eew(-1, 0, vs2, self.d.sew, vm);
        if is_over {
            ret &= vd != vs2;
        }
        ret
    }

    /// `vext_get_emul()`.
    pub(super) fn vext_get_emul(&self, eew: i32) -> i32 {
        (eew - self.d.sew + self.d.lmul).max(0)
    }

    /// The descriptor of an instruction with the `VDATA` of most instructions: `vm`, LMUL,
    /// VTA and VMA from the context, SEW elements.
    pub(super) fn vdesc(&self, vd: i32, vs1: i32, vs2: i32, vm: i32) -> Desc {
        Desc {
            vm: vm != 0,
            lmul: self.d.lmul,
            vta: self.d.vta,
            vta_all_1s: self.d.cfg_vta_all_1s,
            vma: self.d.vma,
            nf: 0,
            vd: vd as u32,
            vs1: vs1 as u32,
            vs2: vs2 as u32,
            esz: self.d.sew as u32,
            scalar: false,
            x: 0,
        }
    }

    /// Call vector helper `h` with `env`, the descriptor and `args`.
    pub(super) fn vcall(&mut self, h: &Def, ret: Option<Temp>, desc: Desc, args: &[Temp]) {
        let env = self.env();
        let d = self.c32(desc.encode() as i32);
        let mut all = vec![env.into(), d.into()];
        all.extend_from_slice(args);
        self.call(h, ret, &all);
    }

    /// `extract_imm()`.
    pub(super) fn extract_imm(&self, imm: i32, mode: ImmMode) -> i64 {
        let imm = i64::from(imm);
        match mode {
            ImmMode::Zx => imm & 0x1f,
            ImmMode::Sx => (imm << 59) >> 59,
            ImmMode::TruncSew => imm & ((1 << (self.d.sew + 3)) - 1),
        }
    }

    /// `opivv_trans()`, `opivx_trans()` and `opivi_trans()`, and the helper paths of the
    /// gvec expansions: call the element-wise helper `h` on `vd`, `vs2` and the first
    /// source `src`, with the `VDATA` of the context.
    pub(super) fn gen_vop(&mut self, h: &Def, a: VArgs, src: VSrc) -> bool {
        let mut desc = self.vdesc(a.rd, a.rs1, a.rs2, a.vm);
        let s1 = match src {
            VSrc::V => self.c64(0),
            VSrc::X => {
                desc.scalar = true;
                self.gpr(a.rs1)
            }
            VSrc::I(mode) => {
                desc.scalar = true;
                let imm = self.extract_imm(a.rs1, mode);
                self.c64(imm)
            }
            VSrc::T(t) => {
                desc.scalar = true;
                t
            }
        };
        self.vcall(h, None, desc, &[s1.into()]);
        self.finalize_rvv_inst();
        true
    }
}

/// `imm_mode_t`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum ImmMode {
    /// `IMM_ZX`.
    Zx,
    /// `IMM_SX`.
    Sx,
    /// `IMM_TRUNC_SEW`.
    TruncSew,
}

/// The first source operand of an element-wise operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum VSrc {
    /// `vs1`.
    V,
    /// `x[rs1]`.
    X,
    /// The immediate in the `rs1` field.
    I(ImmMode),
    /// A value, such as an `f` register.
    T(TempI64),
}

/// The fields of an `arg_rmrr`: `vd`, `rs1` (or `vs1`), `vs2` and `vm`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) struct VArgs {
    pub(super) rd: i32,
    pub(super) rs1: i32,
    pub(super) rs2: i32,
    pub(super) vm: i32,
}

/// The [`VArgs`] of an `arg_rmrr`.
pub(super) fn vargs(a: &crate::decode::insn32::arg_rmrr) -> VArgs {
    VArgs { rd: a.rd, rs1: a.rs1, rs2: a.rs2, vm: a.vm }
}

// The configuration instructions.
impl S<'_, '_> {
    /// `do_vsetvl()`.
    fn do_vsetvl(&mut self, rd: i32, rs1: i32, s2: TempI64) -> bool {
        if !self.require_rvv() || !self.d.cfg.ext_zve32x {
            return false;
        }
        let s1 = if rd == 0 && rs1 == 0 {
            let t = self.new64();
            let env = self.env();
            self.f().gen_ld_i64(t, env, VL as i64);
            t
        } else if rs1 == 0 {
            // As the mask is at least one bit, RV_VLEN_MAX is >= VLMAX.
            self.c64(RV_VLEN_MAX as i64)
        } else {
            self.gpr(rs1)
        };
        let x0 = if rd == 0 && rs1 == 0 { vector::VSETVL_X0 } else { 0 };
        self.gen_vsetvl(rd, s1, s2, x0)
    }

    /// The rest of `do_vsetvl()` and `do_vsetivli()`: `vsetvl` changes the translation
    /// state, so the block ends.
    fn gen_vsetvl(&mut self, rd: i32, s1: TempI64, s2: TempI64, x0: u64) -> bool {
        let flags = self.c64((vector::vsetvl_flags(&self.d.cfg) | x0) as i64);
        let dst = self.new64();
        let env = self.env();
        self.call(
            &vector::VSETVL,
            Some(dst.into()),
            &[env.into(), s1.into(), s2.into(), flags.into()],
        );
        self.set_gpr(rd, dst);
        self.finalize_rvv_inst();
        self.update_pc(self.d.cur_insn_len as i64);
        self.lookup_and_goto_ptr();
        true
    }

    /// `trans_vsetvl()`.
    pub(super) fn vsetvl(&mut self, rd: i32, rs1: i32, rs2: i32) -> bool {
        let s2 = self.gpr(rs2);
        self.do_vsetvl(rd, rs1, s2)
    }

    /// `trans_vsetvli()`.
    pub(super) fn vsetvli(&mut self, rd: i32, rs1: i32, zimm: i32) -> bool {
        let s2 = self.c64(i64::from(zimm));
        self.do_vsetvl(rd, rs1, s2)
    }

    /// `trans_vsetivli()`: `do_vsetivli()`.
    pub(super) fn vsetivli(&mut self, rd: i32, uimm: i32, zimm: i32) -> bool {
        if !self.require_rvv() || !self.d.cfg.ext_zve32x {
            return false;
        }
        let s1 = self.c64(i64::from(uimm));
        let s2 = self.c64(i64::from(zimm));
        self.gen_vsetvl(rd, s1, s2, 0)
    }
}

/// The kinds of unit stride and strided accesses.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Ldst {
    Load,
    Store,
}

// The loads and stores.
impl S<'_, '_> {
    /// The descriptor of a load or store of `eew` elements into or from `vd`.
    fn ldst_desc(&self, vd: i32, vm: i32, nf: i32, emul: i32, eew: i32, kind: Ldst) -> Desc {
        let load = kind == Ldst::Load;
        Desc {
            vm: vm != 0,
            lmul: emul,
            vta: load && self.d.vta,
            vta_all_1s: false,
            vma: load && self.d.vma,
            nf: nf as u32,
            vd: vd as u32,
            vs1: 0,
            vs2: 0,
            esz: eew as u32,
            scalar: false,
            x: 0,
        }
    }

    /// `ldst_us_trans()`, `ldst_stride_trans()` and `ldst_index_trans()`. `tso` is the
    /// direction of a unit-stride access, which with Ztso follows RVTSO at the instruction
    /// level: barriers around the loop, none inside it.
    fn ldst_trans(
        &mut self,
        h: &Def,
        desc: Desc,
        rs1: i32,
        stride: Option<i32>,
        tso: Option<Ldst>,
    ) -> bool {
        let base = self.gpr(rs1);
        let mut args: Vec<Temp> = vec![base.into()];
        if let Some(rs2) = stride {
            args.push(self.gpr(rs2).into());
        }
        let tso = if self.d.cfg.ext_ztso { tso } else { None };
        if tso == Some(Ldst::Store) {
            self.f().gen_mb(mo::ALL | mo::BAR_STRL);
        }
        self.mark_vs_dirty();
        self.vcall(h, None, desc, &args);
        if tso == Some(Ldst::Load) {
            self.f().gen_mb(mo::ALL | mo::BAR_LDAQ);
        }
        self.finalize_rvv_inst();
        true
    }

    /// `ld_us_check()`.
    fn ld_us_check(&self, rd: i32, nf: i32, vm: i32, eew: i32) -> bool {
        self.require_rvv() && self.vext_check_isa_ill() && self.vext_check_load(rd, nf, vm, eew)
    }

    /// `st_us_check()` and `st_stride_check()`.
    fn st_us_check(&self, rd: i32, nf: i32, eew: i32) -> bool {
        self.require_rvv() && self.vext_check_isa_ill() && self.vext_check_store(rd, nf, eew)
    }

    /// `trans_vle*_v()` and `trans_vse*_v()`: `ld_us_op()` and `st_us_op()`.
    pub(super) fn ldst_us(
        &mut self,
        rd: i32,
        rs1: i32,
        nf: i32,
        vm: i32,
        eew: i32,
        k: Ldst,
    ) -> bool {
        let ok = match k {
            Ldst::Load => self.ld_us_check(rd, nf, vm, eew),
            Ldst::Store => self.st_us_check(rd, nf, eew),
        };
        if !ok {
            return false;
        }
        let emul = self.vext_get_emul(eew);
        let desc = self.ldst_desc(rd, vm, nf, emul, eew, k);
        let h = if k == Ldst::Load { &vector::VLE } else { &vector::VSE };
        self.ldst_trans(h, desc, rs1, None, Some(k))
    }

    /// `trans_vlm_v()` and `trans_vsm_v()`.
    pub(super) fn ldst_mask(&mut self, rd: i32, rs1: i32, k: Ldst) -> bool {
        if !self.require_rvv() || !self.vext_check_isa_ill() {
            return false;
        }
        let mut desc = self.ldst_desc(rd, 1, 1, 0, 0, Ldst::Store);
        let h = if k == Ldst::Load {
            // Mask destination registers are always tail agnostic.
            desc.vta = self.d.cfg_vta_all_1s;
            desc.vma = self.d.vma;
            &vector::VLM
        } else {
            &vector::VSM
        };
        self.ldst_trans(h, desc, rs1, None, Some(k))
    }

    /// `trans_vlse*_v()` and `trans_vsse*_v()`.
    pub(super) fn ldst_stride(&mut self, a: (i32, i32, i32, i32, i32), eew: i32, k: Ldst) -> bool {
        let (rd, rs1, rs2, nf, vm) = a;
        let ok = match k {
            Ldst::Load => self.ld_us_check(rd, nf, vm, eew),
            Ldst::Store => self.st_us_check(rd, nf, eew),
        };
        if !ok {
            return false;
        }
        let emul = self.vext_get_emul(eew);
        let desc = self.ldst_desc(rd, vm, nf, emul, eew, k);
        let h = if k == Ldst::Load { &vector::VLSE } else { &vector::VSSE };
        self.ldst_trans(h, desc, rs1, Some(rs2), None)
    }

    /// `trans_vlxei*_v()` and `trans_vsxei*_v()`: `eew` is the index EEW, the data
    /// elements are SEW.
    pub(super) fn ldst_index(&mut self, a: (i32, i32, i32, i32, i32), eew: i32, k: Ldst) -> bool {
        let (rd, rs1, rs2, nf, vm) = a;
        let ok = self.require_rvv()
            && self.vext_check_isa_ill()
            && match k {
                Ldst::Load => {
                    self.vext_check_ld_index(rd, rs2, nf, vm, eew)
                        && self.vext_check_input_eew(-1, 0, rs2, eew, vm)
                }
                Ldst::Store => {
                    self.vext_check_st_index(rd, rs2, nf, eew)
                        && self.vext_check_input_eew(rd, self.d.sew, rs2, eew, vm)
                }
            };
        if !ok {
            return false;
        }
        let emul = self.vext_get_emul(self.d.sew);
        let mut desc = self.ldst_desc(rd, vm, nf, emul, self.d.sew, k);
        desc.vs2 = rs2 as u32;
        desc.x = eew as u32;
        let h = if k == Ldst::Load { &vector::VLXEI } else { &vector::VSXEI };
        self.ldst_trans(h, desc, rs1, None, None)
    }

    /// `trans_vle*ff_v()`: `ldff_op()` and `ldff_trans()`. The load may change `vl`, so
    /// the block ends.
    pub(super) fn ldff(&mut self, rd: i32, rs1: i32, nf: i32, vm: i32, eew: i32) -> bool {
        if !self.ld_us_check(rd, nf, vm, eew) {
            return false;
        }
        let emul = self.vext_get_emul(eew);
        let desc = self.ldst_desc(rd, vm, nf, emul, eew, Ldst::Load);
        let base = self.gpr(rs1);
        self.vcall(&vector::VLEFF, None, desc, &[base.into()]);
        self.finalize_rvv_inst();
        self.update_pc(self.d.cur_insn_len as i64);
        self.lookup_and_goto_ptr();
        true
    }

    /// `trans_vl<nf>re<eew>_v()` and `trans_vs<nf>r_v()`: `ldst_whole_trans()`.
    pub(super) fn ldst_whole(
        &mut self,
        rd: i32,
        rs1: i32,
        nf: i32,
        log2_esz: i32,
        k: Ldst,
    ) -> bool {
        if !self.require_rvv() || rd % nf != 0 {
            return false;
        }
        self.mark_vs_dirty();
        if self.d.vstart_eq_zero {
            // Load or store eight bytes at a time, atomically when possible, and keep
            // vstart up to date with the elements done.
            let size = crate::cpu::VLENB as i32 * nf;
            let atom = if log2_esz == 0 { MemOp::ATOM_NONE } else { MemOp::ATOM_IFALIGN_PAIR };
            let memop = MemOp::LEUQ | atom;
            let idx = self.d.mem_idx;
            let t8 = self.new64();
            let vs = self.new64();
            for i in (0..size).step_by(8) {
                let addr = self.address(rs1, i64::from(i));
                let off = voff(rd as u32, i as usize) as i64;
                let env = self.env();
                if k == Ldst::Load {
                    self.f().gen_qemu_ld_i64(t8, addr, idx, memop);
                    if cfg!(target_endian = "big") {
                        self.f().gen_bswap64_i64(t8, t8);
                    }
                    self.f().gen_st_i64(t8, env, off);
                } else {
                    self.f().gen_ld_i64(t8, env, off);
                    if cfg!(target_endian = "big") {
                        self.f().gen_bswap64_i64(t8, t8);
                    }
                    self.f().gen_qemu_st_i64(t8, addr, idx, memop);
                }
                if i == size - 8 {
                    self.f().gen_movi_i64(vs, 0);
                } else {
                    self.f().gen_ld_i64(vs, env, VSTART as i64);
                    self.f().gen_addi_i64(vs, vs, i64::from(8 >> log2_esz));
                }
                self.f().gen_st_i64(vs, env, VSTART as i64);
            }
        } else {
            let desc = Desc {
                vm: true,
                nf: nf as u32,
                vd: rd as u32,
                esz: log2_esz as u32,
                ..Desc::default()
            };
            let h = if k == Ldst::Load { &vector::VLRE } else { &vector::VSR };
            let base = self.gpr(rs1);
            self.vcall(h, None, desc, &[base.into()]);
        }
        self.finalize_rvv_inst();
        true
    }
}

/// Generate a `trans_*` method that passes its arguments and constants to a method of
/// `S`: `vtrans!(method(fields; consts) => trans_a(arg_a))`.
macro_rules! vtrans {
    ($m:ident($($f:ident),*; $($c:expr),*) => $t:ident($arg:ty)) => {
        fn $t(&mut self, a: &mut $arg) -> bool {
            self.$m($(a.$f,)* $($c),*)
        }
    };
}
pub(super) use vtrans;

/// The vector configuration, load and store `trans_*` methods of `DecodeInsn32`, and those
/// of the other vector files.
macro_rules! rvv_trans32 {
    () => {
        fn trans_vsetvl(&mut self, a: &mut arg_vsetvl) -> bool {
            self.vsetvl(a.rd, a.rs1, a.rs2)
        }

        fn trans_vsetvli(&mut self, a: &mut arg_vsetvli) -> bool {
            self.vsetvli(a.rd, a.rs1, a.zimm)
        }

        fn trans_vsetivli(&mut self, a: &mut arg_vsetivli) -> bool {
            self.vsetivli(a.rd, a.rs1, a.zimm)
        }

        // Unit stride, strided, indexed and fault-only-first.
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 0, Ldst::Load) =>
            trans_vle8_v(arg_vle8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 1, Ldst::Load) =>
            trans_vle16_v(arg_vle16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 2, Ldst::Load) =>
            trans_vle32_v(arg_vle32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 3, Ldst::Load) =>
            trans_vle64_v(arg_vle64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 0, Ldst::Store) =>
            trans_vse8_v(arg_vse8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 1, Ldst::Store) =>
            trans_vse16_v(arg_vse16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 2, Ldst::Store) =>
            trans_vse32_v(arg_vse32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_us(rd, rs1, nf, vm; 3, Ldst::Store) =>
            trans_vse64_v(arg_vse64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_mask(rd, rs1; Ldst::Load) =>
            trans_vlm_v(arg_vlm_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_mask(rd, rs1; Ldst::Store) =>
            trans_vsm_v(arg_vsm_v));
        $crate::tcg::translate_rvv::vtrans!(ldff(rd, rs1, nf, vm; 0) =>
            trans_vle8ff_v(arg_vle8ff_v));
        $crate::tcg::translate_rvv::vtrans!(ldff(rd, rs1, nf, vm; 1) =>
            trans_vle16ff_v(arg_vle16ff_v));
        $crate::tcg::translate_rvv::vtrans!(ldff(rd, rs1, nf, vm; 2) =>
            trans_vle32ff_v(arg_vle32ff_v));
        $crate::tcg::translate_rvv::vtrans!(ldff(rd, rs1, nf, vm; 3) =>
            trans_vle64ff_v(arg_vle64ff_v));

        fn trans_vlse8_v(&mut self, a: &mut arg_vlse8_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 0, Ldst::Load)
        }
        fn trans_vlse16_v(&mut self, a: &mut arg_vlse16_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 1, Ldst::Load)
        }
        fn trans_vlse32_v(&mut self, a: &mut arg_vlse32_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 2, Ldst::Load)
        }
        fn trans_vlse64_v(&mut self, a: &mut arg_vlse64_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 3, Ldst::Load)
        }
        fn trans_vsse8_v(&mut self, a: &mut arg_vsse8_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 0, Ldst::Store)
        }
        fn trans_vsse16_v(&mut self, a: &mut arg_vsse16_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 1, Ldst::Store)
        }
        fn trans_vsse32_v(&mut self, a: &mut arg_vsse32_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 2, Ldst::Store)
        }
        fn trans_vsse64_v(&mut self, a: &mut arg_vsse64_v) -> bool {
            self.ldst_stride((a.rd, a.rs1, a.rs2, a.nf, a.vm), 3, Ldst::Store)
        }
        fn trans_vlxei8_v(&mut self, a: &mut arg_vlxei8_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 0, Ldst::Load)
        }
        fn trans_vlxei16_v(&mut self, a: &mut arg_vlxei16_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 1, Ldst::Load)
        }
        fn trans_vlxei32_v(&mut self, a: &mut arg_vlxei32_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 2, Ldst::Load)
        }
        fn trans_vlxei64_v(&mut self, a: &mut arg_vlxei64_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 3, Ldst::Load)
        }
        fn trans_vsxei8_v(&mut self, a: &mut arg_vsxei8_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 0, Ldst::Store)
        }
        fn trans_vsxei16_v(&mut self, a: &mut arg_vsxei16_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 1, Ldst::Store)
        }
        fn trans_vsxei32_v(&mut self, a: &mut arg_vsxei32_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 2, Ldst::Store)
        }
        fn trans_vsxei64_v(&mut self, a: &mut arg_vsxei64_v) -> bool {
            self.ldst_index((a.rd, a.rs1, a.rs2, a.nf, a.vm), 3, Ldst::Store)
        }

        // Whole register.
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 1, 0, Ldst::Load) =>
            trans_vl1re8_v(arg_vl1re8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 1, 1, Ldst::Load) =>
            trans_vl1re16_v(arg_vl1re16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 1, 2, Ldst::Load) =>
            trans_vl1re32_v(arg_vl1re32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 1, 3, Ldst::Load) =>
            trans_vl1re64_v(arg_vl1re64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 2, 0, Ldst::Load) =>
            trans_vl2re8_v(arg_vl2re8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 2, 1, Ldst::Load) =>
            trans_vl2re16_v(arg_vl2re16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 2, 2, Ldst::Load) =>
            trans_vl2re32_v(arg_vl2re32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 2, 3, Ldst::Load) =>
            trans_vl2re64_v(arg_vl2re64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 4, 0, Ldst::Load) =>
            trans_vl4re8_v(arg_vl4re8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 4, 1, Ldst::Load) =>
            trans_vl4re16_v(arg_vl4re16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 4, 2, Ldst::Load) =>
            trans_vl4re32_v(arg_vl4re32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 4, 3, Ldst::Load) =>
            trans_vl4re64_v(arg_vl4re64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 8, 0, Ldst::Load) =>
            trans_vl8re8_v(arg_vl8re8_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 8, 1, Ldst::Load) =>
            trans_vl8re16_v(arg_vl8re16_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 8, 2, Ldst::Load) =>
            trans_vl8re32_v(arg_vl8re32_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 8, 3, Ldst::Load) =>
            trans_vl8re64_v(arg_vl8re64_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 1, 0, Ldst::Store) =>
            trans_vs1r_v(arg_vs1r_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 2, 0, Ldst::Store) =>
            trans_vs2r_v(arg_vs2r_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 4, 0, Ldst::Store) =>
            trans_vs4r_v(arg_vs4r_v));
        $crate::tcg::translate_rvv::vtrans!(ldst_whole(rd, rs1; 8, 0, Ldst::Store) =>
            trans_vs8r_v(arg_vs8r_v));
    };
}
pub(super) use rvv_trans32;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn overlap_rules() {
        assert!(is_overlapped(0, 2, 1, 1));
        assert!(!is_overlapped(0, 2, 2, 2));
        assert!(require_align(4, 2));
        assert!(!require_align(2, 2));
        assert!(require_align(3, -1));
        assert!(require_nf(0, 8, 0));
        assert!(!require_nf(0, 3, 2));
        assert!(!require_nf(30, 3, 0));
        // A widening destination v2-v3 over a source v3 overlaps in its top half (rule 3).
        assert!(require_noover(2, 1, 3, 0));
        // ... but not over a source v2.
        assert!(!require_noover(2, 1, 2, 0));
        // A fractional source may not overlap at all.
        assert!(!require_noover(2, 1, 3, -1));
        assert!(require_noover(4, 1, 2, 1));
        assert!(!require_vm(0, 0));
        assert!(require_vm(1, 0));
    }
}
