[package]
name = "ruvm-accel-kvm"
description = "The KVM accelerator."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 4

[dependencies]
ruvm-base.workspace = true
ruvm-mem.workspace = true

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
kvm-bindings.workspace = true
kvm-ioctls.workspace = true
libc.workspace = true
vmm-sys-util.workspace = true

[dev-dependencies]
ruvm-mem.workspace = true

[lints]
workspace = true
