[package]
name = "ruvm-accel-whpx"
description = "The Windows Hypervisor Platform accelerator."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 44

[target.'cfg(windows)'.dependencies]
ruvm-mem.workspace = true
windows-sys.workspace = true

[lints]
workspace = true
