[package]
name = "ruvm-vhost"
description = "The vhost kernel interface, the vhost-user protocol, vhost-vdpa and VDUSE plumbing."
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 4

[dependencies]

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
vmm-sys-util.workspace = true

[target.'cfg(unix)'.dev-dependencies]
rustix.workspace = true

[lints]
workspace = true
