// SPDX-License-Identifier: GPL-2.0-or-later

//! The A64 scalar floating point and AdvSIMD translator: the FP, SIMD and crypto parts of
//! QEMU's `target/arm/tcg/translate-a64.c`.
//!
//! The `trans_` hooks are generated by [`simd_trans`] from a table that names, for every
//! pattern, the shape of the translation and the operation. The arithmetic is done by three
//! out of line helpers, `a64_neon` ([`super::super::vec_helper`]), `a64_fp`, `a64_fp_cmp` and
//! `a64_fp_gpr` ([`super::super::vfp`]) and `a64_crypto` ([`super::super::crypto`]), which take
//! the register numbers and a descriptor; moves, duplicates, immediates, FCSEL, the flag
//! setting of FCMP and the loads and stores are expanded inline as QEMU does.
//!
//! Differences from QEMU:
//!
//! - QEMU expands most integer vector operations inline with the TCG gvec ops and calls one
//!   helper per operation and element size for the rest. Here every AdvSIMD data processing
//!   instruction is one call of a helper that reads and writes the registers in `env`. The
//!   results, the FPSR flags and QC are the same; the generated code is slower.
//! - FEAT_AFP, FEAT_AH (FPCR.AH), FEAT_NEP, FEAT_RPRES and FEAT_FPRCVT are not implemented, so
//!   scalar results always clear the rest of the vector register, and the FPRCVT forms
//!   (`FCVT*` to and `SCVTF`/`UCVTF` from a general register size in a SIMD register) are
//!   unallocated, as they are in QEMU for CPUs without the feature.
//! - With SVE, QEMU clears the bits of the Z register above 128 (up to the vector length)
//!   on every AdvSIMD and FP write except the single structure loads, and so does this port
//!   (the helpers clear all 2048 bits, which is the same because the bits above the vector
//!   length are always zero, see `sve_narrow_vq()`).
//! - Data accesses are always little endian, and MTE tag checks are not done.
//! - QEMU checks the SP alignment of SIMD loads and stores through SP when the CPU asks for
//!   it; this port never does (as for the integer loads and stores).

use ruvm_jit::DisasJumpType;
use ruvm_jit_core::MemOp;
use ruvm_jit_core::ir::{TempI32, TempI64};
use ruvm_jit_core::types::Cond;

use super::S;
use super::decode::{
    arg_crypto3i, arg_disas_a6452, arg_disas_a6465, arg_disas_a6466, arg_disas_a6467,
    arg_disas_a6470, arg_disas_a6471, arg_disas_a6473, arg_disas_a6474, arg_disas_a6475,
    arg_disas_a6476, arg_disas_a6477, arg_fcvt, arg_fcvt_q, arg_ldlit, arg_ldst, arg_ldst_imm,
    arg_ldst_mult, arg_ldst_single, arg_ldstpair, arg_qrr_e, arg_qrri_e, arg_qrrr_e, arg_qrrx_e,
    arg_rr, arg_rr_e, arg_rri_e, arg_rrr_e, arg_rrrr_e, arg_rrx_e,
};
use crate::cpu::{CF, EXCP_UDEF, NF, VF, ZF, vreg_off};
use crate::syndrome::syn_a64_fp_access_trap;
use crate::tcg::helpers::{self, Def};
use crate::tcg::vec_helper::{Desc, NEON, Regs};
use crate::tcg::vfp::{FP, FP_CMP, FP_GPR, vfp_expand_imm};

pub(super) use crate::tcg::crypto::op as cop;
pub(super) use crate::tcg::vec_helper::op as nop;
pub(super) use crate::tcg::vfp::op as fop;

/// The rounding mode values of [`Desc::rmode`]: `FPROUNDING_TIEEVEN`, `_NEGINF`, `_POSINF`,
/// `_ZERO`, `_TIEAWAY`, and the mode in FPCR.
pub(super) const RN: u32 = 0;
pub(super) const RM: u32 = 1;
pub(super) const RP: u32 = 2;
pub(super) const RZ: u32 = 3;
pub(super) const RA: u32 = 4;
pub(super) const RF: u32 = crate::tcg::vec_helper::RMODE_FPCR;

/// The element size checks QEMU does before `fp_access_check()`.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Chk {
    None,
    /// `do_gvec_fn*`: no 64 bit elements in a 64 bit vector.
    Fn,
    /// `do_gvec_fn*_no64`: no 64 bit elements.
    No64,
    /// `_hs`, `_no8_no64`: 16 or 32 bit elements only.
    Hs,
}

/// The ID register features some instructions need.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Feat {
    None,
    Fp16,
    Rdm,
    DotProd,
    Aes,
    Pmull,
    Sha1,
    Sha256,
}

/// The FMOV forms between a general and a SIMD register.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Mov {
    /// Hd from Wn.
    Hx,
    /// Sd from Wn.
    Sw,
    /// Dd from Xn.
    Dx,
    /// Vd.D[1] from Xn.
    Ux,
    /// Wd from Hn.
    Xh,
    /// Wd from Sn.
    Ws,
    /// Xd from Dn.
    Xd,
    /// Xd from Vn.D[1].
    Xu,
}

fn chk(c: Chk, q: i32, esz: i32) -> bool {
    match c {
        Chk::None => true,
        Chk::Fn => !(q == 0 && esz == 3),
        Chk::No64 => esz != 3,
        Chk::Hs => esz == 1 || esz == 2,
    }
}

fn oprsz(q: i32) -> usize {
    if q != 0 { 16 } else { 8 }
}

/// `decode_esz_idx()`: the element size and index of the imm5 field of the copy instructions.
fn decode_esz_idx(imm: i32) -> Option<(i32, i32)> {
    let esz = (imm as u32).trailing_zeros() as i32;
    if esz <= 3 { Some((esz, imm >> (esz + 1))) } else { None }
}

/// `asimd_imm_const()`: AdvSIMDExpandImm, with the inversion of the op=1 forms.
pub(super) fn asimd_imm_const(imm: u32, cmode: i32, op: i32) -> u64 {
    let mut imm = imm;
    match cmode {
        0 | 1 => {}
        2 | 3 => imm <<= 8,
        4 | 5 => imm <<= 16,
        6 | 7 => imm <<= 24,
        8 | 9 => imm |= imm << 16,
        10 | 11 => imm = (imm << 8) | (imm << 24),
        12 => imm = (imm << 8) | 0xff,
        13 => imm = (imm << 16) | 0xffff,
        14 => {
            if op != 0 {
                let mut imm64 = 0u64;
                for n in 0..8 {
                    if imm & (1 << n) != 0 {
                        imm64 |= 0xff << (n * 8);
                    }
                }
                return imm64;
            }
            imm |= (imm << 8) | (imm << 16) | (imm << 24);
        }
        _ => {
            if op != 0 {
                let mut imm64 = u64::from(imm & 0x3f) << 48;
                if imm & 0x80 != 0 {
                    imm64 |= 0x8000_0000_0000_0000;
                }
                if imm & 0x40 != 0 {
                    imm64 |= 0x3fc0_0000_0000_0000;
                } else {
                    imm64 |= 0x4000_0000_0000_0000;
                }
                return imm64;
            }
            imm = ((imm & 0x80) << 24)
                | ((imm & 0x3f) << 19)
                | if imm & 0x40 != 0 { 0x1f << 25 } else { 1 << 30 };
        }
    }
    if op != 0 {
        imm = !imm;
    }
    u64::from(imm) * 0x0000_0001_0000_0001
}

/// Replicate the low `8 << esz` bits of a value to 64 bits.
fn dup_const(esz: i32, v: u64) -> u64 {
    match esz {
        0 => (v & 0xff) * 0x0101_0101_0101_0101,
        1 => (v & 0xffff) * 0x0001_0001_0001_0001,
        2 => (v & 0xffff_ffff) * 0x0000_0001_0000_0001,
        _ => v,
    }
}

impl S<'_, '_> {
    /// `fp_access_check()`: raise the FP access trap if CPACR_EL1.FPEN says so. Returns true
    /// if the instruction should be translated.
    pub(super) fn fp_access_check(&mut self) -> bool {
        if self.d.fp_excp_el == 0 {
            return true;
        }
        self.update_pc(0);
        let env = self.env();
        let e = self.c32(EXCP_UDEF);
        let syn = self.c32(syn_a64_fp_access_trap(1, 0xe) as i32);
        let el = self.c32(self.d.fp_excp_el as i32);
        self.call(
            &helpers::EXCEPTION_WITH_SYNDROME_EL,
            None,
            &[env.into(), e.into(), syn.into(), el.into()],
        );
        self.b.is_jmp = DisasJumpType::NoReturn;
        false
    }

    fn has(&self, f: Feat) -> bool {
        let x = self.feat();
        match f {
            Feat::None => true,
            Feat::Fp16 => x.fp16,
            Feat::Rdm => x.rdm,
            Feat::DotProd => x.dotprod,
            Feat::Aes => x.aes,
            Feat::Pmull => x.pmull,
            Feat::Sha1 => x.sha1,
            Feat::Sha256 => x.sha256,
        }
    }

    /// `fp_access_check_vector_hsd()` and `_scalar_hsd()` (with `q` set) without the access
    /// check: whether the element size is allocated.
    fn hsd(&self, esz: i32, q: bool) -> bool {
        match esz {
            3 => q,
            2 => true,
            1 => self.feat().fp16,
            _ => false,
        }
    }

    fn vcall(&mut self, def: &Def, r: [i32; 4], desc: Desc) {
        let env = self.env();
        let regs = self.c32(Regs::pack(r[0], r[1], r[2], r[3]) as i32);
        let d = self.c32(desc.pack() as i32);
        self.call(def, None, &[env.into(), regs.into(), d.into()]);
    }

    /// Translate a helper call: false if not allocated, the access check, then the call.
    fn emit(&mut self, ok: bool, def: &Def, r: [i32; 4], desc: Desc) -> bool {
        if !ok {
            return false;
        }
        if self.fp_access_check() {
            self.vcall(def, r, desc);
        }
        true
    }

    // Element access.

    fn elem_off(reg: i32, idx: i32, esz: i32) -> i64 {
        (vreg_off(reg as usize) + ((idx as usize) << esz)) as i64
    }

    /// `read_vec_element()`: element `idx` of `reg`, zero or sign extended.
    fn read_elem(&mut self, reg: i32, idx: i32, esz: i32, signed: bool) -> TempI64 {
        let t = self.new64();
        let env = self.env();
        let off = Self::elem_off(reg, idx, esz);
        let f = self.f();
        match (esz, signed) {
            (0, false) => f.gen_ld8u_i64(t, env, off),
            (0, true) => f.gen_ld8s_i64(t, env, off),
            (1, false) => f.gen_ld16u_i64(t, env, off),
            (1, true) => f.gen_ld16s_i64(t, env, off),
            (2, false) => f.gen_ld32u_i64(t, env, off),
            (2, true) => f.gen_ld32s_i64(t, env, off),
            _ => f.gen_ld_i64(t, env, off),
        }
        t
    }

    /// `write_vec_element()`.
    fn write_elem(&mut self, reg: i32, idx: i32, esz: i32, t: TempI64) {
        let env = self.env();
        let off = Self::elem_off(reg, idx, esz);
        let f = self.f();
        match esz {
            0 => f.gen_st8_i64(t, env, off),
            1 => f.gen_st16_i64(t, env, off),
            2 => f.gen_st32_i64(t, env, off),
            _ => f.gen_st_i64(t, env, off),
        }
    }

    /// Write the two halves of a register; `hi` None writes zero.
    fn write_vreg(&mut self, reg: i32, lo: TempI64, hi: Option<TempI64>) {
        let off = vreg_off(reg as usize);
        self.st_env64(lo, off);
        let hi = match hi {
            Some(h) => h,
            None => self.c64(0),
        };
        self.st_env64(hi, off + 8);
        self.clear_sve(reg);
    }

    /// The part of `clear_vec_high()` above 128 bits: with SVE, zero the bytes of the Z
    /// register from 16 up to the vector length.
    pub(super) fn clear_sve(&mut self, reg: i32) {
        let vl = self.d.vl as usize;
        if !self.feat().sve || vl <= 16 {
            return;
        }
        let z = self.c64(0);
        let off = vreg_off(reg as usize);
        for o in (16..vl).step_by(8) {
            self.st_env64(z, off + o);
        }
    }

    /// `write_fp_dreg()`: the low 64 bits, clearing the rest.
    fn write_fp_dreg(&mut self, reg: i32, t: TempI64) {
        self.write_vreg(reg, t, None);
    }

    /// `clear_vec_high()` for a 64 bit write.
    fn clear_high(&mut self, reg: i32) {
        let z = self.c64(0);
        self.st_env64(z, vreg_off(reg as usize) + 8);
        self.clear_sve(reg);
    }

    /// Replicate the low element of `t` across 64 bits, in place.
    fn dup64(&mut self, t: TempI64, esz: i32) {
        let f = self.f();
        match esz {
            0 => {
                f.gen_ext8u_i64(t, t);
                f.gen_muli_i64(t, t, 0x0101_0101_0101_0101);
            }
            1 => {
                f.gen_ext16u_i64(t, t);
                f.gen_muli_i64(t, t, 0x0001_0001_0001_0001);
            }
            2 => {
                f.gen_ext32u_i64(t, t);
                f.gen_muli_i64(t, t, 0x0000_0001_0000_0001);
            }
            _ => {}
        }
    }

    /// Write a replicated 64 bit value to the low half, and to the high half if `q`.
    fn write_dup(&mut self, reg: i32, t: TempI64, q: bool) {
        self.write_vreg(reg, t, if q { Some(t) } else { None });
    }

    // Integer three registers.

    pub(super) fn v3(&mut self, a: &arg_qrrr_e, op: u32, c: Chk, f: Feat) -> bool {
        let ok = self.has(f) && chk(c, a.q, a.esz);
        self.emit(ok, &NEON, [a.rd, a.rn, a.rm, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    /// SUQADD and USQADD: the accumulator is Rd and the source Rm.
    pub(super) fn v3acc(&mut self, a: &arg_qrrr_e, op: u32) -> bool {
        let ok = chk(Chk::Fn, a.q, a.esz);
        self.emit(ok, &NEON, [a.rd, a.rm, 0, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    pub(super) fn s3(&mut self, a: &arg_rrr_e, op: u32, c: Chk, f: Feat) -> bool {
        let ok = self.has(f) && chk(c, 1, a.esz);
        self.emit(ok, &NEON, [a.rd, a.rn, a.rm, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    pub(super) fn s3acc(&mut self, a: &arg_rrr_e, op: u32) -> bool {
        self.emit(true, &NEON, [a.rd, a.rm, 0, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    // Integer two registers.

    pub(super) fn v2(&mut self, a: &arg_qrr_e, op: u32, c: Chk) -> bool {
        let ok = chk(c, a.q, a.esz);
        self.emit(ok, &NEON, [a.rd, a.rn, 0, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    pub(super) fn s2(&mut self, a: &arg_rr_e, op: u32) -> bool {
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    /// The scalar forms that only have 64 bit elements.
    pub(super) fn s2d(&mut self, a: &arg_rr, op: u32) -> bool {
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], Desc::new(op, 3, 8))
    }

    /// Scalar pairwise: one result from the two elements of Rn.
    pub(super) fn sp(&mut self, a: &arg_rr_e, op: u32) -> bool {
        self.emit(true, &NEON, [a.rd, a.rn, a.rn, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    /// `do_int_reduction()`: at least four elements.
    pub(super) fn vred(&mut self, a: &arg_qrr_e, op: u32) -> bool {
        let ok = a.esz != 3 && (oprsz(a.q) >> a.esz) >= 4;
        self.emit(ok, &NEON, [a.rd, a.rn, 0, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    /// The narrowing forms: the "2" forms (`q` set) write the high half and keep the low.
    pub(super) fn narrow_v(&mut self, a: &arg_qrr_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, oprsz(a.q)).hi(a.q != 0);
        self.emit(a.esz != 3, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn narrow_s(&mut self, a: &arg_rr_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 1 << a.esz);
        self.emit(a.esz != 3, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn shll(&mut self, a: &arg_qrr_e) -> bool {
        let desc = Desc::new(nop::SHLL, a.esz, 16).hi(a.q != 0);
        self.emit(a.esz != 3, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    // Shifts by immediate.

    pub(super) fn vsh(&mut self, a: &arg_qrri_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, oprsz(a.q)).imm(a.imm);
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn ssh(&mut self, a: &arg_rri_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 1 << a.esz).imm(a.imm);
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn vshn(&mut self, a: &arg_qrri_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, oprsz(a.q)).hi(a.q != 0).imm(a.imm);
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn vshll(&mut self, a: &arg_qrri_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 16).hi(a.q != 0).imm(a.imm);
        self.emit(true, &NEON, [a.rd, a.rn, 0, 0], desc)
    }

    // Widening, narrowing three registers and indexed.

    pub(super) fn wide(&mut self, a: &arg_qrrr_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 16).hi(a.q != 0);
        self.emit(a.esz < 3, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn pmull64(&mut self, a: &arg_qrrr_e) -> bool {
        let ok = self.has(Feat::Pmull);
        let desc = Desc::new(nop::PMULL, 3, 16).hi(a.q != 0);
        self.emit(ok, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn wide_vi(&mut self, a: &arg_qrrx_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 16).hi(a.q != 0).indexed(a.idx);
        self.emit(a.esz < 3, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn wide_si(&mut self, a: &arg_rrx_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 1 << a.esz).indexed(a.idx);
        self.emit(a.esz < 3, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn vi(&mut self, a: &arg_qrrx_e, op: u32, f: Feat) -> bool {
        let ok = self.has(f);
        let desc = Desc::new(op, a.esz, oprsz(a.q)).indexed(a.idx);
        self.emit(ok, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn si(&mut self, a: &arg_rrx_e, op: u32, f: Feat) -> bool {
        let ok = self.has(f) && chk(Chk::Hs, 1, a.esz);
        let desc = Desc::new(op, a.esz, 1 << a.esz).indexed(a.idx);
        self.emit(ok, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    // Permutes and tables.

    pub(super) fn ext(&mut self, a: &arg_crypto3i, q: bool) -> bool {
        let desc = Desc::new(nop::EXT, 0, if q { 16 } else { 8 }).imm(a.imm);
        self.emit(true, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn tbl(&mut self, a: &arg_disas_a6471) -> bool {
        let op = if a.tbx != 0 { nop::TBX } else { nop::TBL };
        let desc = Desc::new(op, 0, oprsz(a.q)).imm(a.len);
        self.emit(true, &NEON, [a.rd, a.rn, a.rm, 0], desc)
    }

    // Crypto.

    pub(super) fn cr3(&mut self, a: &arg_qrrr_e, op: u32, f: Feat) -> bool {
        let ok = self.has(f);
        let def = &crate::tcg::crypto::CRYPTO;
        self.emit(ok, def, [a.rd, a.rn, a.rm, 0], Desc::new(op, 0, 16))
    }

    pub(super) fn cr2(&mut self, a: &arg_qrr_e, op: u32, f: Feat) -> bool {
        let ok = self.has(f);
        let def = &crate::tcg::crypto::CRYPTO;
        self.emit(ok, def, [a.rd, a.rn, 0, 0], Desc::new(op, 0, 16))
    }

    /// AESE and AESD: the state is Rd and the key Rm.
    pub(super) fn aes(&mut self, a: &arg_qrrr_e, op: u32) -> bool {
        let ok = self.has(Feat::Aes);
        let def = &crate::tcg::crypto::CRYPTO;
        self.emit(ok, def, [a.rd, a.rm, 0, 0], Desc::new(op, 0, 16))
    }

    // Floating point data processing.

    pub(super) fn f3v(&mut self, a: &arg_qrrr_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, a.q != 0);
        self.emit(ok, &FP, [a.rd, a.rn, a.rm, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    pub(super) fn f3s(&mut self, a: &arg_rrr_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        self.emit(ok, &FP, [a.rd, a.rn, a.rm, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    /// Scalar pairwise: one result from the two elements of Rn.
    pub(super) fn fps(&mut self, a: &arg_rr_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        self.emit(ok, &FP, [a.rd, a.rn, a.rn, 0], Desc::new(op, a.esz, 1 << a.esz))
    }

    /// `do_fp_reduction()`; the half precision forms need FEAT_FP16.
    pub(super) fn fred(&mut self, a: &arg_qrr_e, op: u32) -> bool {
        let ok = a.esz != 1 || self.has(Feat::Fp16);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], Desc::new(op, a.esz, oprsz(a.q)))
    }

    pub(super) fn f2s(&mut self, a: &arg_rr_e, op: u32, rm: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        let desc = Desc::new(op, a.esz, 1 << a.esz).rmode(rm);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn f2v(&mut self, a: &arg_qrr_e, op: u32, rm: u32) -> bool {
        let ok = self.hsd(a.esz, a.q != 0);
        let desc = Desc::new(op, a.esz, oprsz(a.q)).rmode(rm);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn fsi(&mut self, a: &arg_rrx_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        let desc = Desc::new(op, a.esz, 1 << a.esz).indexed(a.idx);
        self.emit(ok, &FP, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn fvi(&mut self, a: &arg_qrrx_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, a.q != 0);
        let desc = Desc::new(op, a.esz, oprsz(a.q)).indexed(a.idx);
        self.emit(ok, &FP, [a.rd, a.rn, a.rm, 0], desc)
    }

    pub(super) fn fmadd(&mut self, a: &arg_rrrr_e, op: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        self.emit(ok, &FP, [a.rd, a.rn, a.rm, a.ra], Desc::new(op, a.esz, 1 << a.esz))
    }

    // Conversions.

    /// `do_fcvt_g()`: FP to a general register.
    pub(super) fn fcvt_g(&mut self, a: &arg_fcvt, signed: bool, rm: u32) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if self.fp_access_check() {
            let op = if signed { fop::TOSINT } else { fop::TOUINT };
            let desc = Desc::new(op, a.esz, 1 << a.esz).imm(a.shift).hi(a.sf != 0).rmode(rm);
            let x = self.c64(0);
            let ret = self.gpr_call(x, [0, a.rn, 0, 0], desc);
            self.set_reg(a.rd, ret);
        }
        true
    }

    /// `do_cvtf_g()`: a general register to FP.
    pub(super) fn cvtf_g(&mut self, a: &arg_fcvt, signed: bool) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if self.fp_access_check() {
            let op = if signed { fop::SCVTF } else { fop::UCVTF };
            let desc = Desc::new(op, a.esz, 1 << a.esz).imm(a.shift).hi(a.sf != 0);
            let x = self.reg(a.rn);
            self.gpr_call(x, [a.rd, 0, 0, 0], desc);
        }
        true
    }

    fn gpr_call(&mut self, x: TempI64, r: [i32; 4], desc: Desc) -> TempI64 {
        let env = self.env();
        let regs = self.c32(Regs::pack(r[0], r[1], r[2], r[3]) as i32);
        let d = self.c32(desc.pack() as i32);
        let ret = self.new64();
        self.call(&FP_GPR, Some(ret.into()), &[env.into(), x.into(), regs.into(), d.into()]);
        ret
    }

    /// `do_fcvt_f()`: FP to an integer of the same size in a SIMD register.
    pub(super) fn fcvt_f(&mut self, a: &arg_fcvt, signed: bool, rm: u32) -> bool {
        let ok = self.hsd(a.esz, true);
        let op = if signed { fop::TOSINT } else { fop::TOUINT };
        let desc = Desc::new(op, a.esz, 1 << a.esz).imm(a.shift).rmode(rm);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    /// `do_cvtf_f()`.
    pub(super) fn cvtf_f(&mut self, a: &arg_fcvt, signed: bool) -> bool {
        let ok = self.hsd(a.esz, true);
        let op = if signed { fop::SCVTF } else { fop::UCVTF };
        let desc = Desc::new(op, a.esz, 1 << a.esz).imm(a.shift);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    /// The vector fixed point forms: FCVTZS and FCVTZU round to zero.
    pub(super) fn cvt_vf(&mut self, a: &arg_fcvt_q, op: u32) -> bool {
        let ok = self.hsd(a.esz, a.q != 0);
        let rm = if op == fop::TOSINT || op == fop::TOUINT { RZ } else { RF };
        let desc = Desc::new(op, a.esz, oprsz(a.q)).imm(a.shift).rmode(rm);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    /// FCVT between precisions: `from` and `to` are element sizes.
    pub(super) fn fcvt_s(&mut self, a: &arg_rr, from: i32, to: i32) -> bool {
        let desc = Desc::new(fop::FCVT, from, 1 << from).imm(to);
        self.emit(true, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn fcvtl(&mut self, a: &arg_qrr_e) -> bool {
        let desc = Desc::new(fop::FCVTL, a.esz, 16).hi(a.q != 0);
        self.emit(true, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn fcvtn(&mut self, a: &arg_qrr_e, op: u32) -> bool {
        let desc = Desc::new(op, a.esz, 8).hi(a.q != 0);
        self.emit(a.esz != 3, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    pub(super) fn fcvtxn_s(&mut self, a: &arg_rr_e) -> bool {
        let desc = Desc::new(fop::FCVTXN, 2, 4);
        self.emit(true, &FP, [a.rd, a.rn, 0, 0], desc)
    }

    /// URECPE and URSQRTE: integer estimates on 32 bit elements.
    pub(super) fn urecpe(&mut self, a: &arg_qrr_e, op: u32) -> bool {
        let ok = chk(Chk::Fn, a.q, a.esz);
        self.emit(ok, &FP, [a.rd, a.rn, 0, 0], Desc::new(op, 2, oprsz(a.q)))
    }

    // Moves and immediates.

    pub(super) fn fmov_g(&mut self, a: &arg_rr, k: Mov) -> bool {
        if matches!(k, Mov::Hx | Mov::Xh) && !self.has(Feat::Fp16) {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let rn_off = vreg_off(a.rn as usize);
        match k {
            Mov::Hx | Mov::Sw | Mov::Dx => {
                let t = self.reg(a.rn);
                match k {
                    Mov::Hx => self.f().gen_ext16u_i64(t, t),
                    Mov::Sw => self.f().gen_ext32u_i64(t, t),
                    _ => {}
                }
                self.write_fp_dreg(a.rd, t);
            }
            Mov::Ux => {
                let t = self.reg(a.rn);
                self.st_env64(t, vreg_off(a.rd as usize) + 8);
                self.clear_sve(a.rd);
            }
            Mov::Xh => {
                let t = self.read_elem(a.rn, 0, 1, false);
                self.set_reg(a.rd, t);
            }
            Mov::Ws => {
                let t = self.read_elem(a.rn, 0, 2, false);
                self.set_reg(a.rd, t);
            }
            Mov::Xd => {
                let t = self.ld_env64(rn_off);
                self.set_reg(a.rd, t);
            }
            Mov::Xu => {
                let t = self.ld_env64(rn_off + 8);
                self.set_reg(a.rd, t);
            }
        }
        true
    }

    pub(super) fn fcsel(&mut self, a: &arg_disas_a6470) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if self.fp_access_check() {
            let t_true = self.read_elem(a.rn, 0, a.esz, false);
            let t_false = self.read_elem(a.rm, 0, a.esz, false);
            let (cond, v) = self.test_cc64(a.cond);
            let zero = self.c64(0);
            self.f().gen_movcond_i64(cond, t_true, v, zero, t_true, t_false);
            self.write_fp_dreg(a.rd, t_true);
        }
        true
    }

    /// `gen_set_nzcv()`: NZCV from bits 31 to 28 of `t`.
    fn set_nzcv(&mut self, t: TempI32) {
        self.st_env32(t, NF);
        let z = self.new32();
        let c = self.new32();
        let v = self.new32();
        let f = self.f();
        f.gen_andi_i32(z, t, 0x4000_0000);
        f.gen_setcondi_i32(Cond::Eq, z, z, 0);
        f.gen_shri_i32(c, t, 29);
        f.gen_andi_i32(c, c, 1);
        f.gen_andi_i32(v, t, 0x1000_0000);
        f.gen_shli_i32(v, v, 3);
        self.st_env32(z, ZF);
        self.st_env32(c, CF);
        self.st_env32(v, VF);
    }

    /// `handle_fp_compare()`.
    fn fp_compare(&mut self, esz: i32, rn: i32, rm: i32, zero: bool, signal: bool) {
        let op = if signal { fop::CMPE } else { fop::CMP };
        let desc = Desc::new(op, esz, 1 << esz).imm(i32::from(zero));
        let env = self.env();
        let regs = self.c32(Regs::pack(0, rn, rm, 0) as i32);
        let d = self.c32(desc.pack() as i32);
        let ret = self.new32();
        self.call(&FP_CMP, Some(ret.into()), &[env.into(), regs.into(), d.into()]);
        self.set_nzcv(ret);
    }

    pub(super) fn fcmp(&mut self, a: &arg_disas_a6474) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if self.fp_access_check() {
            self.fp_compare(a.esz, a.rn, a.rm, a.z != 0, a.e != 0);
        }
        true
    }

    pub(super) fn fccmp(&mut self, a: &arg_disas_a6475) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let mut cont = None;
        if a.cond < 0xe {
            let matched = self.f().new_label();
            let l = self.f().new_label();
            let (cond, v) = self.test_cc(a.cond);
            self.f().gen_brcondi_i32(cond, v, 0, matched);
            let nzcv = self.c32(((a.nzcv as u32) << 28) as i32);
            self.set_nzcv(nzcv);
            self.f().gen_br(l);
            self.f().gen_set_label(matched);
            cont = Some(l);
        }
        self.fp_compare(a.esz, a.rn, a.rm, false, a.e != 0);
        if let Some(l) = cont {
            self.f().gen_set_label(l);
        }
        true
    }

    pub(super) fn fmovi_s(&mut self, a: &arg_disas_a6473) -> bool {
        if !self.hsd(a.esz, true) {
            return false;
        }
        if self.fp_access_check() {
            let imm = vfp_expand_imm(a.esz as u32, a.imm as u32);
            let t = self.c64(imm as i64);
            self.write_fp_dreg(a.rd, t);
        }
        true
    }

    pub(super) fn fmovi_vh(&mut self, a: &arg_disas_a6476) -> bool {
        if !self.has(Feat::Fp16) {
            return false;
        }
        if self.fp_access_check() {
            let imm = dup_const(1, vfp_expand_imm(1, a.abcdefgh as u32));
            let t = self.c64(imm as i64);
            self.write_dup(a.rd, t, a.q != 0);
        }
        true
    }

    /// `trans_Vimm()`: MOVI, MVNI, ORR, BIC and FMOV (vector, immediate).
    pub(super) fn vimm(&mut self, a: &arg_disas_a6477) -> bool {
        let logic = (a.cmode & 1) != 0 && a.cmode < 12;
        if !logic && a.cmode == 15 && a.op == 1 && a.q == 0 {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let imm = asimd_imm_const(a.abcdefgh as u32, a.cmode, a.op);
        if logic {
            let off = vreg_off(a.rd as usize);
            let lo = self.ld_env64(off);
            let hi = if a.q != 0 { Some(self.ld_env64(off + 8)) } else { None };
            for t in [Some(lo), hi].into_iter().flatten() {
                if a.op != 0 {
                    self.f().gen_andi_i64(t, t, imm as i64);
                } else {
                    self.f().gen_ori_i64(t, t, imm as i64);
                }
            }
            self.write_vreg(a.rd, lo, hi);
        } else {
            let t = self.c64(imm as i64);
            self.write_dup(a.rd, t, a.q != 0);
        }
        true
    }

    // Copies between elements and registers.

    pub(super) fn dup_s(&mut self, a: &arg_disas_a6465) -> bool {
        let Some((esz, idx)) = decode_esz_idx(a.imm) else {
            return false;
        };
        if self.fp_access_check() {
            let t = self.read_elem(a.rn, idx, esz, false);
            self.write_fp_dreg(a.rd, t);
        }
        true
    }

    pub(super) fn dup_v(&mut self, a: &arg_disas_a6466) -> bool {
        let Some((esz, idx)) = decode_esz_idx(a.imm) else {
            return false;
        };
        if esz == 3 && a.q == 0 {
            return false;
        }
        if self.fp_access_check() {
            let t = self.read_elem(a.rn, idx, esz, false);
            self.dup64(t, esz);
            self.write_dup(a.rd, t, a.q != 0);
        }
        true
    }

    pub(super) fn dup_g(&mut self, a: &arg_disas_a6466) -> bool {
        let Some((esz, _)) = decode_esz_idx(a.imm) else {
            return false;
        };
        if esz == 3 && a.q == 0 {
            return false;
        }
        if self.fp_access_check() {
            let t = self.reg(a.rn);
            self.dup64(t, esz);
            self.write_dup(a.rd, t, a.q != 0);
        }
        true
    }

    pub(super) fn ins_g(&mut self, a: &arg_disas_a6465) -> bool {
        let Some((esz, idx)) = decode_esz_idx(a.imm) else {
            return false;
        };
        if self.fp_access_check() {
            let t = self.reg(a.rn);
            self.write_elem(a.rd, idx, esz, t);
            self.clear_sve(a.rd);
        }
        true
    }

    pub(super) fn ins_e(&mut self, a: &arg_disas_a6467) -> bool {
        let Some((esz, didx)) = decode_esz_idx(a.di) else {
            return false;
        };
        let sidx = a.si >> esz;
        if self.fp_access_check() {
            let t = self.read_elem(a.rn, sidx, esz, false);
            self.write_elem(a.rd, didx, esz, t);
            self.clear_sve(a.rd);
        }
        true
    }

    /// `do_smov_umov()`.
    pub(super) fn smov_umov(&mut self, a: &arg_disas_a6466, signed: bool) -> bool {
        let Some((esz, idx)) = decode_esz_idx(a.imm) else {
            return false;
        };
        let bad = if signed {
            esz == 3 || (esz == 2 && a.q == 0)
        } else if esz == 3 {
            a.q == 0
        } else {
            a.q != 0
        };
        if bad {
            return false;
        }
        if self.fp_access_check() {
            let t = self.read_elem(a.rn, idx, esz, signed);
            if signed && a.q == 0 {
                self.f().gen_ext32u_i64(t, t);
            }
            self.set_reg(a.rd, t);
        }
        true
    }

    // Loads and stores.

    /// `finalize_memop_asimd()`.
    fn memop_asimd(&self, sz: i32) -> MemOp {
        if sz == 4 {
            self.finalize_memop_atom(MemOp(4), MemOp::ATOM_IFALIGN_PAIR)
        } else {
            self.finalize_memop(MemOp(sz as u32))
        }
    }

    /// `do_fp_ld()`: load into the low bits of `rt`, clearing the rest.
    fn fp_ld(&mut self, rt: i32, addr: TempI64, mop: MemOp) {
        let idx = self.get_mem_index();
        let lo = self.new64();
        if mop.0 & MemOp::SIZE.0 < 4 {
            self.f().gen_qemu_ld_i64(lo, addr, idx, mop);
            self.write_vreg(rt, lo, None);
        } else {
            let hi = self.new64();
            let f = self.f();
            let t = f.temp_new_i128();
            f.gen_qemu_ld_i128(t, addr, idx, mop);
            f.gen_extr_i128_i64(lo, hi, t);
            self.write_vreg(rt, lo, Some(hi));
        }
    }

    /// `do_fp_st()`: store the low bits of `rt`.
    fn fp_st(&mut self, rt: i32, addr: TempI64, mop: MemOp) {
        let idx = self.get_mem_index();
        let off = vreg_off(rt as usize);
        let lo = self.ld_env64(off);
        if mop.0 & MemOp::SIZE.0 < 4 {
            self.f().gen_qemu_st_i64(lo, addr, idx, mop);
        } else {
            let hi = self.ld_env64(off + 8);
            let f = self.f();
            let t = f.temp_new_i128();
            f.gen_concat_i64_i128(t, lo, hi);
            f.gen_qemu_st_i128(t, addr, idx, mop);
        }
    }

    fn fp_ldst(&mut self, is_load: bool, rt: i32, addr: TempI64, mop: MemOp) {
        if is_load {
            self.fp_ld(rt, addr, mop);
        } else {
            self.fp_st(rt, addr, mop);
        }
    }

    pub(super) fn ld_lit_v(&mut self, a: &arg_ldlit) -> bool {
        if self.fp_access_check() {
            let mop = self.memop_asimd(a.sz);
            let addr = self.c64(self.d.pc_curr.wrapping_add(i64::from(a.imm) as u64) as i64);
            self.fp_ld(a.rt, addr, mop);
        }
        true
    }

    pub(super) fn ldst_v_i(&mut self, a: &arg_ldst_imm, is_load: bool) -> bool {
        if self.fp_access_check() {
            let mop = self.memop_asimd(a.sz);
            let imm = i64::from(a.imm);
            let (dirty, clean) = self.addr_imm_pre(a.rn, imm, a.p != 0);
            self.fp_ldst(is_load, a.rt, clean, mop);
            self.addr_imm_post(a.rn, dirty, imm, a.w != 0, a.p != 0);
        }
        true
    }

    pub(super) fn ldst_v(&mut self, a: &arg_ldst, is_load: bool) -> bool {
        if a.opt & 2 == 0 {
            return false;
        }
        if self.fp_access_check() {
            let mop = self.memop_asimd(a.sz);
            let clean = self.addr_reg(a);
            self.fp_ldst(is_load, a.rt, clean, mop);
        }
        true
    }

    pub(super) fn ldstp_v(&mut self, a: &arg_ldstpair, is_load: bool) -> bool {
        if self.fp_access_check() {
            let offset = i64::from(a.imm) << a.sz;
            let mop = self.memop_asimd(a.sz);
            let (dirty, clean) = self.addr_imm_pre(a.rn, offset, a.p != 0);
            self.fp_ldst(is_load, a.rt, clean, mop);
            self.f().gen_addi_i64(clean, clean, 1 << a.sz);
            self.fp_ldst(is_load, a.rt2, clean, mop);
            self.addr_imm_post(a.rn, dirty, offset, a.w != 0, a.p != 0);
        }
        true
    }

    /// `do_vec_ld()` and `do_vec_st()`: one element.
    fn vec_ldst(&mut self, is_load: bool, reg: i32, e: i32, addr: TempI64, mop: MemOp) {
        let idx = self.get_mem_index();
        let esz = (mop.0 & MemOp::SIZE.0) as i32;
        if is_load {
            let t = self.new64();
            self.f().gen_qemu_ld_i64(t, addr, idx, mop);
            self.write_elem(reg, e, esz, t);
        } else {
            let t = self.read_elem(reg, e, esz, false);
            self.f().gen_qemu_st_i64(t, addr, idx, mop);
        }
    }

    /// The post-index writeback of the structure loads and stores.
    fn ldst_writeback(&mut self, rn: i32, base: TempI64, p: i32, rm: i32, total: i32) {
        if p == 0 {
            return;
        }
        if rm == 31 {
            self.f().gen_addi_i64(base, base, i64::from(total));
        } else {
            let m = self.reg(rm);
            self.f().gen_add_i64(base, base, m);
        }
        self.set_reg_sp(rn, base);
    }

    /// `trans_LD_mult()` and `trans_ST_mult()`.
    pub(super) fn ldst_mult(&mut self, a: &arg_ldst_mult, is_load: bool) -> bool {
        if a.p == 0 && a.rm != 0 {
            return false;
        }
        if a.sz == 3 && a.q == 0 && a.selem != 1 {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let total = a.rpt * a.selem * oprsz(a.q) as i32;
        let base = self.reg_sp(a.rn);
        let clean = self.clean_data_tbi(base);
        // Consecutive little endian elements from one register are loaded 64 bits at a time.
        let mut size = a.sz;
        let mut align = MemOp::ALIGN;
        if a.selem == 1 {
            align = MemOp((size as u32) << 5);
            size = 3;
        }
        if !self.d.align_mem {
            align = MemOp(0);
        }
        let mop = MemOp(size as u32) | align | MemOp::LE;
        let elements = oprsz(a.q) as i32 >> size;
        for r in 0..a.rpt {
            for e in 0..elements {
                for xs in 0..a.selem {
                    let tt = (a.rt + r + xs) % 32;
                    self.vec_ldst(is_load, tt, e, clean, mop);
                    self.f().gen_addi_i64(clean, clean, 1 << size);
                }
            }
        }
        if is_load {
            for r in 0..a.rpt * a.selem {
                if a.q == 0 {
                    self.clear_high((a.rt + r) % 32);
                } else {
                    self.clear_sve((a.rt + r) % 32);
                }
            }
        }
        self.ldst_writeback(a.rn, base, a.p, a.rm, total);
        true
    }

    /// `trans_LD_single()` and `trans_ST_single()`.
    pub(super) fn ldst_single(&mut self, a: &arg_ldst_single, is_load: bool) -> bool {
        if a.p == 0 && a.rm != 0 {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let total = a.selem << a.scale;
        let base = self.reg_sp(a.rn);
        let mop = self.memop_asimd(a.scale);
        let clean = self.clean_data_tbi(base);
        for xs in 0..a.selem {
            let rt = (a.rt + xs) % 32;
            self.vec_ldst(is_load, rt, a.index, clean, mop);
            self.f().gen_addi_i64(clean, clean, 1 << a.scale);
        }
        self.ldst_writeback(a.rn, base, a.p, a.rm, total);
        true
    }

    /// `trans_LD_single_repl()`.
    pub(super) fn ld_repl(&mut self, a: &arg_disas_a6452) -> bool {
        if a.p == 0 && a.rm != 0 {
            return false;
        }
        if !self.fp_access_check() {
            return true;
        }
        let total = a.selem << a.scale;
        let base = self.reg_sp(a.rn);
        let mop = self.memop_asimd(a.scale);
        let clean = self.clean_data_tbi(base);
        let idx = self.get_mem_index();
        for xs in 0..a.selem {
            let rt = (a.rt + xs) % 32;
            let t = self.new64();
            self.f().gen_qemu_ld_i64(t, clean, idx, mop);
            self.dup64(t, a.scale);
            self.write_dup(rt, t, a.q != 0);
            self.f().gen_addi_i64(clean, clean, 1 << a.scale);
        }
        self.ldst_writeback(a.rn, base, a.p, a.rm, total);
        true
    }
}

/// Generate the `trans_` hooks of the FP and AdvSIMD patterns inside the `DisasA64` impl:
/// each line names the hook, its argument type and the method with its extra arguments.
macro_rules! simd_trans {
    () => {
        simd::simd_trans! { @fns
            // Integer three same, vector.
            trans_ADD_v arg_qrrr_e v3(nop::ADD, Chk::Fn, Feat::None);
            trans_SUB_v arg_qrrr_e v3(nop::SUB, Chk::Fn, Feat::None);
            trans_MUL_v arg_qrrr_e v3(nop::MUL, Chk::No64, Feat::None);
            trans_MLA_v arg_qrrr_e v3(nop::MLA, Chk::No64, Feat::None);
            trans_MLS_v arg_qrrr_e v3(nop::MLS, Chk::No64, Feat::None);
            trans_SMAX_v arg_qrrr_e v3(nop::SMAX, Chk::No64, Feat::None);
            trans_SMIN_v arg_qrrr_e v3(nop::SMIN, Chk::No64, Feat::None);
            trans_UMAX_v arg_qrrr_e v3(nop::UMAX, Chk::No64, Feat::None);
            trans_UMIN_v arg_qrrr_e v3(nop::UMIN, Chk::No64, Feat::None);
            trans_SABD_v arg_qrrr_e v3(nop::SABD, Chk::No64, Feat::None);
            trans_UABD_v arg_qrrr_e v3(nop::UABD, Chk::No64, Feat::None);
            trans_SABA_v arg_qrrr_e v3(nop::SABA, Chk::No64, Feat::None);
            trans_UABA_v arg_qrrr_e v3(nop::UABA, Chk::No64, Feat::None);
            trans_SHADD_v arg_qrrr_e v3(nop::SHADD, Chk::No64, Feat::None);
            trans_UHADD_v arg_qrrr_e v3(nop::UHADD, Chk::No64, Feat::None);
            trans_SRHADD_v arg_qrrr_e v3(nop::SRHADD, Chk::No64, Feat::None);
            trans_URHADD_v arg_qrrr_e v3(nop::URHADD, Chk::No64, Feat::None);
            trans_SHSUB_v arg_qrrr_e v3(nop::SHSUB, Chk::No64, Feat::None);
            trans_UHSUB_v arg_qrrr_e v3(nop::UHSUB, Chk::No64, Feat::None);
            trans_SQADD_v arg_qrrr_e v3(nop::SQADD, Chk::Fn, Feat::None);
            trans_UQADD_v arg_qrrr_e v3(nop::UQADD, Chk::Fn, Feat::None);
            trans_SQSUB_v arg_qrrr_e v3(nop::SQSUB, Chk::Fn, Feat::None);
            trans_UQSUB_v arg_qrrr_e v3(nop::UQSUB, Chk::Fn, Feat::None);
            trans_SUQADD_v arg_qrrr_e v3acc(nop::SUQADD);
            trans_USQADD_v arg_qrrr_e v3acc(nop::USQADD);
            trans_SSHL_v arg_qrrr_e v3(nop::SSHL, Chk::Fn, Feat::None);
            trans_USHL_v arg_qrrr_e v3(nop::USHL, Chk::Fn, Feat::None);
            trans_SRSHL_v arg_qrrr_e v3(nop::SRSHL, Chk::Fn, Feat::None);
            trans_URSHL_v arg_qrrr_e v3(nop::URSHL, Chk::Fn, Feat::None);
            trans_SQSHL_v arg_qrrr_e v3(nop::SQSHL, Chk::Fn, Feat::None);
            trans_UQSHL_v arg_qrrr_e v3(nop::UQSHL, Chk::Fn, Feat::None);
            trans_SQRSHL_v arg_qrrr_e v3(nop::SQRSHL, Chk::Fn, Feat::None);
            trans_UQRSHL_v arg_qrrr_e v3(nop::UQRSHL, Chk::Fn, Feat::None);
            trans_PMUL_v arg_qrrr_e v3(nop::PMUL, Chk::Fn, Feat::None);
            trans_SQDMULH_v arg_qrrr_e v3(nop::SQDMULH, Chk::Hs, Feat::None);
            trans_SQRDMULH_v arg_qrrr_e v3(nop::SQRDMULH, Chk::Hs, Feat::None);
            trans_SQRDMLAH_v arg_qrrr_e v3(nop::SQRDMLAH, Chk::Hs, Feat::Rdm);
            trans_SQRDMLSH_v arg_qrrr_e v3(nop::SQRDMLSH, Chk::Hs, Feat::Rdm);
            trans_CMTST_v arg_qrrr_e v3(nop::CMTST, Chk::Fn, Feat::None);
            trans_CMEQ_v arg_qrrr_e v3(nop::CMEQ, Chk::Fn, Feat::None);
            trans_CMGE_v arg_qrrr_e v3(nop::CMGE, Chk::Fn, Feat::None);
            trans_CMGT_v arg_qrrr_e v3(nop::CMGT, Chk::Fn, Feat::None);
            trans_CMHI_v arg_qrrr_e v3(nop::CMHI, Chk::Fn, Feat::None);
            trans_CMHS_v arg_qrrr_e v3(nop::CMHS, Chk::Fn, Feat::None);
            trans_AND_v arg_qrrr_e v3(nop::AND, Chk::Fn, Feat::None);
            trans_BIC_v arg_qrrr_e v3(nop::BIC, Chk::Fn, Feat::None);
            trans_ORR_v arg_qrrr_e v3(nop::ORR, Chk::Fn, Feat::None);
            trans_ORN_v arg_qrrr_e v3(nop::ORN, Chk::Fn, Feat::None);
            trans_EOR_v arg_qrrr_e v3(nop::EOR, Chk::Fn, Feat::None);
            trans_BSL_v arg_qrrr_e v3(nop::BSL, Chk::Fn, Feat::None);
            trans_BIT_v arg_qrrr_e v3(nop::BIT, Chk::Fn, Feat::None);
            trans_BIF_v arg_qrrr_e v3(nop::BIF, Chk::Fn, Feat::None);
            trans_ADDP_v arg_qrrr_e v3(nop::ADDP, Chk::Fn, Feat::None);
            trans_SMAXP_v arg_qrrr_e v3(nop::SMAXP, Chk::No64, Feat::None);
            trans_SMINP_v arg_qrrr_e v3(nop::SMINP, Chk::No64, Feat::None);
            trans_UMAXP_v arg_qrrr_e v3(nop::UMAXP, Chk::No64, Feat::None);
            trans_UMINP_v arg_qrrr_e v3(nop::UMINP, Chk::No64, Feat::None);
            trans_SDOT_v arg_qrrr_e v3(nop::SDOT, Chk::None, Feat::DotProd);
            trans_UDOT_v arg_qrrr_e v3(nop::UDOT, Chk::None, Feat::DotProd);
            // Permutes.
            trans_UZP1 arg_qrrr_e v3(nop::UZP1, Chk::Fn, Feat::None);
            trans_UZP2 arg_qrrr_e v3(nop::UZP2, Chk::Fn, Feat::None);
            trans_ZIP1 arg_qrrr_e v3(nop::ZIP1, Chk::Fn, Feat::None);
            trans_ZIP2 arg_qrrr_e v3(nop::ZIP2, Chk::Fn, Feat::None);
            trans_TRN1 arg_qrrr_e v3(nop::TRN1, Chk::Fn, Feat::None);
            trans_TRN2 arg_qrrr_e v3(nop::TRN2, Chk::Fn, Feat::None);
            trans_EXT_d arg_crypto3i ext(false);
            trans_EXT_q arg_crypto3i ext(true);
            trans_TBL_TBX arg_disas_a6471 tbl();
            // Integer three same, scalar.
            trans_ADD_s arg_rrr_e s3(nop::ADD, Chk::None, Feat::None);
            trans_SUB_s arg_rrr_e s3(nop::SUB, Chk::None, Feat::None);
            trans_SQADD_s arg_rrr_e s3(nop::SQADD, Chk::None, Feat::None);
            trans_UQADD_s arg_rrr_e s3(nop::UQADD, Chk::None, Feat::None);
            trans_SQSUB_s arg_rrr_e s3(nop::SQSUB, Chk::None, Feat::None);
            trans_UQSUB_s arg_rrr_e s3(nop::UQSUB, Chk::None, Feat::None);
            trans_SUQADD_s arg_rrr_e s3acc(nop::SUQADD);
            trans_USQADD_s arg_rrr_e s3acc(nop::USQADD);
            trans_SSHL_s arg_rrr_e s3(nop::SSHL, Chk::None, Feat::None);
            trans_USHL_s arg_rrr_e s3(nop::USHL, Chk::None, Feat::None);
            trans_SRSHL_s arg_rrr_e s3(nop::SRSHL, Chk::None, Feat::None);
            trans_URSHL_s arg_rrr_e s3(nop::URSHL, Chk::None, Feat::None);
            trans_SQSHL_s arg_rrr_e s3(nop::SQSHL, Chk::None, Feat::None);
            trans_UQSHL_s arg_rrr_e s3(nop::UQSHL, Chk::None, Feat::None);
            trans_SQRSHL_s arg_rrr_e s3(nop::SQRSHL, Chk::None, Feat::None);
            trans_UQRSHL_s arg_rrr_e s3(nop::UQRSHL, Chk::None, Feat::None);
            trans_SQDMULH_s arg_rrr_e s3(nop::SQDMULH, Chk::Hs, Feat::None);
            trans_SQRDMULH_s arg_rrr_e s3(nop::SQRDMULH, Chk::Hs, Feat::None);
            trans_SQRDMLAH_s arg_rrr_e s3(nop::SQRDMLAH, Chk::Hs, Feat::Rdm);
            trans_SQRDMLSH_s arg_rrr_e s3(nop::SQRDMLSH, Chk::Hs, Feat::Rdm);
            trans_CMTST_s arg_rrr_e s3(nop::CMTST, Chk::None, Feat::None);
            trans_CMEQ_s arg_rrr_e s3(nop::CMEQ, Chk::None, Feat::None);
            trans_CMGE_s arg_rrr_e s3(nop::CMGE, Chk::None, Feat::None);
            trans_CMGT_s arg_rrr_e s3(nop::CMGT, Chk::None, Feat::None);
            trans_CMHI_s arg_rrr_e s3(nop::CMHI, Chk::None, Feat::None);
            trans_CMHS_s arg_rrr_e s3(nop::CMHS, Chk::None, Feat::None);
            trans_ADDP_s arg_rr_e sp(nop::ADDP);
            // Two register misc.
            trans_ABS_v arg_qrr_e v2(nop::ABS, Chk::Fn);
            trans_NEG_v arg_qrr_e v2(nop::NEG, Chk::Fn);
            trans_NOT_v arg_qrr_e v2(nop::NOT, Chk::Fn);
            trans_CNT_v arg_qrr_e v2(nop::CNT, Chk::Fn);
            trans_RBIT_v arg_qrr_e v2(nop::RBIT, Chk::Fn);
            trans_CLS_v arg_qrr_e v2(nop::CLS, Chk::No64);
            trans_CLZ_v arg_qrr_e v2(nop::CLZ, Chk::No64);
            trans_REV16_v arg_qrr_e v2(nop::REV16, Chk::Fn);
            trans_REV32_v arg_qrr_e v2(nop::REV32, Chk::Fn);
            trans_REV64_v arg_qrr_e v2(nop::REV64, Chk::No64);
            trans_SQABS_v arg_qrr_e v2(nop::SQABS, Chk::Fn);
            trans_SQNEG_v arg_qrr_e v2(nop::SQNEG, Chk::Fn);
            trans_CMEQ0_v arg_qrr_e v2(nop::CMEQ0, Chk::Fn);
            trans_CMGE0_v arg_qrr_e v2(nop::CMGE0, Chk::Fn);
            trans_CMGT0_v arg_qrr_e v2(nop::CMGT0, Chk::Fn);
            trans_CMLE0_v arg_qrr_e v2(nop::CMLE0, Chk::Fn);
            trans_CMLT0_v arg_qrr_e v2(nop::CMLT0, Chk::Fn);
            trans_SADDLP_v arg_qrr_e v2(nop::SADDLP, Chk::No64);
            trans_UADDLP_v arg_qrr_e v2(nop::UADDLP, Chk::No64);
            trans_SADALP_v arg_qrr_e v2(nop::SADALP, Chk::No64);
            trans_UADALP_v arg_qrr_e v2(nop::UADALP, Chk::No64);
            trans_ABS_s arg_rr s2d(nop::ABS);
            trans_NEG_s arg_rr s2d(nop::NEG);
            trans_CMEQ0_s arg_rr s2d(nop::CMEQ0);
            trans_CMGE0_s arg_rr s2d(nop::CMGE0);
            trans_CMGT0_s arg_rr s2d(nop::CMGT0);
            trans_CMLE0_s arg_rr s2d(nop::CMLE0);
            trans_CMLT0_s arg_rr s2d(nop::CMLT0);
            trans_SQABS_s arg_rr_e s2(nop::SQABS);
            trans_SQNEG_s arg_rr_e s2(nop::SQNEG);
            trans_XTN arg_qrr_e narrow_v(nop::XTN);
            trans_SQXTN_v arg_qrr_e narrow_v(nop::SQXTN);
            trans_UQXTN_v arg_qrr_e narrow_v(nop::UQXTN);
            trans_SQXTUN_v arg_qrr_e narrow_v(nop::SQXTUN);
            trans_SQXTN_s arg_rr_e narrow_s(nop::SQXTN);
            trans_UQXTN_s arg_rr_e narrow_s(nop::UQXTN);
            trans_SQXTUN_s arg_rr_e narrow_s(nop::SQXTUN);
            trans_SHLL_v arg_qrr_e shll();
            // Across lanes.
            trans_ADDV arg_qrr_e vred(nop::ADDV);
            trans_SADDLV arg_qrr_e vred(nop::SADDLV);
            trans_UADDLV arg_qrr_e vred(nop::UADDLV);
            trans_SMAXV arg_qrr_e vred(nop::SMAXV);
            trans_SMINV arg_qrr_e vred(nop::SMINV);
            trans_UMAXV arg_qrr_e vred(nop::UMAXV);
            trans_UMINV arg_qrr_e vred(nop::UMINV);
            // Shifts by immediate.
            trans_SSHR_v arg_qrri_e vsh(nop::SSHR);
            trans_USHR_v arg_qrri_e vsh(nop::USHR);
            trans_SSRA_v arg_qrri_e vsh(nop::SSRA);
            trans_USRA_v arg_qrri_e vsh(nop::USRA);
            trans_SRSHR_v arg_qrri_e vsh(nop::SRSHR);
            trans_URSHR_v arg_qrri_e vsh(nop::URSHR);
            trans_SRSRA_v arg_qrri_e vsh(nop::SRSRA);
            trans_URSRA_v arg_qrri_e vsh(nop::URSRA);
            trans_SRI_v arg_qrri_e vsh(nop::SRI);
            trans_SHL_v arg_qrri_e vsh(nop::SHL);
            trans_SLI_v arg_qrri_e vsh(nop::SLI);
            trans_SQSHL_vi arg_qrri_e vsh(nop::SQSHLI);
            trans_UQSHL_vi arg_qrri_e vsh(nop::UQSHLI);
            trans_SQSHLU_vi arg_qrri_e vsh(nop::SQSHLUI);
            trans_SSHLL_v arg_qrri_e vshll(nop::SSHLL);
            trans_USHLL_v arg_qrri_e vshll(nop::USHLL);
            trans_SHRN_v arg_qrri_e vshn(nop::SHRN);
            trans_RSHRN_v arg_qrri_e vshn(nop::RSHRN);
            trans_SQSHRN_v arg_qrri_e vshn(nop::SQSHRN);
            trans_UQSHRN_v arg_qrri_e vshn(nop::UQSHRN);
            trans_SQRSHRN_v arg_qrri_e vshn(nop::SQRSHRN);
            trans_UQRSHRN_v arg_qrri_e vshn(nop::UQRSHRN);
            trans_SQSHRUN_v arg_qrri_e vshn(nop::SQSHRUN);
            trans_SQRSHRUN_v arg_qrri_e vshn(nop::SQRSHRUN);
            trans_SSHR_s arg_rri_e ssh(nop::SSHR);
            trans_USHR_s arg_rri_e ssh(nop::USHR);
            trans_SSRA_s arg_rri_e ssh(nop::SSRA);
            trans_USRA_s arg_rri_e ssh(nop::USRA);
            trans_SRSHR_s arg_rri_e ssh(nop::SRSHR);
            trans_URSHR_s arg_rri_e ssh(nop::URSHR);
            trans_SRSRA_s arg_rri_e ssh(nop::SRSRA);
            trans_URSRA_s arg_rri_e ssh(nop::URSRA);
            trans_SRI_s arg_rri_e ssh(nop::SRI);
            trans_SHL_s arg_rri_e ssh(nop::SHL);
            trans_SLI_s arg_rri_e ssh(nop::SLI);
            trans_SQSHL_si arg_rri_e ssh(nop::SQSHLI);
            trans_UQSHL_si arg_rri_e ssh(nop::UQSHLI);
            trans_SQSHLU_si arg_rri_e ssh(nop::SQSHLUI);
            trans_SQSHRN_si arg_rri_e ssh(nop::SQSHRN);
            trans_UQSHRN_si arg_rri_e ssh(nop::UQSHRN);
            trans_SQRSHRN_si arg_rri_e ssh(nop::SQRSHRN);
            trans_UQRSHRN_si arg_rri_e ssh(nop::UQRSHRN);
            trans_SQSHRUN_si arg_rri_e ssh(nop::SQSHRUN);
            trans_SQRSHRUN_si arg_rri_e ssh(nop::SQRSHRUN);
            // Three different.
            trans_SADDL_v arg_qrrr_e wide(nop::SADDL);
            trans_UADDL_v arg_qrrr_e wide(nop::UADDL);
            trans_SSUBL_v arg_qrrr_e wide(nop::SSUBL);
            trans_USUBL_v arg_qrrr_e wide(nop::USUBL);
            trans_SADDW arg_qrrr_e wide(nop::SADDW);
            trans_UADDW arg_qrrr_e wide(nop::UADDW);
            trans_SSUBW arg_qrrr_e wide(nop::SSUBW);
            trans_USUBW arg_qrrr_e wide(nop::USUBW);
            trans_SABAL_v arg_qrrr_e wide(nop::SABAL);
            trans_UABAL_v arg_qrrr_e wide(nop::UABAL);
            trans_SABDL_v arg_qrrr_e wide(nop::SABDL);
            trans_UABDL_v arg_qrrr_e wide(nop::UABDL);
            trans_SMLAL_v arg_qrrr_e wide(nop::SMLAL);
            trans_UMLAL_v arg_qrrr_e wide(nop::UMLAL);
            trans_SMLSL_v arg_qrrr_e wide(nop::SMLSL);
            trans_UMLSL_v arg_qrrr_e wide(nop::UMLSL);
            trans_SMULL_v arg_qrrr_e wide(nop::SMULL);
            trans_UMULL_v arg_qrrr_e wide(nop::UMULL);
            trans_SQDMULL_v arg_qrrr_e wide(nop::SQDMULL);
            trans_SQDMLAL_v arg_qrrr_e wide(nop::SQDMLAL);
            trans_SQDMLSL_v arg_qrrr_e wide(nop::SQDMLSL);
            trans_PMULL_p8 arg_qrrr_e wide(nop::PMULL);
            trans_PMULL_p64 arg_qrrr_e pmull64();
            trans_ADDHN arg_qrrr_e wide(nop::ADDHN);
            trans_SUBHN arg_qrrr_e wide(nop::SUBHN);
            trans_RADDHN arg_qrrr_e wide(nop::RADDHN);
            trans_RSUBHN arg_qrrr_e wide(nop::RSUBHN);
            // Indexed.
            trans_MUL_vi arg_qrrx_e vi(nop::MUL, Feat::None);
            trans_MLA_vi arg_qrrx_e vi(nop::MLA, Feat::None);
            trans_MLS_vi arg_qrrx_e vi(nop::MLS, Feat::None);
            trans_SQDMULH_vi arg_qrrx_e vi(nop::SQDMULH, Feat::None);
            trans_SQRDMULH_vi arg_qrrx_e vi(nop::SQRDMULH, Feat::None);
            trans_SQRDMLAH_vi arg_qrrx_e vi(nop::SQRDMLAH, Feat::Rdm);
            trans_SQRDMLSH_vi arg_qrrx_e vi(nop::SQRDMLSH, Feat::Rdm);
            trans_SDOT_vi arg_qrrx_e vi(nop::SDOT, Feat::DotProd);
            trans_UDOT_vi arg_qrrx_e vi(nop::UDOT, Feat::DotProd);
            trans_SMLAL_vi arg_qrrx_e wide_vi(nop::SMLAL);
            trans_UMLAL_vi arg_qrrx_e wide_vi(nop::UMLAL);
            trans_SMLSL_vi arg_qrrx_e wide_vi(nop::SMLSL);
            trans_UMLSL_vi arg_qrrx_e wide_vi(nop::UMLSL);
            trans_SMULL_vi arg_qrrx_e wide_vi(nop::SMULL);
            trans_UMULL_vi arg_qrrx_e wide_vi(nop::UMULL);
            trans_SQDMULL_vi arg_qrrx_e wide_vi(nop::SQDMULL);
            trans_SQDMLAL_vi arg_qrrx_e wide_vi(nop::SQDMLAL);
            trans_SQDMLSL_vi arg_qrrx_e wide_vi(nop::SQDMLSL);
            trans_SQDMULH_si arg_rrx_e si(nop::SQDMULH, Feat::None);
            trans_SQRDMULH_si arg_rrx_e si(nop::SQRDMULH, Feat::None);
            trans_SQRDMLAH_si arg_rrx_e si(nop::SQRDMLAH, Feat::Rdm);
            trans_SQRDMLSH_si arg_rrx_e si(nop::SQRDMLSH, Feat::Rdm);
            trans_SQDMULL_si arg_rrx_e wide_si(nop::SQDMULL);
            trans_SQDMLAL_si arg_rrx_e wide_si(nop::SQDMLAL);
            trans_SQDMLSL_si arg_rrx_e wide_si(nop::SQDMLSL);
            // Crypto.
            trans_AESE arg_qrrr_e aes(cop::AESE);
            trans_AESD arg_qrrr_e aes(cop::AESD);
            trans_AESMC arg_qrr_e cr2(cop::AESMC, Feat::Aes);
            trans_AESIMC arg_qrr_e cr2(cop::AESIMC, Feat::Aes);
            trans_SHA1C arg_qrrr_e cr3(cop::SHA1C, Feat::Sha1);
            trans_SHA1P arg_qrrr_e cr3(cop::SHA1P, Feat::Sha1);
            trans_SHA1M arg_qrrr_e cr3(cop::SHA1M, Feat::Sha1);
            trans_SHA1SU0 arg_qrrr_e cr3(cop::SHA1SU0, Feat::Sha1);
            trans_SHA1H arg_qrr_e cr2(cop::SHA1H, Feat::Sha1);
            trans_SHA1SU1 arg_qrr_e cr2(cop::SHA1SU1, Feat::Sha1);
            trans_SHA256H arg_qrrr_e cr3(cop::SHA256H, Feat::Sha256);
            trans_SHA256H2 arg_qrrr_e cr3(cop::SHA256H2, Feat::Sha256);
            trans_SHA256SU0 arg_qrr_e cr2(cop::SHA256SU0, Feat::Sha256);
            trans_SHA256SU1 arg_qrrr_e cr3(cop::SHA256SU1, Feat::Sha256);
            // FP three same, vector.
            trans_FADD_v arg_qrrr_e f3v(fop::ADD);
            trans_FSUB_v arg_qrrr_e f3v(fop::SUB);
            trans_FMUL_v arg_qrrr_e f3v(fop::MUL);
            trans_FDIV_v arg_qrrr_e f3v(fop::DIV);
            trans_FMAX_v arg_qrrr_e f3v(fop::MAX);
            trans_FMIN_v arg_qrrr_e f3v(fop::MIN);
            trans_FMAXNM_v arg_qrrr_e f3v(fop::MAXNM);
            trans_FMINNM_v arg_qrrr_e f3v(fop::MINNM);
            trans_FMULX_v arg_qrrr_e f3v(fop::MULX);
            trans_FABD_v arg_qrrr_e f3v(fop::ABD);
            trans_FRECPS_v arg_qrrr_e f3v(fop::RECPS);
            trans_FRSQRTS_v arg_qrrr_e f3v(fop::RSQRTS);
            trans_FCMEQ_v arg_qrrr_e f3v(fop::CEQ);
            trans_FCMGE_v arg_qrrr_e f3v(fop::CGE);
            trans_FCMGT_v arg_qrrr_e f3v(fop::CGT);
            trans_FACGE_v arg_qrrr_e f3v(fop::ACGE);
            trans_FACGT_v arg_qrrr_e f3v(fop::ACGT);
            trans_FMLA_v arg_qrrr_e f3v(fop::MLA);
            trans_FMLS_v arg_qrrr_e f3v(fop::MLS);
            trans_FADDP_v arg_qrrr_e f3v(fop::ADDP);
            trans_FMAXP_v arg_qrrr_e f3v(fop::MAXP);
            trans_FMINP_v arg_qrrr_e f3v(fop::MINP);
            trans_FMAXNMP_v arg_qrrr_e f3v(fop::MAXNMP);
            trans_FMINNMP_v arg_qrrr_e f3v(fop::MINNMP);
            // FP three same, scalar.
            trans_FADD_s arg_rrr_e f3s(fop::ADD);
            trans_FSUB_s arg_rrr_e f3s(fop::SUB);
            trans_FMUL_s arg_rrr_e f3s(fop::MUL);
            trans_FDIV_s arg_rrr_e f3s(fop::DIV);
            trans_FMAX_s arg_rrr_e f3s(fop::MAX);
            trans_FMIN_s arg_rrr_e f3s(fop::MIN);
            trans_FMAXNM_s arg_rrr_e f3s(fop::MAXNM);
            trans_FMINNM_s arg_rrr_e f3s(fop::MINNM);
            trans_FMULX_s arg_rrr_e f3s(fop::MULX);
            trans_FABD_s arg_rrr_e f3s(fop::ABD);
            trans_FNMUL_s arg_rrr_e f3s(fop::NMUL);
            trans_FRECPS_s arg_rrr_e f3s(fop::RECPS);
            trans_FRSQRTS_s arg_rrr_e f3s(fop::RSQRTS);
            trans_FCMEQ_s arg_rrr_e f3s(fop::CEQ);
            trans_FCMGE_s arg_rrr_e f3s(fop::CGE);
            trans_FCMGT_s arg_rrr_e f3s(fop::CGT);
            trans_FACGE_s arg_rrr_e f3s(fop::ACGE);
            trans_FACGT_s arg_rrr_e f3s(fop::ACGT);
            trans_FMADD arg_rrrr_e fmadd(fop::MADD);
            trans_FMSUB arg_rrrr_e fmadd(fop::MSUB);
            trans_FNMADD arg_rrrr_e fmadd(fop::NMADD);
            trans_FNMSUB arg_rrrr_e fmadd(fop::NMSUB);
            trans_FADDP_s arg_rr_e fps(fop::ADDP);
            trans_FMAXP_s arg_rr_e fps(fop::MAXP);
            trans_FMINP_s arg_rr_e fps(fop::MINP);
            trans_FMAXNMP_s arg_rr_e fps(fop::MAXNMP);
            trans_FMINNMP_s arg_rr_e fps(fop::MINNMP);
            trans_FMAXV_h arg_qrr_e fred(fop::MAXV);
            trans_FMAXV_s arg_qrr_e fred(fop::MAXV);
            trans_FMINV_h arg_qrr_e fred(fop::MINV);
            trans_FMINV_s arg_qrr_e fred(fop::MINV);
            trans_FMAXNMV_h arg_qrr_e fred(fop::MAXNMV);
            trans_FMAXNMV_s arg_qrr_e fred(fop::MAXNMV);
            trans_FMINNMV_h arg_qrr_e fred(fop::MINNMV);
            trans_FMINNMV_s arg_qrr_e fred(fop::MINNMV);
            // FP indexed.
            trans_FMUL_vi arg_qrrx_e fvi(fop::MUL);
            trans_FMULX_vi arg_qrrx_e fvi(fop::MULX);
            trans_FMLA_vi arg_qrrx_e fvi(fop::MLA);
            trans_FMLS_vi arg_qrrx_e fvi(fop::MLS);
            trans_FMUL_si arg_rrx_e fsi(fop::MUL);
            trans_FMULX_si arg_rrx_e fsi(fop::MULX);
            trans_FMLA_si arg_rrx_e fsi(fop::MLA);
            trans_FMLS_si arg_rrx_e fsi(fop::MLS);
            // FP one source.
            trans_FMOV_s arg_rr_e f2s(fop::MOV, RF);
            trans_FABS_s arg_rr_e f2s(fop::ABS, RF);
            trans_FNEG_s arg_rr_e f2s(fop::NEG, RF);
            trans_FSQRT_s arg_rr_e f2s(fop::SQRT, RF);
            trans_FRINTN_s arg_rr_e f2s(fop::RINT, RN);
            trans_FRINTP_s arg_rr_e f2s(fop::RINT, RP);
            trans_FRINTM_s arg_rr_e f2s(fop::RINT, RM);
            trans_FRINTZ_s arg_rr_e f2s(fop::RINT, RZ);
            trans_FRINTA_s arg_rr_e f2s(fop::RINT, RA);
            trans_FRINTI_s arg_rr_e f2s(fop::RINT, RF);
            trans_FRINTX_s arg_rr_e f2s(fop::RINTX, RF);
            trans_FRECPE_s arg_rr_e f2s(fop::RECPE, RF);
            trans_FRSQRTE_s arg_rr_e f2s(fop::RSQRTE, RF);
            trans_FRECPX_s arg_rr_e f2s(fop::RECPX, RF);
            trans_FCMEQ0_s arg_rr_e f2s(fop::CEQ0, RF);
            trans_FCMGE0_s arg_rr_e f2s(fop::CGE0, RF);
            trans_FCMGT0_s arg_rr_e f2s(fop::CGT0, RF);
            trans_FCMLE0_s arg_rr_e f2s(fop::CLE0, RF);
            trans_FCMLT0_s arg_rr_e f2s(fop::CLT0, RF);
            trans_FABS_v arg_qrr_e f2v(fop::ABS, RF);
            trans_FNEG_v arg_qrr_e f2v(fop::NEG, RF);
            trans_FSQRT_v arg_qrr_e f2v(fop::SQRT, RF);
            trans_FRINTN_v arg_qrr_e f2v(fop::RINT, RN);
            trans_FRINTP_v arg_qrr_e f2v(fop::RINT, RP);
            trans_FRINTM_v arg_qrr_e f2v(fop::RINT, RM);
            trans_FRINTZ_v arg_qrr_e f2v(fop::RINT, RZ);
            trans_FRINTA_v arg_qrr_e f2v(fop::RINT, RA);
            trans_FRINTI_v arg_qrr_e f2v(fop::RINT, RF);
            trans_FRINTX_v arg_qrr_e f2v(fop::RINTX, RF);
            trans_FRECPE_v arg_qrr_e f2v(fop::RECPE, RF);
            trans_FRSQRTE_v arg_qrr_e f2v(fop::RSQRTE, RF);
            trans_FCMEQ0_v arg_qrr_e f2v(fop::CEQ0, RF);
            trans_FCMGE0_v arg_qrr_e f2v(fop::CGE0, RF);
            trans_FCMGT0_v arg_qrr_e f2v(fop::CGT0, RF);
            trans_FCMLE0_v arg_qrr_e f2v(fop::CLE0, RF);
            trans_FCMLT0_v arg_qrr_e f2v(fop::CLT0, RF);
            trans_URECPE_v arg_qrr_e urecpe(fop::URECPE);
            trans_URSQRTE_v arg_qrr_e urecpe(fop::URSQRTE);
            // FP conversions.
            trans_FCVT_s_ds arg_rr fcvt_s(2, 3);
            trans_FCVT_s_hs arg_rr fcvt_s(2, 1);
            trans_FCVT_s_sd arg_rr fcvt_s(3, 2);
            trans_FCVT_s_hd arg_rr fcvt_s(3, 1);
            trans_FCVT_s_sh arg_rr fcvt_s(1, 2);
            trans_FCVT_s_dh arg_rr fcvt_s(1, 3);
            trans_FCVTL_v arg_qrr_e fcvtl();
            trans_FCVTN_v arg_qrr_e fcvtn(fop::FCVTN);
            trans_FCVTXN_v arg_qrr_e fcvtn(fop::FCVTXN);
            trans_FCVTXN_s arg_rr_e fcvtxn_s();
            trans_FCVTNS_g arg_fcvt fcvt_g(true, RN);
            trans_FCVTNU_g arg_fcvt fcvt_g(false, RN);
            trans_FCVTPS_g arg_fcvt fcvt_g(true, RP);
            trans_FCVTPU_g arg_fcvt fcvt_g(false, RP);
            trans_FCVTMS_g arg_fcvt fcvt_g(true, RM);
            trans_FCVTMU_g arg_fcvt fcvt_g(false, RM);
            trans_FCVTZS_g arg_fcvt fcvt_g(true, RZ);
            trans_FCVTZU_g arg_fcvt fcvt_g(false, RZ);
            trans_FCVTAS_g arg_fcvt fcvt_g(true, RA);
            trans_FCVTAU_g arg_fcvt fcvt_g(false, RA);
            trans_FCVTNS_f arg_fcvt fcvt_f(true, RN);
            trans_FCVTNU_f arg_fcvt fcvt_f(false, RN);
            trans_FCVTPS_f arg_fcvt fcvt_f(true, RP);
            trans_FCVTPU_f arg_fcvt fcvt_f(false, RP);
            trans_FCVTMS_f arg_fcvt fcvt_f(true, RM);
            trans_FCVTMU_f arg_fcvt fcvt_f(false, RM);
            trans_FCVTZS_f arg_fcvt fcvt_f(true, RZ);
            trans_FCVTZU_f arg_fcvt fcvt_f(false, RZ);
            trans_FCVTAS_f arg_fcvt fcvt_f(true, RA);
            trans_FCVTAU_f arg_fcvt fcvt_f(false, RA);
            trans_SCVTF_g arg_fcvt cvtf_g(true);
            trans_UCVTF_g arg_fcvt cvtf_g(false);
            trans_SCVTF_f arg_fcvt cvtf_f(true);
            trans_UCVTF_f arg_fcvt cvtf_f(false);
            trans_FCVTNS_vi arg_qrr_e f2v(fop::TOSINT, RN);
            trans_FCVTNU_vi arg_qrr_e f2v(fop::TOUINT, RN);
            trans_FCVTPS_vi arg_qrr_e f2v(fop::TOSINT, RP);
            trans_FCVTPU_vi arg_qrr_e f2v(fop::TOUINT, RP);
            trans_FCVTMS_vi arg_qrr_e f2v(fop::TOSINT, RM);
            trans_FCVTMU_vi arg_qrr_e f2v(fop::TOUINT, RM);
            trans_FCVTZS_vi arg_qrr_e f2v(fop::TOSINT, RZ);
            trans_FCVTZU_vi arg_qrr_e f2v(fop::TOUINT, RZ);
            trans_FCVTAS_vi arg_qrr_e f2v(fop::TOSINT, RA);
            trans_FCVTAU_vi arg_qrr_e f2v(fop::TOUINT, RA);
            trans_SCVTF_vi arg_qrr_e f2v(fop::SCVTF, RF);
            trans_UCVTF_vi arg_qrr_e f2v(fop::UCVTF, RF);
            trans_FCVTZS_vf arg_fcvt_q cvt_vf(fop::TOSINT);
            trans_FCVTZU_vf arg_fcvt_q cvt_vf(fop::TOUINT);
            trans_SCVTF_vf arg_fcvt_q cvt_vf(fop::SCVTF);
            trans_UCVTF_vf arg_fcvt_q cvt_vf(fop::UCVTF);
            // FP compares, selects, moves and immediates.
            trans_FCMP arg_disas_a6474 fcmp();
            trans_FCCMP arg_disas_a6475 fccmp();
            trans_FCSEL arg_disas_a6470 fcsel();
            trans_FMOV_hx arg_rr fmov_g(Mov::Hx);
            trans_FMOV_sw arg_rr fmov_g(Mov::Sw);
            trans_FMOV_dx arg_rr fmov_g(Mov::Dx);
            trans_FMOV_ux arg_rr fmov_g(Mov::Ux);
            trans_FMOV_xh arg_rr fmov_g(Mov::Xh);
            trans_FMOV_ws arg_rr fmov_g(Mov::Ws);
            trans_FMOV_xd arg_rr fmov_g(Mov::Xd);
            trans_FMOV_xu arg_rr fmov_g(Mov::Xu);
            trans_FMOVI_s arg_disas_a6473 fmovi_s();
            trans_FMOVI_v_h arg_disas_a6476 fmovi_vh();
            trans_Vimm arg_disas_a6477 vimm();
            // Copies.
            trans_DUP_element_s arg_disas_a6465 dup_s();
            trans_DUP_element_v arg_disas_a6466 dup_v();
            trans_DUP_general arg_disas_a6466 dup_g();
            trans_INS_general arg_disas_a6465 ins_g();
            trans_INS_element arg_disas_a6467 ins_e();
            trans_SMOV arg_disas_a6466 smov_umov(true);
            trans_UMOV arg_disas_a6466 smov_umov(false);
            // Loads and stores.
            trans_LD_lit_v arg_ldlit ld_lit_v();
            trans_LDR_v_i arg_ldst_imm ldst_v_i(true);
            trans_STR_v_i arg_ldst_imm ldst_v_i(false);
            trans_LDR_v arg_ldst ldst_v(true);
            trans_STR_v arg_ldst ldst_v(false);
            trans_LDP_v arg_ldstpair ldstp_v(true);
            trans_STP_v arg_ldstpair ldstp_v(false);
            trans_LD_mult arg_ldst_mult ldst_mult(true);
            trans_ST_mult arg_ldst_mult ldst_mult(false);
            trans_LD_single arg_ldst_single ldst_single(true);
            trans_ST_single arg_ldst_single ldst_single(false);
            trans_LD_single_repl arg_disas_a6452 ld_repl();
        }
    };
    (@fns $($name:ident $ty:ident $m:ident($($arg:expr),*);)*) => {
        $(
            fn $name(&mut self, a: &mut decode::$ty) -> bool {
                self.$m(a, $($arg),*)
            }
        )*
    };
}

pub(super) use simd_trans;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn imm_const() {
        // MOVI Vd.4S, #0xab, LSL #8.
        assert_eq!(asimd_imm_const(0xab, 2, 0), 0x0000_ab00_0000_ab00);
        // MVNI: inverted.
        assert_eq!(asimd_imm_const(0xab, 2, 1), 0xffff_54ff_ffff_54ff);
        // MOVI Dd, #mask.
        assert_eq!(asimd_imm_const(0x81, 14, 1), 0xff00_0000_0000_00ff);
        // FMOV Vd.2D, #1.0.
        assert_eq!(asimd_imm_const(0x70, 15, 1), 0x3ff0_0000_0000_0000);
        // FMOV Vd.4S, #1.0.
        assert_eq!(asimd_imm_const(0x70, 15, 0), 0x3f80_0000_3f80_0000);
        assert_eq!(dup_const(1, 0x3c00), 0x3c00_3c00_3c00_3c00);
        assert_eq!(decode_esz_idx(0b10110), Some((1, 0b101)));
        assert_eq!(decode_esz_idx(0), None);
    }
}
