[package]
name = "ruvm-decode"
description = "A generator that turns QEMU decodetree files into Rust decoders."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[lib]
path = "src/lib.rs"

[[bin]]
name = "ruvm-decodetree"
path = "src/main.rs"

[dependencies]

[lints]
workspace = true
