// SPDX-License-Identifier: GPL-2.0-or-later

//! The vector opcode tables of `decode-new.c.inc`, generated by
//! `tests/data/gen_sse_tab.py`. Do not edit by hand.

use super::sse::flags::*;
use super::sse::{E, E0, T, Z, e};

/// The emitters, QEMU's `gen_*` functions.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum G {
    None,
    Blendvpd,
    Blendvps,
    Cmpccxadd,
    Cvtpi2px,
    Cvtpx2pi,
    Cvttpx2pi,
    Emms,
    ExtrqI,
    ExtrqR,
    InsertqI,
    InsertqR,
    Maskmov,
    MovdFrom,
    MovdTo,
    Movdq,
    Movmsk,
    Movq,
    MovqDq,
    Pabsb,
    Pabsd,
    Pabsw,
    Packssdw,
    Packsswb,
    Packuswb,
    Paddb,
    Paddd,
    Paddq,
    Paddsb,
    Paddsw,
    Paddusb,
    Paddusw,
    Paddw,
    Palignr,
    Pand,
    Pandn,
    Pavgb,
    Pavgw,
    Pblendvb,
    Pclmulqdq,
    Pcmpeqb,
    Pcmpeqd,
    Pcmpeqq,
    Pcmpeqw,
    Pcmpestri,
    Pcmpestrm,
    Pcmpgtb,
    Pcmpgtd,
    Pcmpgtq,
    Pcmpgtw,
    Pcmpistri,
    Pcmpistrm,
    Pextr,
    Pextrb,
    Pextrw,
    Phaddd,
    Phaddsw,
    Phaddw,
    Phsubd,
    Phsubsw,
    Phsubw,
    Pinsr,
    Pinsrb,
    Pinsrw,
    Pmaddubsw,
    Pmaddwd,
    Pmaxsb,
    Pmaxsd,
    Pmaxsw,
    Pmaxub,
    Pmaxud,
    Pmaxuw,
    Pminsb,
    Pminsd,
    Pminsw,
    Pminub,
    Pminud,
    Pminuw,
    Pmovmskb,
    Pmuldq,
    Pmulhrsw,
    Pmulhuw,
    Pmulhw,
    Pmulld,
    Pmullw,
    Pmuludq,
    Por,
    Psadbw,
    Pshufb,
    Pshufd,
    Pshufhw,
    Pshuflw,
    Pshufw,
    Psignb,
    Psignd,
    Psignw,
    PslldI,
    PslldR,
    PslldqI,
    PsllqI,
    PsllqR,
    PsllwI,
    PsllwR,
    PsradI,
    PsradR,
    PsrawI,
    PsrawR,
    PsrldI,
    PsrldR,
    PsrldqI,
    PsrlqI,
    PsrlqR,
    PsrlwI,
    PsrlwR,
    Psubb,
    Psubd,
    Psubq,
    Psubsb,
    Psubsw,
    Psubusb,
    Psubusw,
    Psubw,
    Punpckhbw,
    Punpckhdq,
    Punpckhqdq,
    Punpckhwd,
    Punpcklbw,
    Punpckldq,
    Punpcklqdq,
    Punpcklwd,
    Pxor,
    Rorx,
    Sha1msg1,
    Sha1msg2,
    Sha1nexte,
    Sha1rnds4,
    Sha256msg1,
    Sha256msg2,
    Sha256rnds2,
    Vadd,
    Vaddsub,
    Vaesdec,
    Vaesdeclast,
    Vaesenc,
    Vaesenclast,
    Vaesimc,
    Vaeskeygen,
    Vblendpd,
    Vblendps,
    Vblendvpd,
    Vblendvps,
    Vbroadcastx128,
    Vcmp,
    Vcomi,
    Vcvtdq2pd,
    Vcvtdq2ps,
    Vcvtpd2dq,
    Vcvtpd2ps,
    Vcvtph2ps,
    Vcvtps2dq,
    Vcvtps2pd,
    Vcvtps2ph,
    Vcvtsd2ss,
    Vcvtsi2sx,
    Vcvtss2sd,
    Vcvtsx2si,
    Vcvttpd2dq,
    Vcvttps2dq,
    Vcvttsx2si,
    Vdiv,
    Vdppd,
    Vdpps,
    Vextractps,
    Vextractx128,
    Vfmadd132px,
    Vfmadd132sx,
    Vfmadd213px,
    Vfmadd213sx,
    Vfmadd231px,
    Vfmadd231sx,
    Vfmaddsub132px,
    Vfmaddsub213px,
    Vfmaddsub231px,
    Vfmsub132px,
    Vfmsub132sx,
    Vfmsub213px,
    Vfmsub213sx,
    Vfmsub231px,
    Vfmsub231sx,
    Vfmsubadd132px,
    Vfmsubadd213px,
    Vfmsubadd231px,
    Vfnmadd132px,
    Vfnmadd132sx,
    Vfnmadd213px,
    Vfnmadd213sx,
    Vfnmadd231px,
    Vfnmadd231sx,
    Vfnmsub132px,
    Vfnmsub132sx,
    Vfnmsub213px,
    Vfnmsub213sx,
    Vfnmsub231px,
    Vfnmsub231sx,
    Vhadd,
    Vhsub,
    VinsertpsM,
    VinsertpsR,
    Vinsertx128,
    Vmaskmovpd,
    VmaskmovpdSt,
    Vmaskmovps,
    VmaskmovpsSt,
    Vmax,
    Vmin,
    Vmovddup,
    Vmovhlps,
    Vmovhpx,
    VmovhpxLd,
    VmovhpxSt,
    Vmovlhps,
    Vmovlpx,
    VmovlpxLd,
    VmovlpxSt,
    VmovsdLd,
    Vmovshdup,
    Vmovsldup,
    Vmovss,
    VmovssLd,
    VmovssSt,
    Vmpsadbw,
    Vmul,
    Vpackusdw,
    Vpblendvb,
    Vpblendw,
    Vpbroadcastb,
    Vpbroadcastd,
    Vpbroadcastq,
    Vpbroadcastw,
    Vperm2x128,
    Vpermd,
    Vpermilpd,
    VpermilpdI,
    Vpermilps,
    VpermilpsI,
    Vpermq,
    Vpgatherd,
    Vpgatherq,
    Vphminposuw,
    Vpmaskmov,
    VpmaskmovSt,
    Vpmovsxbd,
    Vpmovsxbq,
    Vpmovsxbw,
    Vpmovsxdq,
    Vpmovsxwd,
    Vpmovsxwq,
    Vpmovzxbd,
    Vpmovzxbq,
    Vpmovzxbw,
    Vpmovzxdq,
    Vpmovzxwd,
    Vpmovzxwq,
    Vpsllv,
    Vpsrav,
    Vpsrlv,
    Vptest,
    Vrcp,
    Vroundpd,
    Vroundps,
    Vroundsd,
    Vroundss,
    Vrsqrt,
    Vshuf,
    Vsqrt,
    Vsub,
    Vtestpd,
    Vtestps,
    Vucomi,
    Vunpckhpx,
    Vunpcklpx,
    Vzeroall,
    Vzeroupper,
}

/// The decoders, QEMU's `decode_*` functions.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Dec {
    None,
    D0f10,
    D0f11,
    D0f12,
    D0f16,
    D0f2a,
    D0f2b,
    D0f2c,
    D0f2d,
    D0f5a,
    D0f5b,
    D0f6f,
    D0f70,
    D0f77,
    D0f78,
    D0f79,
    D0f7e,
    D0f7f,
    D0fd6,
    D0fe6,
    Group12,
    Group13,
    Group14,
    SseUnary,
    Vinsertps,
    Vxcomisx,
}

/// The CPUID features, `X86CPUIDFeature`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Ft {
    None,
    Aes,
    Avx,
    Avx2,
    Bmi2,
    Cmpccxadd,
    F16c,
    Fma,
    Pclmulqdq,
    ShaNi,
    Sse3,
    Sse41,
    Sse42,
    Sse4a,
    Ssse3,
}

pub(super) static GROUP12: [E; 8] = [
    // 0x00
    E0,
    // 0x01
    E0,
    // 0x02
    e(
        G::PsrlwI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x03
    E0,
    // 0x04
    e(
        G::PsrawI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x05
    E0,
    // 0x06
    e(
        G::PsllwI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x07
    E0,
];

pub(super) static GROUP13: [E; 8] = [
    // 0x00
    E0,
    // 0x01
    E0,
    // 0x02
    e(
        G::PsrldI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x03
    E0,
    // 0x04
    e(
        G::PsradI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x05
    E0,
    // 0x06
    e(
        G::PslldI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x07
    E0,
];

pub(super) static GROUP14: [E; 8] = [
    // 0x00
    E0,
    // 0x01
    E0,
    // 0x02
    e(
        G::PsrlqI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x03
    e(
        G::PsrldqI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | P_66,
        Ft::None,
    ),
    // 0x04
    E0,
    // 0x05
    E0,
    // 0x06
    e(
        G::PsllqI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x07
    e(
        G::PslldqI,
        Dec::None,
        [T::H, T::U, T::I],
        [Z::X, Z::X, Z::B],
        VEX7 | AVX2_256 | P_66,
        Ft::None,
    ),
];

pub(super) static OPCODES_0F6F: [E; 4] = [
    // 0x00
    e(G::Movdq, Dec::None, [T::P, T::None, T::Q], [Z::Q, Z::None, Z::Q], VEX5 | MMX, Ft::None),
    // 0x01
    e(G::Movdq, Dec::None, [T::V, T::None, T::W], [Z::X, Z::None, Z::X], VEX1, Ft::None),
    // 0x02
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x03
    E0,
];

pub(super) static OPCODES_0F70: [E; 4] = [
    // 0x00
    e(G::Pshufw, Dec::None, [T::P, T::Q, T::I], [Z::Q, Z::Q, Z::B], VEX4 | MMX, Ft::None),
    // 0x01
    e(G::Pshufd, Dec::None, [T::V, T::W, T::I], [Z::X, Z::X, Z::B], VEX4 | AVX2_256, Ft::None),
    // 0x02
    e(G::Pshufhw, Dec::None, [T::V, T::W, T::I], [Z::X, Z::X, Z::B], VEX4 | AVX2_256, Ft::None),
    // 0x03
    e(G::Pshuflw, Dec::None, [T::V, T::W, T::I], [Z::X, Z::X, Z::B], VEX4 | AVX2_256, Ft::None),
];

pub(super) static OPCODES_0F78: [E; 4] = [
    // 0x00
    E0,
    // 0x01
    e(G::ExtrqI, Dec::None, [T::V, T::None, T::I], [Z::X, Z::None, Z::W], 0, Ft::Sse4a),
    // 0x02
    E0,
    // 0x03
    e(G::InsertqI, Dec::None, [T::V, T::U, T::I], [Z::X, Z::X, Z::W], 0, Ft::Sse4a),
];

pub(super) static OPCODES_0F7E: [E; 4] = [
    // 0x00
    e(G::MovdFrom, Dec::None, [T::E, T::None, T::P], [Z::Y, Z::None, Z::Y], VEX5 | MMX, Ft::None),
    // 0x01
    e(G::MovdFrom, Dec::None, [T::E, T::None, T::V], [Z::Y, Z::None, Z::Y], VEX5, Ft::None),
    // 0x02
    e(G::Movq, Dec::None, [T::V, T::None, T::W], [Z::Dq, Z::None, Z::Q], VEX5, Ft::None),
    // 0x03
    E0,
];

pub(super) static OPCODES_0F7F: [E; 4] = [
    // 0x00
    e(G::Movdq, Dec::None, [T::W, T::None, T::V], [Z::X, Z::None, Z::X], VEX5 | MMX, Ft::None),
    // 0x01
    e(G::Movdq, Dec::None, [T::W, T::None, T::V], [Z::X, Z::None, Z::X], VEX1, Ft::None),
    // 0x02
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x03
    E0,
];

pub(super) static OPCODES_0FD6: [E; 4] = [
    // 0x00
    E0,
    // 0x01
    e(G::Movq, Dec::None, [T::W, T::None, T::V], [Z::Dq, Z::None, Z::Q], VEX5, Ft::None),
    // 0x02
    e(G::MovqDq, Dec::None, [T::V, T::None, T::N], [Z::Dq, Z::None, Z::Q], 0, Ft::None),
    // 0x03
    e(G::MovqDq, Dec::None, [T::P, T::None, T::U], [Z::Q, Z::None, Z::Q], 0, Ft::None),
];

pub(super) static OPCODES_0F38: [E; 240] = [
    // 0x00
    e(
        G::Pshufb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x01
    e(
        G::Phaddw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x02
    e(
        G::Phaddd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x03
    e(
        G::Phaddsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x04
    e(
        G::Pmaddubsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x05
    e(
        G::Phsubw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x06
    e(
        G::Phsubd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x07
    e(
        G::Phsubsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x08
    e(
        G::Psignb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x09
    e(
        G::Psignw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x0a
    e(
        G::Psignd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x0b
    e(
        G::Pmulhrsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x0c
    e(
        G::Vpermilps,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x0d
    e(
        G::Vpermilpd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x0e
    e(
        G::Vtestps,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x0f
    e(
        G::Vtestpd,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x10
    e(
        G::Pblendvb,
        Dec::None,
        [T::V, T::Op0, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x11
    E0,
    // 0x12
    E0,
    // 0x13
    e(
        G::Vcvtph2ps,
        Dec::None,
        [T::V, T::Op0, T::W],
        [Z::X, Z::X, Z::Xh],
        VEX11 | CHK_W0 | P_66,
        Ft::F16c,
    ),
    // 0x14
    e(G::Blendvps, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Sse41),
    // 0x15
    e(G::Blendvpd, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Sse41),
    // 0x16
    e(
        G::Vpermd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Qq],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x17
    e(G::Vptest, Dec::None, [T::None, T::V, T::W], [Z::None, Z::X, Z::X], VEX4 | P_66, Ft::Sse41),
    // 0x18
    e(
        G::Vpbroadcastd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x19
    e(
        G::Vpbroadcastq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::Qq, Z::None, Z::Q],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x1a
    e(
        G::Vbroadcastx128,
        Dec::None,
        [T::V, T::None, T::Wm],
        [Z::Qq, Z::None, Z::Dq],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x1b
    E0,
    // 0x1c
    e(
        G::Pabsb,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x1d
    e(
        G::Pabsw,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x1e
    e(
        G::Pabsd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::Ssse3,
    ),
    // 0x1f
    E0,
    // 0x20
    e(
        G::Vpmovsxbw,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x21
    e(
        G::Vpmovsxbd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x22
    e(
        G::Vpmovsxbq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::W],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x23
    e(
        G::Vpmovsxwd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x24
    e(
        G::Vpmovsxwq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x25
    e(
        G::Vpmovsxdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x26
    E0,
    // 0x27
    E0,
    // 0x28
    e(
        G::Pmuldq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x29
    e(
        G::Pcmpeqq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x2a
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::Wm],
        [Z::X, Z::None, Z::X],
        VEX1 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x2b
    e(
        G::Vpackusdw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x2c
    e(
        G::Vmaskmovps,
        Dec::None,
        [T::V, T::H, T::Wm],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x2d
    e(
        G::Vmaskmovpd,
        Dec::None,
        [T::V, T::H, T::Wm],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x2e
    e(
        G::VmaskmovpsSt,
        Dec::None,
        [T::M, T::V, T::H],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x2f
    e(
        G::VmaskmovpdSt,
        Dec::None,
        [T::M, T::V, T::H],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x30
    e(
        G::Vpmovzxbw,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x31
    e(
        G::Vpmovzxbd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x32
    e(
        G::Vpmovzxbq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::W],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x33
    e(
        G::Vpmovzxwd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x34
    e(
        G::Vpmovzxwq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x35
    e(
        G::Vpmovzxdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX5 | AVX2_256 | AVX_MOVX | P_66,
        Ft::Sse41,
    ),
    // 0x36
    e(
        G::Vpermd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Qq],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x37
    e(
        G::Pcmpgtq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse42,
    ),
    // 0x38
    e(
        G::Pminsb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x39
    e(
        G::Pminsd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3a
    e(
        G::Pminuw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3b
    e(
        G::Pminud,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3c
    e(
        G::Pmaxsb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3d
    e(
        G::Pmaxsd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3e
    e(
        G::Pmaxuw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x3f
    e(
        G::Pmaxud,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x40
    e(
        G::Pmulld,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::Sse41,
    ),
    // 0x41
    e(
        G::Vphminposuw,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::Dq, Z::None, Z::Dq],
        VEX4 | P_66,
        Ft::Sse41,
    ),
    // 0x42
    E0,
    // 0x43
    E0,
    // 0x44
    E0,
    // 0x45
    e(G::Vpsrlv, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Avx2),
    // 0x46
    e(G::Vpsrav, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | CHK_W0 | P_66, Ft::Avx2),
    // 0x47
    e(G::Vpsllv, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Avx2),
    // 0x48
    E0,
    // 0x49
    E0,
    // 0x4a
    E0,
    // 0x4b
    E0,
    // 0x4c
    E0,
    // 0x4d
    E0,
    // 0x4e
    E0,
    // 0x4f
    E0,
    // 0x50
    E0,
    // 0x51
    E0,
    // 0x52
    E0,
    // 0x53
    E0,
    // 0x54
    E0,
    // 0x55
    E0,
    // 0x56
    E0,
    // 0x57
    E0,
    // 0x58
    e(
        G::Vpbroadcastd,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::D],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x59
    e(
        G::Vpbroadcastq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::Q],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x5a
    e(
        G::Vbroadcastx128,
        Dec::None,
        [T::V, T::None, T::Wm],
        [Z::Qq, Z::None, Z::Dq],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x5b
    E0,
    // 0x5c
    E0,
    // 0x5d
    E0,
    // 0x5e
    E0,
    // 0x5f
    E0,
    // 0x60
    E0,
    // 0x61
    E0,
    // 0x62
    E0,
    // 0x63
    E0,
    // 0x64
    E0,
    // 0x65
    E0,
    // 0x66
    E0,
    // 0x67
    E0,
    // 0x68
    E0,
    // 0x69
    E0,
    // 0x6a
    E0,
    // 0x6b
    E0,
    // 0x6c
    E0,
    // 0x6d
    E0,
    // 0x6e
    E0,
    // 0x6f
    E0,
    // 0x70
    E0,
    // 0x71
    E0,
    // 0x72
    E0,
    // 0x73
    E0,
    // 0x74
    E0,
    // 0x75
    E0,
    // 0x76
    E0,
    // 0x77
    E0,
    // 0x78
    e(
        G::Vpbroadcastb,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::B],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x79
    e(
        G::Vpbroadcastw,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::W],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x7a
    E0,
    // 0x7b
    E0,
    // 0x7c
    E0,
    // 0x7d
    E0,
    // 0x7e
    E0,
    // 0x7f
    E0,
    // 0x80
    E0,
    // 0x81
    E0,
    // 0x82
    E0,
    // 0x83
    E0,
    // 0x84
    E0,
    // 0x85
    E0,
    // 0x86
    E0,
    // 0x87
    E0,
    // 0x88
    E0,
    // 0x89
    E0,
    // 0x8a
    E0,
    // 0x8b
    E0,
    // 0x8c
    e(G::Vpmaskmov, Dec::None, [T::V, T::H, T::Wm], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Avx2),
    // 0x8d
    E0,
    // 0x8e
    e(G::VpmaskmovSt, Dec::None, [T::M, T::V, T::H], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Avx2),
    // 0x8f
    E0,
    // 0x90
    e(G::Vpgatherd, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::D], VEX12 | P_66, Ft::Avx2),
    // 0x91
    e(G::Vpgatherq, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::Q], VEX12 | P_66, Ft::Avx2),
    // 0x92
    e(G::Vpgatherd, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::D], VEX12 | P_66, Ft::Avx2),
    // 0x93
    e(G::Vpgatherq, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::Q], VEX12 | P_66, Ft::Avx2),
    // 0x94
    E0,
    // 0x95
    E0,
    // 0x96
    e(G::Vfmaddsub132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x97
    e(G::Vfmsubadd132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x98
    e(G::Vfmadd132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x99
    e(G::Vfmadd132sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9a
    e(G::Vfmsub132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9b
    e(G::Vfmsub132sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9c
    e(G::Vfnmadd132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9d
    e(G::Vfnmadd132sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9e
    e(G::Vfnmsub132px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0x9f
    e(G::Vfnmsub132sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xa0
    E0,
    // 0xa1
    E0,
    // 0xa2
    E0,
    // 0xa3
    E0,
    // 0xa4
    E0,
    // 0xa5
    E0,
    // 0xa6
    e(G::Vfmaddsub213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xa7
    e(G::Vfmsubadd213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xa8
    e(G::Vfmadd213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xa9
    e(G::Vfmadd213sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xaa
    e(G::Vfmsub213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xab
    e(G::Vfmsub213sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xac
    e(G::Vfnmadd213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xad
    e(G::Vfnmadd213sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xae
    e(G::Vfnmsub213px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xaf
    e(G::Vfnmsub213sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xb0
    E0,
    // 0xb1
    E0,
    // 0xb2
    E0,
    // 0xb3
    E0,
    // 0xb4
    E0,
    // 0xb5
    E0,
    // 0xb6
    e(G::Vfmaddsub231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xb7
    e(G::Vfmsubadd231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xb8
    e(G::Vfmadd231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xb9
    e(G::Vfmadd231sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xba
    e(G::Vfmsub231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xbb
    e(G::Vfmsub231sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xbc
    e(G::Vfnmadd231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xbd
    e(G::Vfnmadd231sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xbe
    e(G::Vfnmsub231px, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xbf
    e(G::Vfnmsub231sx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX6 | P_66, Ft::Fma),
    // 0xc0
    E0,
    // 0xc1
    E0,
    // 0xc2
    E0,
    // 0xc3
    E0,
    // 0xc4
    E0,
    // 0xc5
    E0,
    // 0xc6
    E0,
    // 0xc7
    E0,
    // 0xc8
    e(G::Sha1nexte, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xc9
    e(G::Sha1msg1, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xca
    e(G::Sha1msg2, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xcb
    e(G::Sha256rnds2, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xcc
    e(G::Sha256msg1, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xcd
    e(G::Sha256msg2, Dec::None, [T::V, T::Op0, T::W], [Z::Dq, Z::Dq, Z::Dq], 0, Ft::ShaNi),
    // 0xce
    E0,
    // 0xcf
    E0,
    // 0xd0
    E0,
    // 0xd1
    E0,
    // 0xd2
    E0,
    // 0xd3
    E0,
    // 0xd4
    E0,
    // 0xd5
    E0,
    // 0xd6
    E0,
    // 0xd7
    E0,
    // 0xd8
    E0,
    // 0xd9
    E0,
    // 0xda
    E0,
    // 0xdb
    e(G::Vaesimc, Dec::None, [T::V, T::None, T::W], [Z::Dq, Z::None, Z::Dq], VEX4 | P_66, Ft::Aes),
    // 0xdc
    e(G::Vaesenc, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Aes),
    // 0xdd
    e(G::Vaesenclast, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Aes),
    // 0xde
    e(G::Vaesdec, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Aes),
    // 0xdf
    e(G::Vaesdeclast, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66, Ft::Aes),
    // 0xe0
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe1
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe2
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe3
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe4
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe5
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe6
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe7
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe8
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xe9
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xea
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xeb
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xec
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xed
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xee
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
    // 0xef
    e(
        G::Cmpccxadd,
        Dec::None,
        [T::M, T::G, T::B],
        [Z::Y, Z::Y, Z::Y],
        VEX13 | XCHG | CHK_O64 | P_66,
        Ft::Cmpccxadd,
    ),
];

pub(super) const VINSERTPS_REG: E = e(
    G::VinsertpsR,
    Dec::None,
    [T::V, T::H, T::U],
    [Z::Dq, Z::Dq, Z::Dq],
    VEX5 | P_66 | OP3,
    Ft::Sse41,
);

pub(super) const VINSERTPS_MEM: E = e(
    G::VinsertpsM,
    Dec::None,
    [T::V, T::H, T::M],
    [Z::Dq, Z::Dq, Z::D],
    VEX5 | P_66 | OP3,
    Ft::Sse41,
);

pub(super) static OPCODES_0F3A: [E; 256] = [
    // 0x00
    e(
        G::Vpermq,
        Dec::None,
        [T::V, T::W, T::I],
        [Z::Qq, Z::Qq, Z::B],
        VEX6 | CHK_W1 | P_66,
        Ft::Avx2,
    ),
    // 0x01
    e(
        G::Vpermq,
        Dec::None,
        [T::V, T::W, T::I],
        [Z::Qq, Z::Qq, Z::B],
        VEX6 | CHK_W1 | P_66,
        Ft::Avx2,
    ),
    // 0x02
    e(
        G::Vblendps,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx2,
    ),
    // 0x03
    E0,
    // 0x04
    e(
        G::VpermilpsI,
        Dec::None,
        [T::V, T::W, T::I],
        [Z::X, Z::X, Z::B],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x05
    e(
        G::VpermilpdI,
        Dec::None,
        [T::V, T::W, T::I],
        [Z::X, Z::X, Z::B],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x06
    e(
        G::Vperm2x128,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Qq],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx,
    ),
    // 0x07
    E0,
    // 0x08
    e(G::Vroundps, Dec::None, [T::V, T::W, T::I], [Z::X, Z::X, Z::B], VEX2 | P_66, Ft::Sse41),
    // 0x09
    e(G::Vroundpd, Dec::None, [T::V, T::W, T::I], [Z::X, Z::X, Z::B], VEX2 | P_66, Ft::Sse41),
    // 0x0a
    e(
        G::Vroundss,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::Ss],
        VEX3 | P_66 | OP3,
        Ft::Sse41,
    ),
    // 0x0b
    e(
        G::Vroundsd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::Sd],
        VEX3 | P_66 | OP3,
        Ft::Sse41,
    ),
    // 0x0c
    e(G::Vblendps, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66 | OP3, Ft::Sse41),
    // 0x0d
    e(G::Vblendpd, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_66 | OP3, Ft::Sse41),
    // 0x0e
    e(
        G::Vpblendw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66 | OP3,
        Ft::Sse41,
    ),
    // 0x0f
    e(
        G::Palignr,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66 | OP3,
        Ft::Ssse3,
    ),
    // 0x10
    E0,
    // 0x11
    E0,
    // 0x12
    E0,
    // 0x13
    E0,
    // 0x14
    e(
        G::Pextrb,
        Dec::None,
        [T::E, T::V, T::I],
        [Z::B, Z::Dq, Z::B],
        VEX5 | OP0_RD | P_66,
        Ft::Sse41,
    ),
    // 0x15
    e(
        G::Pextrw,
        Dec::None,
        [T::E, T::V, T::I],
        [Z::W, Z::Dq, Z::B],
        VEX5 | OP0_RD | P_66,
        Ft::Sse41,
    ),
    // 0x16
    e(G::Pextr, Dec::None, [T::E, T::V, T::I], [Z::Y, Z::Dq, Z::B], VEX5 | P_66, Ft::Sse41),
    // 0x17
    e(G::Vextractps, Dec::None, [T::E, T::V, T::I], [Z::D, Z::Dq, Z::B], VEX5 | P_66, Ft::Sse41),
    // 0x18
    e(
        G::Vinsertx128,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Dq],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx,
    ),
    // 0x19
    e(
        G::Vextractx128,
        Dec::None,
        [T::W, T::V, T::I],
        [Z::Dq, Z::Qq, Z::B],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx,
    ),
    // 0x1a
    E0,
    // 0x1b
    E0,
    // 0x1c
    E0,
    // 0x1d
    e(
        G::Vcvtps2ph,
        Dec::None,
        [T::W, T::V, T::I],
        [Z::Xh, Z::X, Z::B],
        VEX11 | CHK_W0 | P_66,
        Ft::F16c,
    ),
    // 0x1e
    E0,
    // 0x1f
    E0,
    // 0x20
    e(
        G::Pinsrb,
        Dec::None,
        [T::V, T::H, T::E],
        [Z::Dq, Z::Dq, Z::B],
        VEX5 | OP2_RY | P_66 | OP3,
        Ft::Sse41,
    ),
    // 0x21
    e(
        G::None,
        Dec::Vinsertps,
        [T::None, T::None, T::None],
        [Z::None, Z::None, Z::None],
        0,
        Ft::None,
    ),
    // 0x22
    e(G::Pinsr, Dec::None, [T::V, T::H, T::E], [Z::Dq, Z::Dq, Z::Y], VEX5 | P_66 | OP3, Ft::Sse41),
    // 0x23
    E0,
    // 0x24
    E0,
    // 0x25
    E0,
    // 0x26
    E0,
    // 0x27
    E0,
    // 0x28
    E0,
    // 0x29
    E0,
    // 0x2a
    E0,
    // 0x2b
    E0,
    // 0x2c
    E0,
    // 0x2d
    E0,
    // 0x2e
    E0,
    // 0x2f
    E0,
    // 0x30
    E0,
    // 0x31
    E0,
    // 0x32
    E0,
    // 0x33
    E0,
    // 0x34
    E0,
    // 0x35
    E0,
    // 0x36
    E0,
    // 0x37
    E0,
    // 0x38
    e(
        G::Vinsertx128,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Dq],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx2,
    ),
    // 0x39
    e(
        G::Vextractx128,
        Dec::None,
        [T::W, T::V, T::I],
        [Z::Dq, Z::Qq, Z::B],
        VEX6 | CHK_W0 | P_66,
        Ft::Avx2,
    ),
    // 0x3a
    E0,
    // 0x3b
    E0,
    // 0x3c
    E0,
    // 0x3d
    E0,
    // 0x3e
    E0,
    // 0x3f
    E0,
    // 0x40
    e(G::Vdpps, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | P_66 | OP3, Ft::Sse41),
    // 0x41
    e(G::Vdppd, Dec::None, [T::V, T::H, T::W], [Z::Dq, Z::Dq, Z::Dq], VEX2 | P_66 | OP3, Ft::Sse41),
    // 0x42
    e(
        G::Vmpsadbw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | AVX2_256 | P_66 | OP3,
        Ft::Sse41,
    ),
    // 0x43
    E0,
    // 0x44
    e(
        G::Pclmulqdq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Dq, Z::Dq, Z::Dq],
        VEX4 | P_66 | OP3,
        Ft::Pclmulqdq,
    ),
    // 0x45
    E0,
    // 0x46
    e(
        G::Vperm2x128,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::Qq, Z::Qq, Z::Qq],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx2,
    ),
    // 0x47
    E0,
    // 0x48
    E0,
    // 0x49
    E0,
    // 0x4a
    e(
        G::Vblendvps,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx,
    ),
    // 0x4b
    e(
        G::Vblendvpd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | CHK_W0 | P_66 | OP3,
        Ft::Avx,
    ),
    // 0x4c
    e(
        G::Vpblendvb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX6 | AVX2_256 | CHK_W0 | P_66 | OP3,
        Ft::Avx,
    ),
    // 0x4d
    E0,
    // 0x4e
    E0,
    // 0x4f
    E0,
    // 0x50
    E0,
    // 0x51
    E0,
    // 0x52
    E0,
    // 0x53
    E0,
    // 0x54
    E0,
    // 0x55
    E0,
    // 0x56
    E0,
    // 0x57
    E0,
    // 0x58
    E0,
    // 0x59
    E0,
    // 0x5a
    E0,
    // 0x5b
    E0,
    // 0x5c
    E0,
    // 0x5d
    E0,
    // 0x5e
    E0,
    // 0x5f
    E0,
    // 0x60
    e(
        G::Pcmpestrm,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::Dq, Z::Dq],
        VEX4 | SSE_UNALIGNED | P_66 | OP3,
        Ft::Sse42,
    ),
    // 0x61
    e(
        G::Pcmpestri,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::Dq, Z::Dq],
        VEX4 | SSE_UNALIGNED | P_66 | OP3,
        Ft::Sse42,
    ),
    // 0x62
    e(
        G::Pcmpistrm,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::Dq, Z::Dq],
        VEX4 | SSE_UNALIGNED | P_66 | OP3,
        Ft::Sse42,
    ),
    // 0x63
    e(
        G::Pcmpistri,
        Dec::None,
        [T::None, T::V, T::W],
        [Z::None, Z::Dq, Z::Dq],
        VEX4 | SSE_UNALIGNED | P_66 | OP3,
        Ft::Sse42,
    ),
    // 0x64
    E0,
    // 0x65
    E0,
    // 0x66
    E0,
    // 0x67
    E0,
    // 0x68
    E0,
    // 0x69
    E0,
    // 0x6a
    E0,
    // 0x6b
    E0,
    // 0x6c
    E0,
    // 0x6d
    E0,
    // 0x6e
    E0,
    // 0x6f
    E0,
    // 0x70
    E0,
    // 0x71
    E0,
    // 0x72
    E0,
    // 0x73
    E0,
    // 0x74
    E0,
    // 0x75
    E0,
    // 0x76
    E0,
    // 0x77
    E0,
    // 0x78
    E0,
    // 0x79
    E0,
    // 0x7a
    E0,
    // 0x7b
    E0,
    // 0x7c
    E0,
    // 0x7d
    E0,
    // 0x7e
    E0,
    // 0x7f
    E0,
    // 0x80
    E0,
    // 0x81
    E0,
    // 0x82
    E0,
    // 0x83
    E0,
    // 0x84
    E0,
    // 0x85
    E0,
    // 0x86
    E0,
    // 0x87
    E0,
    // 0x88
    E0,
    // 0x89
    E0,
    // 0x8a
    E0,
    // 0x8b
    E0,
    // 0x8c
    E0,
    // 0x8d
    E0,
    // 0x8e
    E0,
    // 0x8f
    E0,
    // 0x90
    E0,
    // 0x91
    E0,
    // 0x92
    E0,
    // 0x93
    E0,
    // 0x94
    E0,
    // 0x95
    E0,
    // 0x96
    E0,
    // 0x97
    E0,
    // 0x98
    E0,
    // 0x99
    E0,
    // 0x9a
    E0,
    // 0x9b
    E0,
    // 0x9c
    E0,
    // 0x9d
    E0,
    // 0x9e
    E0,
    // 0x9f
    E0,
    // 0xa0
    E0,
    // 0xa1
    E0,
    // 0xa2
    E0,
    // 0xa3
    E0,
    // 0xa4
    E0,
    // 0xa5
    E0,
    // 0xa6
    E0,
    // 0xa7
    E0,
    // 0xa8
    E0,
    // 0xa9
    E0,
    // 0xaa
    E0,
    // 0xab
    E0,
    // 0xac
    E0,
    // 0xad
    E0,
    // 0xae
    E0,
    // 0xaf
    E0,
    // 0xb0
    E0,
    // 0xb1
    E0,
    // 0xb2
    E0,
    // 0xb3
    E0,
    // 0xb4
    E0,
    // 0xb5
    E0,
    // 0xb6
    E0,
    // 0xb7
    E0,
    // 0xb8
    E0,
    // 0xb9
    E0,
    // 0xba
    E0,
    // 0xbb
    E0,
    // 0xbc
    E0,
    // 0xbd
    E0,
    // 0xbe
    E0,
    // 0xbf
    E0,
    // 0xc0
    E0,
    // 0xc1
    E0,
    // 0xc2
    E0,
    // 0xc3
    E0,
    // 0xc4
    E0,
    // 0xc5
    E0,
    // 0xc6
    E0,
    // 0xc7
    E0,
    // 0xc8
    E0,
    // 0xc9
    E0,
    // 0xca
    E0,
    // 0xcb
    E0,
    // 0xcc
    e(G::Sha1rnds4, Dec::None, [T::V, T::W, T::I], [Z::Dq, Z::Dq, Z::B], 0, Ft::ShaNi),
    // 0xcd
    E0,
    // 0xce
    E0,
    // 0xcf
    E0,
    // 0xd0
    E0,
    // 0xd1
    E0,
    // 0xd2
    E0,
    // 0xd3
    E0,
    // 0xd4
    E0,
    // 0xd5
    E0,
    // 0xd6
    E0,
    // 0xd7
    E0,
    // 0xd8
    E0,
    // 0xd9
    E0,
    // 0xda
    E0,
    // 0xdb
    E0,
    // 0xdc
    E0,
    // 0xdd
    E0,
    // 0xde
    E0,
    // 0xdf
    e(G::Vaeskeygen, Dec::None, [T::V, T::W, T::I], [Z::Dq, Z::Dq, Z::B], VEX4 | P_66, Ft::Aes),
    // 0xe0
    E0,
    // 0xe1
    E0,
    // 0xe2
    E0,
    // 0xe3
    E0,
    // 0xe4
    E0,
    // 0xe5
    E0,
    // 0xe6
    E0,
    // 0xe7
    E0,
    // 0xe8
    E0,
    // 0xe9
    E0,
    // 0xea
    E0,
    // 0xeb
    E0,
    // 0xec
    E0,
    // 0xed
    E0,
    // 0xee
    E0,
    // 0xef
    E0,
    // 0xf0
    e(G::Rorx, Dec::None, [T::G, T::E, T::I], [Z::Y, Z::Y, Z::B], VEX13 | P_F2, Ft::Bmi2),
    // 0xf1
    E0,
    // 0xf2
    E0,
    // 0xf3
    E0,
    // 0xf4
    E0,
    // 0xf5
    E0,
    // 0xf6
    E0,
    // 0xf7
    E0,
    // 0xf8
    E0,
    // 0xf9
    E0,
    // 0xfa
    E0,
    // 0xfb
    E0,
    // 0xfc
    E0,
    // 0xfd
    E0,
    // 0xfe
    E0,
    // 0xff
    E0,
];

pub(super) static OPCODES_0F10_REG: [E; 4] = [
    // 0x00
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x01
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x02
    e(G::Vmovss, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX5, Ft::None),
    // 0x03
    e(G::Vmovlpx, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX5, Ft::None),
];

pub(super) static OPCODES_0F10_MEM: [E; 4] = [
    // 0x00
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x01
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x02
    e(G::VmovssLd, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::Ss], VEX5, Ft::None),
    // 0x03
    e(G::VmovsdLd, Dec::None, [T::V, T::H, T::M], [Z::X, Z::X, Z::Sd], VEX5, Ft::None),
];

pub(super) static OPCODES_0F11_REG: [E; 4] = [
    // 0x00
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x01
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x02
    e(G::Vmovss, Dec::None, [T::W, T::H, T::V], [Z::X, Z::X, Z::X], VEX5, Ft::None),
    // 0x03
    e(G::Vmovlpx, Dec::None, [T::W, T::H, T::V], [Z::X, Z::X, Z::Q], VEX5, Ft::None),
];

pub(super) static OPCODES_0F11_MEM: [E; 4] = [
    // 0x00
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x01
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED,
        Ft::None,
    ),
    // 0x02
    e(G::VmovssSt, Dec::None, [T::M, T::None, T::V], [Z::Ss, Z::None, Z::X], VEX5, Ft::None),
    // 0x03
    e(G::VmovlpxSt, Dec::None, [T::M, T::None, T::V], [Z::Sd, Z::None, Z::X], VEX5, Ft::None),
];

pub(super) static OPCODES_0F12_MEM: [E; 4] = [
    // 0x00
    e(G::VmovlpxLd, Dec::None, [T::V, T::H, T::M], [Z::Dq, Z::Dq, Z::Q], VEX5, Ft::None),
    // 0x01
    e(G::VmovlpxLd, Dec::None, [T::V, T::H, T::M], [Z::Dq, Z::Dq, Z::Q], VEX5, Ft::None),
    // 0x02
    e(G::Vmovsldup, Dec::None, [T::V, T::None, T::W], [Z::X, Z::None, Z::X], VEX4, Ft::Sse3),
    // 0x03
    e(G::Vmovddup, Dec::None, [T::V, T::None, T::Wm], [Z::X, Z::None, Z::Q], VEX5, Ft::Sse3),
];

pub(super) static OPCODES_0F12_REG: [E; 4] = [
    // 0x00
    e(G::Vmovhlps, Dec::None, [T::V, T::H, T::U], [Z::Dq, Z::Dq, Z::Dq], VEX7, Ft::None),
    // 0x01
    e(G::Vmovlpx, Dec::None, [T::W, T::H, T::U], [Z::Dq, Z::Dq, Z::Q], VEX5, Ft::None),
    // 0x02
    e(G::Vmovsldup, Dec::None, [T::V, T::None, T::U], [Z::X, Z::None, Z::X], VEX4, Ft::Sse3),
    // 0x03
    e(G::Vmovddup, Dec::None, [T::V, T::None, T::U], [Z::X, Z::None, Z::X], VEX5, Ft::Sse3),
];

pub(super) static OPCODES_0F16_MEM: [E; 4] = [
    // 0x00
    e(G::VmovhpxLd, Dec::None, [T::V, T::H, T::M], [Z::Dq, Z::Dq, Z::Q], VEX5, Ft::None),
    // 0x01
    e(G::VmovhpxLd, Dec::None, [T::V, T::H, T::M], [Z::Dq, Z::Dq, Z::Q], VEX5, Ft::None),
    // 0x02
    e(G::Vmovshdup, Dec::None, [T::V, T::None, T::W], [Z::X, Z::None, Z::X], VEX4, Ft::Sse3),
    // 0x03
    E0,
];

pub(super) static OPCODES_0F16_REG: [E; 4] = [
    // 0x00
    e(G::Vmovlhps, Dec::None, [T::V, T::H, T::U], [Z::Dq, Z::Dq, Z::Q], VEX7, Ft::None),
    // 0x01
    e(G::Vmovhpx, Dec::None, [T::V, T::H, T::U], [Z::X, Z::X, Z::X], VEX5, Ft::None),
    // 0x02
    e(G::Vmovshdup, Dec::None, [T::V, T::None, T::U], [Z::X, Z::None, Z::X], VEX4, Ft::Sse3),
    // 0x03
    E0,
];

pub(super) static OPCODES_0F2A: [E; 4] = [
    // 0x00
    e(G::Cvtpi2px, Dec::None, [T::V, T::None, T::Q], [Z::X, Z::None, Z::Q], 0, Ft::None),
    // 0x01
    e(G::Cvtpi2px, Dec::None, [T::V, T::None, T::Q], [Z::X, Z::None, Z::Q], 0, Ft::None),
    // 0x02
    e(G::Vcvtsi2sx, Dec::None, [T::V, T::H, T::E], [Z::X, Z::X, Z::Y], VEX3, Ft::None),
    // 0x03
    e(G::Vcvtsi2sx, Dec::None, [T::V, T::H, T::E], [Z::X, Z::X, Z::Y], VEX3, Ft::None),
];

pub(super) static OPCODES_0F2B: [E; 4] = [
    // 0x00
    e(G::Movdq, Dec::None, [T::M, T::None, T::V], [Z::X, Z::None, Z::X], VEX1, Ft::None),
    // 0x01
    e(G::Movdq, Dec::None, [T::M, T::None, T::V], [Z::X, Z::None, Z::X], VEX1, Ft::None),
    // 0x02
    e(G::VmovssSt, Dec::None, [T::M, T::None, T::V], [Z::Ss, Z::None, Z::X], VEX4, Ft::Sse4a),
    // 0x03
    e(G::VmovlpxSt, Dec::None, [T::M, T::None, T::V], [Z::Sd, Z::None, Z::X], VEX4, Ft::Sse4a),
];

pub(super) static OPCODES_0F2C: [E; 4] = [
    // 0x00
    e(G::Cvttpx2pi, Dec::None, [T::P, T::None, T::W], [Z::Q, Z::None, Z::Q], 0, Ft::None),
    // 0x01
    e(G::Cvttpx2pi, Dec::None, [T::P, T::None, T::W], [Z::Q, Z::None, Z::Dq], 0, Ft::None),
    // 0x02
    e(G::Vcvttsx2si, Dec::None, [T::G, T::None, T::W], [Z::Y, Z::None, Z::Ss], VEX3, Ft::None),
    // 0x03
    e(G::Vcvttsx2si, Dec::None, [T::G, T::None, T::W], [Z::Y, Z::None, Z::Sd], VEX3, Ft::None),
];

pub(super) static OPCODES_0F2D: [E; 4] = [
    // 0x00
    e(G::Cvtpx2pi, Dec::None, [T::P, T::None, T::W], [Z::Q, Z::None, Z::Q], 0, Ft::None),
    // 0x01
    e(G::Cvtpx2pi, Dec::None, [T::P, T::None, T::W], [Z::Q, Z::None, Z::Dq], 0, Ft::None),
    // 0x02
    e(G::Vcvtsx2si, Dec::None, [T::G, T::None, T::W], [Z::Y, Z::None, Z::Ss], VEX3, Ft::None),
    // 0x03
    e(G::Vcvtsx2si, Dec::None, [T::G, T::None, T::W], [Z::Y, Z::None, Z::Sd], VEX3, Ft::None),
];

pub(super) static OPCODES_0F5A: [E; 4] = [
    // 0x00
    e(G::Vcvtps2pd, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::Xh], VEX2, Ft::None),
    // 0x01
    e(G::Vcvtpd2ps, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
    // 0x02
    e(G::Vcvtss2sd, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | REP_SCALAR, Ft::None),
    // 0x03
    e(G::Vcvtsd2ss, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | REP_SCALAR, Ft::None),
];

pub(super) static OPCODES_0F5B: [E; 4] = [
    // 0x00
    e(G::Vcvtdq2ps, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
    // 0x01
    e(G::Vcvtps2dq, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
    // 0x02
    e(G::Vcvttps2dq, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
    // 0x03
    E0,
];

pub(super) static OPCODES_0FE6: [E; 4] = [
    // 0x00
    E0,
    // 0x01
    e(G::Vcvttpd2dq, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
    // 0x02
    e(G::Vcvtdq2pd, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX5, Ft::None),
    // 0x03
    e(G::Vcvtpd2dq, Dec::None, [T::V, T::Op0, T::W], [Z::X, Z::X, Z::X], VEX2, Ft::None),
];

pub(super) static OPCODES_0F: [E; 256] = [
    // 0x00
    E0,
    // 0x01
    E0,
    // 0x02
    E0,
    // 0x03
    E0,
    // 0x04
    E0,
    // 0x05
    E0,
    // 0x06
    E0,
    // 0x07
    E0,
    // 0x08
    E0,
    // 0x09
    E0,
    // 0x0a
    E0,
    // 0x0b
    E0,
    // 0x0c
    E0,
    // 0x0d
    E0,
    // 0x0e
    E0,
    // 0x0f
    E0,
    // 0x10
    e(G::None, Dec::D0f10, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x11
    e(G::None, Dec::D0f11, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x12
    e(G::None, Dec::D0f12, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x13
    e(
        G::VmovlpxSt,
        Dec::None,
        [T::M, T::None, T::V],
        [Z::Q, Z::None, Z::Q],
        VEX5 | P_00 | P_66,
        Ft::None,
    ),
    // 0x14
    e(
        G::Vunpcklpx,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | P_00 | P_66,
        Ft::None,
    ),
    // 0x15
    e(
        G::Vunpckhpx,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | P_00 | P_66,
        Ft::None,
    ),
    // 0x16
    e(G::None, Dec::D0f16, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x17
    e(
        G::VmovhpxSt,
        Dec::None,
        [T::M, T::None, T::V],
        [Z::Q, Z::None, Z::Dq],
        VEX5 | P_00 | P_66,
        Ft::None,
    ),
    // 0x18
    E0,
    // 0x19
    E0,
    // 0x1a
    E0,
    // 0x1b
    E0,
    // 0x1c
    E0,
    // 0x1d
    E0,
    // 0x1e
    E0,
    // 0x1f
    E0,
    // 0x20
    E0,
    // 0x21
    E0,
    // 0x22
    E0,
    // 0x23
    E0,
    // 0x24
    E0,
    // 0x25
    E0,
    // 0x26
    E0,
    // 0x27
    E0,
    // 0x28
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::W],
        [Z::X, Z::None, Z::X],
        VEX1 | P_00 | P_66,
        Ft::None,
    ),
    // 0x29
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX1 | P_00 | P_66,
        Ft::None,
    ),
    // 0x2a
    e(G::None, Dec::D0f2a, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x2b
    e(G::None, Dec::D0f2b, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x2c
    e(G::None, Dec::D0f2c, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x2d
    e(G::None, Dec::D0f2d, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x2e
    e(
        G::None,
        Dec::Vxcomisx,
        [T::None, T::V, T::W],
        [Z::None, Z::X, Z::X],
        VEX3 | P_00 | P_66,
        Ft::None,
    ),
    // 0x2f
    e(
        G::None,
        Dec::Vxcomisx,
        [T::None, T::V, T::W],
        [Z::None, Z::X, Z::X],
        VEX3 | P_00 | P_66,
        Ft::None,
    ),
    // 0x30
    E0,
    // 0x31
    E0,
    // 0x32
    E0,
    // 0x33
    E0,
    // 0x34
    E0,
    // 0x35
    E0,
    // 0x36
    E0,
    // 0x37
    E0,
    // 0x38
    E0,
    // 0x39
    E0,
    // 0x3a
    E0,
    // 0x3b
    E0,
    // 0x3c
    E0,
    // 0x3d
    E0,
    // 0x3e
    E0,
    // 0x3f
    E0,
    // 0x40
    E0,
    // 0x41
    E0,
    // 0x42
    E0,
    // 0x43
    E0,
    // 0x44
    E0,
    // 0x45
    E0,
    // 0x46
    E0,
    // 0x47
    E0,
    // 0x48
    E0,
    // 0x49
    E0,
    // 0x4a
    E0,
    // 0x4b
    E0,
    // 0x4c
    E0,
    // 0x4d
    E0,
    // 0x4e
    E0,
    // 0x4f
    E0,
    // 0x50
    e(
        G::Movmsk,
        Dec::None,
        [T::G, T::None, T::U],
        [Z::Y, Z::None, Z::X],
        VEX7 | P_00 | P_66,
        Ft::None,
    ),
    // 0x51
    e(
        G::None,
        Dec::SseUnary,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x52
    e(
        G::None,
        Dec::SseUnary,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | REP_SCALAR | P_00 | P_F3,
        Ft::None,
    ),
    // 0x53
    e(
        G::None,
        Dec::SseUnary,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | REP_SCALAR | P_00 | P_F3,
        Ft::None,
    ),
    // 0x54
    e(G::Pand, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_00 | P_66, Ft::None),
    // 0x55
    e(G::Pandn, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_00 | P_66, Ft::None),
    // 0x56
    e(G::Por, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_00 | P_66, Ft::None),
    // 0x57
    e(G::Pxor, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX4 | P_00 | P_66, Ft::None),
    // 0x58
    e(
        G::Vadd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x59
    e(
        G::Vmul,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x5a
    e(G::None, Dec::D0f5a, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x5b
    e(G::None, Dec::D0f5b, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x5c
    e(
        G::Vsub,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x5d
    e(
        G::Vmin,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x5e
    e(
        G::Vdiv,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x5f
    e(
        G::Vmax,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2,
        Ft::None,
    ),
    // 0x60
    e(
        G::Punpcklbw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x61
    e(
        G::Punpcklwd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x62
    e(
        G::Punpckldq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x63
    e(
        G::Packsswb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x64
    e(
        G::Pcmpgtb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x65
    e(
        G::Pcmpgtw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x66
    e(
        G::Pcmpgtd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x67
    e(
        G::Packuswb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x68
    e(
        G::Punpckhbw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x69
    e(
        G::Punpckhwd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x6a
    e(
        G::Punpckhdq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x6b
    e(
        G::Packssdw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x6c
    e(
        G::Punpcklqdq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::None,
    ),
    // 0x6d
    e(
        G::Punpckhqdq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | P_66,
        Ft::None,
    ),
    // 0x6e
    e(
        G::MovdTo,
        Dec::None,
        [T::V, T::None, T::E],
        [Z::Dq, Z::None, Z::Y],
        VEX5 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x6f
    e(G::None, Dec::D0f6f, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x70
    e(G::None, Dec::D0f70, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x71
    e(G::None, Dec::Group12, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x72
    e(G::None, Dec::Group13, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x73
    e(G::None, Dec::Group14, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x74
    e(
        G::Pcmpeqb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x75
    e(
        G::Pcmpeqw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x76
    e(
        G::Pcmpeqd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0x77
    e(G::None, Dec::D0f77, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x78
    e(G::None, Dec::D0f78, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x79
    e(G::None, Dec::D0f79, [T::V, T::Op0, T::U], [Z::X, Z::X, Z::X], 0, Ft::Sse4a),
    // 0x7a
    E0,
    // 0x7b
    E0,
    // 0x7c
    e(G::Vhadd, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | P_66 | P_F2, Ft::Sse3),
    // 0x7d
    e(G::Vhsub, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | P_66 | P_F2, Ft::Sse3),
    // 0x7e
    e(G::None, Dec::D0f7e, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x7f
    e(G::None, Dec::D0f7f, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0x80
    E0,
    // 0x81
    E0,
    // 0x82
    E0,
    // 0x83
    E0,
    // 0x84
    E0,
    // 0x85
    E0,
    // 0x86
    E0,
    // 0x87
    E0,
    // 0x88
    E0,
    // 0x89
    E0,
    // 0x8a
    E0,
    // 0x8b
    E0,
    // 0x8c
    E0,
    // 0x8d
    E0,
    // 0x8e
    E0,
    // 0x8f
    E0,
    // 0x90
    E0,
    // 0x91
    E0,
    // 0x92
    E0,
    // 0x93
    E0,
    // 0x94
    E0,
    // 0x95
    E0,
    // 0x96
    E0,
    // 0x97
    E0,
    // 0x98
    E0,
    // 0x99
    E0,
    // 0x9a
    E0,
    // 0x9b
    E0,
    // 0x9c
    E0,
    // 0x9d
    E0,
    // 0x9e
    E0,
    // 0x9f
    E0,
    // 0xa0
    E0,
    // 0xa1
    E0,
    // 0xa2
    E0,
    // 0xa3
    E0,
    // 0xa4
    E0,
    // 0xa5
    E0,
    // 0xa6
    E0,
    // 0xa7
    E0,
    // 0xa8
    E0,
    // 0xa9
    E0,
    // 0xaa
    E0,
    // 0xab
    E0,
    // 0xac
    E0,
    // 0xad
    E0,
    // 0xae
    E0,
    // 0xaf
    E0,
    // 0xb0
    E0,
    // 0xb1
    E0,
    // 0xb2
    E0,
    // 0xb3
    E0,
    // 0xb4
    E0,
    // 0xb5
    E0,
    // 0xb6
    E0,
    // 0xb7
    E0,
    // 0xb8
    E0,
    // 0xb9
    E0,
    // 0xba
    E0,
    // 0xbb
    E0,
    // 0xbc
    E0,
    // 0xbd
    E0,
    // 0xbe
    E0,
    // 0xbf
    E0,
    // 0xc0
    E0,
    // 0xc1
    E0,
    // 0xc2
    e(
        G::Vcmp,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX2 | REP_SCALAR | P_00 | P_66 | P_F3 | P_F2 | OP3,
        Ft::None,
    ),
    // 0xc3
    E0,
    // 0xc4
    e(
        G::Pinsrw,
        Dec::None,
        [T::V, T::H, T::E],
        [Z::Dq, Z::Dq, Z::W],
        VEX5 | MMX | P_00 | P_66 | OP3,
        Ft::None,
    ),
    // 0xc5
    e(
        G::Pextrw,
        Dec::None,
        [T::G, T::U, T::I],
        [Z::D, Z::Dq, Z::B],
        VEX5 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xc6
    e(
        G::Vshuf,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | P_00 | P_66 | OP3,
        Ft::None,
    ),
    // 0xc7
    E0,
    // 0xc8
    E0,
    // 0xc9
    E0,
    // 0xca
    E0,
    // 0xcb
    E0,
    // 0xcc
    E0,
    // 0xcd
    E0,
    // 0xce
    E0,
    // 0xcf
    E0,
    // 0xd0
    e(G::Vaddsub, Dec::None, [T::V, T::H, T::W], [Z::X, Z::X, Z::X], VEX2 | P_66 | P_F2, Ft::Sse3),
    // 0xd1
    e(
        G::PsrlwR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd2
    e(
        G::PsrldR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd3
    e(
        G::PsrlqR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd4
    e(
        G::Paddq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd5
    e(
        G::Pmullw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd6
    e(G::None, Dec::D0fd6, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0xd7
    e(
        G::Pmovmskb,
        Dec::None,
        [T::G, T::None, T::U],
        [Z::D, Z::None, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd8
    e(
        G::Psubusb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xd9
    e(
        G::Psubusw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xda
    e(
        G::Pminub,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xdb
    e(
        G::Pand,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xdc
    e(
        G::Paddusb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xdd
    e(
        G::Paddusw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xde
    e(
        G::Pmaxub,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xdf
    e(
        G::Pandn,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe0
    e(
        G::Pavgb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe1
    e(
        G::PsrawR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe2
    e(
        G::PsradR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe3
    e(
        G::Pavgw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe4
    e(
        G::Pmulhuw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe5
    e(
        G::Pmulhw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe6
    e(G::None, Dec::D0fe6, [T::None, T::None, T::None], [Z::None, Z::None, Z::None], 0, Ft::None),
    // 0xe7
    e(
        G::Movdq,
        Dec::None,
        [T::W, T::None, T::V],
        [Z::X, Z::None, Z::X],
        VEX1 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe8
    e(
        G::Psubsb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xe9
    e(
        G::Psubsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xea
    e(
        G::Pminsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xeb
    e(
        G::Por,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xec
    e(
        G::Paddsb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xed
    e(
        G::Paddsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xee
    e(
        G::Pmaxsw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xef
    e(
        G::Pxor,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf0
    e(
        G::Movdq,
        Dec::None,
        [T::V, T::None, T::Wm],
        [Z::X, Z::None, Z::X],
        VEX4 | SSE_UNALIGNED | P_F2,
        Ft::Sse3,
    ),
    // 0xf1
    e(
        G::PsllwR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf2
    e(
        G::PslldR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf3
    e(
        G::PsllqR,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX7 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf4
    e(
        G::Pmuludq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf5
    e(
        G::Pmaddwd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf6
    e(
        G::Psadbw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf7
    e(
        G::Maskmov,
        Dec::None,
        [T::None, T::V, T::U],
        [Z::None, Z::Dq, Z::Dq],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf8
    e(
        G::Psubb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xf9
    e(
        G::Psubw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xfa
    e(
        G::Psubd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xfb
    e(
        G::Psubq,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xfc
    e(
        G::Paddb,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xfd
    e(
        G::Paddw,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xfe
    e(
        G::Paddd,
        Dec::None,
        [T::V, T::H, T::W],
        [Z::X, Z::X, Z::X],
        VEX4 | AVX2_256 | MMX | P_00 | P_66,
        Ft::None,
    ),
    // 0xff
    E0,
];
