[package]
name = "ruvm-hw-misc"
description = "pvpanic, watchdogs, IPMI, ivshmem, edu, testdevs and devices that fit nowhere else."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]
ruvm-base.workspace = true
ruvm-mem.workspace = true
ruvm-hw-core.workspace = true
ruvm-hw-pci.workspace = true

[lints]
workspace = true
