[package]
name = "ruvm-target-loongarch"
description = "The loongarch guest: CPU state, models, decoder and translator."
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[package.metadata.ruvm]
unsafe-budget = 0

[dependencies]

[lints]
workspace = true
